[package]
name = "domos"
version = "6.1.2"
description = "DOM.OS personal life operating system"
authors = ["DOM.OS"]
edition = "2021"

[lib]
name = "domos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tauri-plugin-updater = "2"
tauri-plugin-process = "2"
