import {invoke} from '@tauri-apps/api/core';
export async function verifyNativeGoals({services,context,otherProfile,report,check,until}){
 const data=key=>JSON.parse(window.DOMOSStorage.getItem('lifeos4.'+key)||'[]');
 const run=async request=>(await services.execute(context,request)).result;
 const click=(command,id)=>{const control=[...document.querySelectorAll('#page-goals [data-command]')].find(x=>x.dataset.command===command&&(!id||x.dataset.id===id));check(control,'Goal control missing: '+command);control.click()};
 const submit=async values=>{const dialog=document.querySelector('.dom62-goal-dialog:not(.dom62-search-dialog)'),form=dialog.querySelector('form');for(const [name,value] of Object.entries(values)){const field=form.querySelector(`[name="${name}"]`);check(field,'Goal field missing: '+name);field.value=value;}form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await until(()=>!dialog.open||!!dialog.querySelector('[data-error]').textContent);check(!dialog.open,dialog.querySelector('[data-error]').textContent);};
 report.stage='life-areas-goals-objectives';
 window.eval("showPage('goals')");click('areas');click('new-area');await submit({name:'Native Career'});const area=data('lifeAreas').find(x=>x.name==='Native Career');check(area,'Area form did not persist');click('goals');click('new-goal');check(document.querySelector('.dom62-goal-dialog form').querySelectorAll('input,select').length===3,'Goal creation requires unnecessary fields');await submit({name:'Native Life Goal',lifeAreaId:area.id,type:'outcome'});const goal=data('goals').find(x=>x.name==='Native Life Goal');check(goal&&!data('objectives').length,'Simple goal incorrectly requires Objectives');report.passed.push('native quick Life Area and Goal creation without mandatory Objectives');
 click('new-objective');await submit({name:'Native Objective',targetDate:'2026-12-31'});const objective=data('objectives').find(x=>x.goalId===goal.id);click('open-objective',objective.id);click('tab','Actions');click('create-action');await submit({title:'Native Goal Action',objectiveId:objective.id});const task=data('tasks').find(x=>x.title==='Native Goal Action');check(data('goalActionLinks').some(x=>x.actionId===task.id&&x.objectiveId===objective.id),'Goal action was not linked');click('complete-task',task.id);await until(()=>data('tasks').find(x=>x.id===task.id)?.status==='completed');const progress=await run({action:'goal.progress',id:goal.id});check(progress.progress.percent===100,'Objective/task automatic progress did not reach 100');check(data('tasks').filter(x=>x.id===task.id).length===1,'Action was duplicated');report.passed.push('native optional Objective Action linkage completion and automatic progress');
 window.DOMOSGoals.showGoal(goal.id);click('tab','Progress');click('progress-method');await submit({progressMethod:'numeric',current:'7250',target:'20000',start:'0',unit:'GBP'});check(document.getElementById('page-goals').textContent.includes('7250 / 20000 GBP'),'Numeric progress UI lost measurements');const ongoing=(await run({action:'goal.create',lifeAreaId:area.id,name:'Native Ongoing',type:'ongoing'})).item;const ongoingProgress=await run({action:'goal.progress',id:ongoing.id});check(ongoingProgress.progress.percent===null,'Ongoing goal fabricated a percentage');report.passed.push('native Numeric and Ongoing progress use truthful sources');
 const start=new Date(Date.now()-7200000).toISOString(),end=new Date(Date.now()-3600000).toISOString();const session=(await run({action:'work.log',title:'Native Goal Contribution',goalId:goal.id,objectiveId:objective.id,start,end})).item;const time=await run({action:'goal.time',id:goal.id});check(Math.abs(time.time.lifetime-3600000)<10,'Objective work was double-counted or lost');check(session.objectiveId===objective.id,'Work link lost the objective');report.passed.push('native linked Work Session rolls up exactly once to Goal time');
 await run({action:'focus.set',kind:'objective',targetId:objective.id});window.eval("showPage('dashboard');renderDashboard()");await until(()=>document.getElementById('dom612Goals')?.textContent.includes('Weekly Focus'));check(document.getElementById('dom612Goals').textContent.includes('7250 / 20000 GBP'),'Dashboard lost Numeric Goal data');check(document.querySelector('.dom62-today-focus')?.textContent.includes('Native Objective'),'Today lost relevant Weekly Focus');report.passed.push('native Weekly Focus dashboard and Today use persisted Goal data');
 document.dispatchEvent(new KeyboardEvent('keydown',{key:'k',ctrlKey:true,bubbles:true,cancelable:true}));const search=document.querySelector('.dom62-command-backdrop');check(!search.hidden,'Ctrl+K did not open real search');const input=search.querySelector('input');input.value='Native Objective';input.dispatchEvent(new Event('input',{bubbles:true}));check(search.textContent.includes('Objective'),'Search did not discover the objective');input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));await until(()=>document.querySelector('#page-goals h1').textContent==='Native Objective');check(document.querySelector('#page-goals h1').textContent==='Native Objective','Search opened the wrong detail');report.passed.push('native Ctrl+K finds and opens Objective detail');
 document.dispatchEvent(new KeyboardEvent('keydown',{ctrlKey:true,code:'Space',key:' ',bubbles:true}));const command=document.getElementById('dom62CommandInput'),form=command.closest('form'),submitButton=form.querySelector('[type=submit]');command.value='show goal p';command.setSelectionRange(command.value.length,command.value.length);command.dispatchEvent(new Event('input',{bubbles:true}));check([...document.querySelectorAll('.dom62-command-option')].some(x=>x.textContent.includes('Show goal progress')),'Goal autocomplete not registry-driven');command.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}));command.value+='Native Life Goal';command.dispatchEvent(new Event('input',{bubbles:true}));command.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));await until(()=>!submitButton.disabled&&data('assistantAudit').some(x=>x.originalCommand==='Show goal progress Native Life Goal'));check(document.querySelector('.dom62-command [data-result]').textContent.includes('7250'),'Assistant result lost numeric progress');document.querySelector('.dom62-command [data-close]').click();report.passed.push('native Goal assistant registry autocomplete execution and audit');
 const milestone=(await run({action:'milestone.create',goalId:goal.id,title:'Native Installer'})).item;await run({action:'milestone.complete',id:milestone.id});await run({action:'goal.note.create',goalId:goal.id,title:'Native planning',body:'Keep it calm'});await run({action:'area.checkin',id:area.id,rating:4,note:'Native check'});const archive=await services.execute(context,{action:'goal.archive',id:goal.id});check(data('goals').find(x=>x.id===goal.id)?.status==='Archived','Goal not archived');check(data('workSessions').some(x=>x.id===session.id),'Archive erased work');await services.undo(context,archive.undoId);check(data('goalActivity').some(x=>x.goalId===goal.id&&x.label==='Change undone'),'Goal Undo erased activity evidence');report.passed.push('native Milestones Notes check-ins archive and Undo preserve history');
 const backup=await invoke('profile_export',{profileId:context.profileId}),copy=await invoke('profile_import',{name:'Native Goal Backup Copy',payload:backup}),snapshot=await invoke('profile_snapshot',{profileId:copy.id});check(backup.schemaVersion===6,'Goal backup has wrong schema version');for(const name of ['lifeAreas','goals','objectives','goalActionLinks','goalMilestones','weeklyFocus','goalActivity','lifeAreaCheckins','notes','workSessions'])check(snapshot.data['lifeos4.'+name]===window.DOMOSStorage.getItem('lifeos4.'+name),'Goal backup lost '+name);const other=await invoke('profile_snapshot',{profileId:otherProfile});check(other.data['lifeos4.goals']==='[]'&&other.data['lifeos4.goalActionLinks']==='[]','Goal data escaped profile context');const before=(await invoke('profile_snapshot',{profileId:context.profileId})).data,bad=structuredClone(backup);bad.profiles[0].data['lifeos4.goalActionLinks']=JSON.stringify([{id:'invalid-link',goalId:goal.id,kind:'task',actionId:'foreign'}]);let rejected=false;try{await invoke('profile_restore',{profileId:context.profileId,payload:bad})}catch{rejected=true}check(rejected,'Broken goal restore succeeded');check(JSON.stringify((await invoke('profile_snapshot',{profileId:context.profileId})).data)===JSON.stringify(before),'Failed goal restore changed data');report.passed.push('native Goal schema-6 backup round trip profile isolation and invalid-restore rollback');
 window.DOMOSGoals.showGoal(goal.id);
}
