import {FINANCE_KEY,balance,moneyGBP,minor,actualTransactions,occurrences,protection,forecast,budgetSummary,getOccurrence} from '../application/finance.js';
import {dayInZone,profileZone,shiftDay,civilLabel} from '../application/date-time.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function installFinance(services,profileId){
 const context={profileId},read=()=>services.read(context,FINANCE_KEY),today=()=>dayInZone(services.now(),profileZone(services.storage.profile.preferences));let tab='overview',filter='',kind='',lastUndo=null,pending=null;
 const content=document.getElementById('financeContent');if(!content)return;
 const page=document.getElementById('page-finances');page.classList.add('dom62-finance');
 const hero=page.querySelector('.hero .top');if(hero){hero.replaceChildren();for(const [label,mode] of [['Add Expense','expense'],['Add Income','income'],['Record Transfer','transfer'],['Record Bill Payment','bills'],['Check Balance','check'],['Preview Spending/Transfer','forecast']]){const b=document.createElement('button');b.className='btn ghost';b.textContent=label;b.onclick=()=>dispatch(mode);hero.append(b);}}
 const feedback=document.createElement('section');feedback.className='dom62-finance-feedback';feedback.setAttribute('role','status');content.before(feedback);
 function status(text){feedback.replaceChildren();const p=document.createElement('p');p.textContent=text;feedback.append(p);if(lastUndo){const b=document.createElement('button');b.textContent='Undo';b.className='btn ghost';b.onclick=async()=>{try{await services.undo(context,lastUndo);lastUndo=null;render();status('Undone. Financial relationships were restored.');}catch(e){status(e.message)}};feedback.append(b);}}
 async function run(request){try{const out=await services.execute(context,request,{source:'ui'});if(out.status==='confirmation-required'){pending=out;feedback.replaceChildren();const p=document.createElement('p');p.textContent=[out.preview.details?.title,...(out.preview.details?.lines||[])].filter(Boolean).join('\n');p.style.whiteSpace='pre-line';feedback.append(p);for(const [label,handler] of [['Cancel',()=>{services.cancel(context,out.token);pending=null;status('Cancelled.');}],['Confirm',async()=>{try{const done=await services.confirm(context,out.token);pending=null;lastUndo=done.undoId;render();status('Recorded.');}catch(e){status(e.message)}}]]){const b=document.createElement('button');b.className='btn';b.textContent=label;b.onclick=handler;feedback.append(b);}feedback.scrollIntoView?.({block:'nearest'});return out;}
  lastUndo=out.undoId;render();status(out.result.check?'Observed '+moneyGBP(out.result.check.observedMinor)+' · difference '+moneyGBP(out.result.check.differenceMinor)+(out.result.check.differenceMinor>0?' (bank higher)':out.result.check.differenceMinor<0?' (bank lower)':' (matches ledger)')+(out.result.check.basis==='available'?'. Available balances do not verify the posted ledger.':''):'Recorded.');return out;
 }catch(e){status(e.message);throw e;}}
 const buttons=items=>items.map(([label,action,id])=>`<button class="btn ghost" data-action="${action}" data-id="${esc(id||'')}">${esc(label)}</button>`).join(' ');
 const card=(title,body)=>`<section class="card fin-card"><h3>${esc(title)}</h3>${body}</section>`;
 function bind(host){host.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>dispatch(b.dataset.action,b.dataset.id));}
 function render(){const s=read(),day=today(),p=protection(s,s.settings.primaryAccountId,day,{zone:profileZone(services.storage.profile.preferences)}),tx=actualTransactions(s);document.querySelectorAll('#financeTabs button').forEach(b=>{b.classList.toggle('active',b.dataset.finTab===tab);b.onclick=()=>{tab=b.dataset.finTab;render();}});
  if(tab==='overview'){const account=s.accounts.find(a=>a.id===p.accountId),unexplained=s.transactions.filter(t=>t.type==='adjustment'&&!t.voided);content.innerHTML=`<div class="dom62-finance-grid">${card('Available to Transfer',`<p>${esc(account?.name||'Choose your receiving / bill-paying account')}</p><strong class="dom62-finance-value">${account?moneyGBP(p.remainingMinor):'Set up an account'}</strong><p>${p.remainingMinor<0?'Recorded funding shortfall':p.ready?'Estimated uncommitted recorded cash':'Provisional estimate · setup or verification needed'}</p><p class="muted">${s.settings.horizon}-day protection · expected income excluded</p>${buttons([['Check Balance','check',p.accountId],['Review Commitments','settings']])}<details><summary>How this is calculated</summary><p>Recorded balance ${moneyGBP(p.balanceMinor)} − commitments ${moneyGBP(p.protectedMinor)}</p>${p.commitments.map(c=>`<p>${esc(c.name)} ${moneyGBP(c.amountMinor)}${c.estimate?' · estimate':''}${c.overdue?' · overdue':''}${c.nextOccurrenceId?' '+buttons([['Review oldest','occurrence',c.nextOccurrenceId]]):''}</p>`).join('')}<p>Last verified: ${p.verifiedAt?esc(window.DOMOSDate?.timestampLabel(p.verifiedAt)||p.verifiedAt):'Never'}</p>${p.gaps.map(g=>`<p>${esc(g)}</p>`).join('')}</details>`)}${card('Recorded accounts',s.accounts.map(a=>`<div class="dom62-finance-row"><span>${esc(a.name)}<small>${esc(a.type)}${!a.supported?' · unsupported credit / legacy facility':''}${a.archived?' · archived':''}</small></span><b>${moneyGBP(balance(s,a.id))}</b>${buttons([['Check','check',a.id]])}</div>`).join('')||'<p>Add today’s real account positions. No historic purchases are required.</p>')}${card('Finance Catch-up',`<p>Review recorded balances and upcoming obligations. Dates passing never create transactions.</p>${buttons([['Check Balance','check'],['Bills & Income','bills'],['Add Account','account'],['Protected Money','allocation']])}<p>${unexplained.length} unexplained adjustment${unexplained.length===1?'':'s'} · ${s.legacy.bills.filter(b=>!b.reviewed).length} legacy bills to review</p>${unexplained.map(t=>`<p>${moneyGBP(t.amountMinor)} ${buttons([['Explain','explain',t.id]])}</p>`).join('')}`)}</div>`;
  }else if(tab==='accounts'){content.innerHTML=card('Accounts',buttons([['Add Account','account'],['Planning settings','settings']])+s.accounts.map(a=>`<div class="dom62-finance-row"><span><b>${esc(a.name)}</b><small>${esc(a.bank||'Manual')} · GBP · ${esc(a.type)}${a.archived?' · archived':''}</small><small>Opening ${moneyGBP(a.openingMinor)} · ${esc(a.openingSource)} · last verified ${a.verifiedAt?esc(window.DOMOSDate?.timestampLabel(a.verifiedAt)||a.verifiedAt):'never'}</small></span><strong>${moneyGBP(balance(s,a.id))}</strong>${buttons([['Edit','account',a.id],['Check Balance','check',a.id],['History','account-history',a.id],[a.archived?'Restore':'Archive',a.archived?'reopen':'archive',a.id]])}</div>`).join(''));
  }else if(tab==='transactions'){content.innerHTML=card('Transaction history',`<p class="muted">Actual recorded activity. Legacy history is retained without reposting against migrated balances.</p>${buttons([["Add historical information","historical"]])}<label>Account<select id="dom62FinanceFilter"><option value="">All accounts / unallocated</option>${s.accounts.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}</select></label><label>Type<select id="dom62FinanceKind"><option value="">All activity</option>${['income','expense','transfer','adjustment'].map(k=>`<option>${k}</option>`).join('')}</select></label>${s.transactions.filter(t=>(!filter||t.accountId===filter||t.toAccountId===filter)&&(!kind||t.type===kind)).slice().sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate)).map(t=>`<div class="dom62-finance-row"><span><b>${esc(t.description||t.type)}</b><small>${esc(t.effectiveDate)} · ${esc(t.category||'Uncategorised')} · ${esc(s.accounts.find(a=>a.id===t.accountId)?.name||'Unallocated / missing legacy account')}${t.toAccountId?' → '+esc(s.accounts.find(a=>a.id===t.toAccountId)?.name):''}</small><small>${t.voided?'Reversed / excluded':t.historical?'Historical · not posted':'Posted'}${t.annotation?' · '+esc(t.annotation):''}</small></span><b>${moneyGBP(t.amountMinor)}</b>${!t.voided?buttons(t.historical?[['Correct history','correct',t.id],['Annotate','annotate',t.id],['Exclude from reports','history-reverse',t.id]]:[['Correct','correct',t.id],['Reverse','reverse',t.id]]):''}</div>`).join('')||'<p>No recorded transactions.</p>'}`);const a=content.querySelector('#dom62FinanceFilter'),k=content.querySelector('#dom62FinanceKind');a.value=filter;k.value=kind;a.onchange=()=>{filter=a.value;render()};k.onchange=()=>{kind=k.value;render()};
  }else if(tab==='bills'){const upcoming=occurrences(s,shiftDay(day,-366),shiftDay(day,s.settings.horizon));content.innerHTML=card('Bills, subscriptions & expected income',`<p class="muted">Occurrences are plans, never cash. Record or match the real payment / receipt.</p>${buttons([['Add Bill','bill'],['Monthly Income','monthly-income'],['Four-weekly Income','four-income'],['Add Income Schedule','income-rule']])}<div>${s.rules.map(r=>`<p><b>${esc(r.name)}</b> · ${moneyGBP(r.amountMinor)} · ${esc(r.frequency)}${r.archived?' · archived':''} ${buttons([['Edit','rule',r.id],[r.archived?'Restore':'Archive',r.archived?'rule-reopen':'rule-archive',r.id]])}</p>`).join('')}</div>${upcoming.map(o=>`<div class="dom62-finance-row"><span><b>${esc(o.name)}</b><small>${esc(o.date)} · ${o.kind==='income'?'Conditional expected income':'Bill'}${o.estimate?' · estimated':''}</small><small>${moneyGBP(o.settledMinor)} recorded / ${moneyGBP(o.outstandingMinor)} outstanding</small></span>${buttons([...(o.outstandingMinor>0?[['Record '+(o.kind==='income'?'Receipt':'Payment'),'pay',o.id]]:[]),['Change / skip','occurrence',o.id]])}</div>`).join('')}<h3>Preserved legacy bills</h3>${s.legacy.bills.map(b=>`<p>${esc(b.name)} · old ${b.paid?'paid':'unpaid'} flag · ${b.reviewed?'reviewed':buttons([['Configure','legacy-config',b.id],['No longer needed','legacy-review',b.id]])}</p>`).join('')}<p>Legacy paid flags do not create fictional expenses. Historical anchors do not create income receipts.</p>`);
  }else if(tab==='budget'){content.innerHTML=card('Category budgets',`<p>Targets for recorded spending; budgets do not deduct account cash.</p>${buttons([['Add Budget','budget']])}${budgetSummary(s,day).items.map(b=>{if(b.needsReview)return `<p>${esc(b.category)} · legacy target requires review ${buttons([['Review','budget',b.id]])}</p>`;const limit=b.limitMinor,spent=b.spentMinor;return `<p>${esc(b.category)} · ${moneyGBP(spent)} / ${moneyGBP(limit)} this budget period ${buttons([['Edit','budget',b.id],['Archive','budget-archive',b.id]])}</p>`}).join('')}`);
  }else if(tab==='savings'){content.innerHTML=card('Savings goals & protected money',`<p>Savings progress is not extra cash. Protection earmarks existing money in a specific account.</p>${buttons([['Add Savings Goal','saving'],['Protect Money','allocation']])}${s.legacy.savings.filter(g=>!g.archived).map(g=>`<p>${esc(g.name)} · ${esc(g.current)} / ${esc(g.target)} ${esc(g.needsReview?s.legacy.originalCurrency||'unknown currency':'GBP')} progress${g.needsReview?' · needs review':''} ${buttons([['Edit','saving',g.id],['Archive','saving-archive',g.id]])}</p>`).join('')}<h3>Protected allocations</h3>${s.allocations.map(a=>`<p>${esc(a.name)} · ${moneyGBP(a.amountMinor)} · ${esc(a.kind)} ${buttons([['Edit','allocation',a.id],['Remove','allocation-remove',a.id]])}</p>`).join('')}`);
  }else{const f=forecast(s,day);content.innerHTML=card('Cash-flow forecast',`<p>${esc(f.assumptions)}</p>${buttons([['What if…','forecast']])}${f.rows.map(o=>`<div class="dom62-finance-row"><span>${esc(o.date)} · ${esc(o.name)}<small>${esc(s.accounts.find(a=>a.id===o.accountId)?.name)}${o.conditional?' · conditional expected income':''}${o.estimate?' · estimate':''}</small></span><b>${moneyGBP(o.projectedMinor)}${o.shortfall?' · projected shortfall':''}</b></div>`).join('')||'<p>Add expected income and bills to see a projection.</p>'}`);}
  if(s.legacy.quarantine.length)content.insertAdjacentHTML('beforeend',card('Preserved records requiring review',s.legacy.quarantine.map(q=>`<details><summary>${esc(q.collection)} · ${esc(q.reason)}</summary><pre>${esc(JSON.stringify(q.raw,null,2))}</pre>${q.reviewed?"<p>Reviewed · retained without posting</p>":buttons([["Mark reviewed / retain","quarantine-review",q.id]])}</details>`).join('')));bind(content);window.DOMOS612?.renderFinanceWidget?.();
 }
 function dispatch(mode,id){if(mode==='bills'){tab='bills';render();return;}if(mode==='account-history'){filter=id;tab='transactions';render();return;}const commands={reopen:'finance.account.reopen','rule-reopen':'finance.rule.reopen','history-reverse':'finance.history.reverse',archive:'finance.account.archive',reverse:'finance.transaction.reverse','rule-archive':'finance.rule.archive','allocation-remove':'finance.allocation.remove','legacy-review':'finance.legacy.review','quarantine-review':'finance.quarantine.review','budget-archive':'finance.budget.archive','saving-archive':'finance.saving.archive'};if(commands[mode]){run({action:commands[mode],id,operationId:crypto.randomUUID()}).catch(()=>{});return;}form(mode,id);}
 function form(mode,id=''){
  const s=read(),day=today(),account=s.accounts.find(a=>a.id===id),tx=s.transactions.find(t=>t.id===id),rule=s.rules.find(r=>r.id===id),o=['pay','occurrence'].includes(mode)?getOccurrence(s,id):null,allocation=s.allocations.find(a=>a.id===id),legacy=s.legacy.bills.find(b=>b.id===id);const drawer=document.getElementById('drawer'),body=document.getElementById('drawerBody'),title=document.getElementById('drawerTitle');if(!drawer||!body)return;
  const input=(key,label,value='',type='text')=>`<label>${esc(label)}<input name="${key}" type="${type}" value="${esc(value)}" ${type==='number'?'step="1"':''}></label>`,select=(key,label,rows,value='')=>`<label>${esc(label)}<select name="${key}">${rows.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`,amount=(key='amount',label='Amount (GBP)',value='')=>input(key,label,value),accounts=(key='accountId',label='Account',value=s.settings.primaryAccountId)=>select(key,label,s.accounts.filter(a=>a.supported&&!a.archived).map(a=>[a.id,a.name]),value),date=(value=day)=>input('date','Effective date',value,'date');let html='',action='';
  title.textContent=({historical:'Add Historical Information',correct:'Correct Transaction',annotate:'Historical Note',allocation:'Protect Money',budget:'Category Budget',saving:'Savings Progress','monthly-income':'Monthly Expected Income','four-income':'Four-weekly Expected Income','income-rule':'Expected Income Schedule',rule:'Recurring Schedule','legacy-config':'Review Legacy Bill',expense:'Add Expense',income:'Add Income',transfer:'Record Transfer',check:'Check Balance',forecast:'Preview Spending / Transfer',pay:'Record Actual Payment / Receipt',bill:'Add Bill',account:'Account',settings:'Finance Planning',explain:'Explain Adjustment',occurrence:'Occurrence Exception'})[mode]||mode.replaceAll('-',' ');
  if(['expense','income','historical'].includes(mode)){action=mode==='historical'?'finance.history.create':'finance.transaction.create';html=(mode==='historical'?'<p>Historical information only. This will not change any opening position or account balance.</p>'+select('type','Recorded type',[['expense','Expense'],['income','Income']])+select('accountId','Historical account',[['','Unallocated'],...s.accounts.map(a=>[a.id,a.name])]):accounts('accountId','Account',mode==='expense'?s.settings.spendingAccountId||s.settings.primaryAccountId:s.settings.primaryAccountId))+amount()+date()+input('description','Payee / description (optional)')+input('category','Category (optional)')+(s.transactions.some(t=>t.type==='adjustment'&&!t.voided)?'<p>If this explains a forgotten activity already included in a checked balance, use Explain Adjustment to avoid deducting it twice.</p>':'');}
  else if(mode==='transfer'){action='finance.transfer';html='<p>Record a transfer already performed in your banking app. DOM.OS does not send money.</p>'+accounts('accountId','From')+accounts('toAccountId','To',s.settings.spendingAccountId)+amount()+date();}
  else if(mode==='account'){action='finance.account.save';html=input('name','Account name',account?.name||'')+input('bank','Bank (optional)',account?.bank||'')+(account?'':select('type','Type',['Current','Savings','Cash'].map(t=>[t,t]))+amount('amount','Opening position today (GBP)','0'))+'<p>Existing account balances change through transactions or Check Balance.</p>';}
  else if(mode==='check'){action='finance.balance.check';html=accounts('accountId','Account',id||s.settings.primaryAccountId)+amount('amount','Observed bank balance (GBP)')+select('basis','Comparison basis',[['booked','Posted / booked balance'],['available','Available balance (information only)']])+ '<p>Use the posted/booked amount for reconciliation. Pending card authorisations can make an available balance incompatible.</p>';}
  else if(mode==='correct'){action=tx.historical?'finance.history.correct':'finance.transaction.correct';if(tx.historical)title.textContent='Correct Historical Information (no balance change)';html=amount('amount','Corrected amount (GBP)',String(tx.amountMinor/100))+date(tx.effectiveDate)+input('description','Description',tx.description||'')+input('category','Category',tx.category||'')+input('notes','Notes',tx.notes||'');}
  else if(mode==='annotate'){action='finance.history.annotate';html=input('notes','Historical annotation',tx.annotation||'')+'<p>This does not repost legacy activity or change the preserved amount.</p>';}
  else if(mode==='explain'){action='finance.adjustment.explain';html=amount('amount','Amount to explain (GBP)',String(Math.abs(tx.amountMinor)/100))+input('description','What was the missing activity?')+input('category','Category (optional)')+'<p>Replace all or part of the unexplained adjustment; the confirmed balance stays the same.</p>';}
  else if(mode==='pay'){action='finance.occurrence.pay';html=accounts('accountId','Account for a new payment / receipt',o.accountId)+amount('amount','Amount actually paid / received (GBP)',String(o.outstandingMinor/100))+date()+select('transactionId','Or match a record (uses its recorded account)',[['','Create actual transaction'],...s.transactions.filter(t=>!t.voided&&!t.internalTransfer&&t.effectiveDate<=day&&!t.occurrenceId&&t.type===o.kind&&s.accounts.some(a=>a.id===t.accountId&&a.supported&&!a.archived)).map(t=>[t.id,t.effectiveDate+' · '+(t.description||t.type)+' · '+moneyGBP(t.amountMinor)+(t.historical?' · historical / not posted':'')])]);}
  else if(mode==='occurrence'){action='finance.occurrence.update';html=input('date','Occurrence date',o.date,'date')+amount('amount','Expected amount (GBP)',String(o.amountMinor/100))+select('status','Status',[['expected','Expected / delayed'],['skipped','Skip this occurrence'],['cancelled','Cancel this occurrence']],o.status);}
  else if(['bill','income-rule','monthly-income','four-income','rule','legacy-config'].includes(mode)){action='finance.rule.save';const income=mode.includes('income')||rule?.kind==='income',anchor=rule?.anchor||(mode==='four-income'?'2026-10-01':day),frequency=rule?.frequency||(mode==='four-income'?'four-weekly':mode==='monthly-income'?'monthly':'once');html=input('name','Name',rule?.name||legacy?.name||'')+select('kind','Type',[['expense','Bill / subscription'],['income','Expected income']],income?'income':'expense')+amount('amount','Expected amount (GBP)',String((rule?.amountMinor??(legacy?.amount&&s.legacy.originalCurrency==='GBP'?minor(legacy.amount):0))/100))+accounts('accountId','Expected account',rule?.accountId||legacy?.accountId||s.settings.primaryAccountId)+input('anchor','Schedule anchor',anchor,'date')+select('frequency','Repeats',['once','weekly','four-weekly','monthly','quarterly','annually'].map(v=>[v,v]),frequency)+input('day','Intended monthly day (optional)',rule?.day||(mode==='monthly-income'?27:''),'number')+select('weekend','Weekend adjustment',[['none','None'],['preceding-friday','Preceding Friday']],rule?.weekend||(mode==='monthly-income'?'preceding-friday':'none'))+select('estimate','Certainty of amount / due date',[['','Known details'],['yes','Estimated details']],rule?.estimate?'yes':'')+input('category','Category (optional)',rule?.category||'')+(rule?input('effectiveDate','New terms apply from',day,'date'):'')+select('reminder','Bill reminder',[['yes','Enabled'],['','Off']],rule?.reminder===false?'':'yes')+'<p>Expected dates never post cash. Individual exceptions leave the base schedule unchanged.</p>';}
  else if(mode==='settings'){action='finance.settings';html=accounts('primaryAccountId','Receiving / bill-paying account',s.settings.primaryAccountId)+accounts('spendingAccountId','Everyday spending account',s.settings.spendingAccountId)+input('horizon','Protection period (days)',s.settings.horizon,'number')+input('budgetDay','Budget cycle day (blank = calendar month)',s.settings.budgetDay||'','number')+select('billsReviewed','Commitment coverage',[['','Still configuring'],['yes','I have reviewed my current bills']]);}
  else if(mode==='allocation'){action='finance.allocation.save';html=input('name','Protection name',allocation?.name||'')+accounts('accountId','Funding account',allocation?.accountId||s.settings.primaryAccountId)+amount('amount','Protected amount (GBP)',allocation?String(allocation.amountMinor/100):'')+select('kind','Purpose',['independent','essentials','buffer','bill'].map(k=>[k,k]),allocation?.kind||'independent')+select('ruleId','Linked bill (for bill protection)',[['','None'],...s.rules.filter(r=>r.kind==='expense'&&!r.archived).map(r=>[r.id,r.name])],allocation?.ruleId||'')+input('category','Essentials category (optional)',allocation?.category||'')+input('startDate','Allowance start',allocation?.startDate||day,'date')+input('endDate','Allowance end',allocation?.endDate||shiftDay(day,s.settings.horizon),'date')+'<p>Linked bill amounts remain the total reserve at their original settlement baseline. Payments already counted continue to reduce that reserve after edits.</p>';}
  else if(mode==='budget'||mode==='saving'){const row=s.legacy[mode==='budget'?'budgets':'savings'].find(x=>x.id===id);action=mode==='budget'?'finance.budget.save':'finance.saving.save';html=input('name',mode==='budget'?'Category':'Goal name',row?.category||row?.name||'')+amount('amount',mode==='budget'?'Pay-cycle target (GBP)':'Recorded savings progress (GBP)',String((mode==='budget'?row?.limit:row?.current)||0))+(mode==='saving'?amount('target','Goal target (GBP)',String(row?.target||0)):'');}
  else if(mode==='forecast'){html=accounts('accountId','Scenario source account')+amount('amount','What if I spend / transfer (GBP)','0')+select('toAccountId','Destination (empty means spending)',[['','Spend'],...s.accounts.filter(a=>a.supported&&!a.archived).map(a=>[a.id,a.name])]);}
  else return;
  body.innerHTML=`<form class="dom62-finance-form"><div class="dom62-finance-fields">${html}<p data-error role="alert"></p></div><footer class="dom62-finance-actions"><button class="btn ghost" type="button" data-finance-cancel>Cancel</button><button class="btn" type="submit">${mode==='forecast'?'Preview':'Save / Review'}</button></footer></form>`;drawer.classList.add('show');const f=body.querySelector('form'),operationId=crypto.randomUUID(),previousFocus=document.activeElement;f.querySelector('[data-finance-cancel]').onclick=()=>{drawer.classList.remove('show');window.dispatchEvent(new Event('domos-editor-closed'));previousFocus?.focus();};f.querySelector('input,select')?.focus();if(f.elements.namedItem('reminder')&&f.elements.namedItem('kind')){const syncReminder=()=>{f.elements.namedItem('reminder').closest('label').hidden=f.elements.namedItem('kind').value==='income';};f.elements.namedItem('kind').onchange=syncReminder;syncReminder();}f.onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(f)),button=f.querySelector('[type=submit]');button.disabled=true;try{if(mode==='forecast'){const preview=forecast(read(),day,{accountId:values.accountId,scenarioMinor:minor(values.amount,{zero:true}),toAccountId:values.toAccountId||undefined});f.querySelector('[data-error]').textContent=preview.assumptions+' '+Object.entries(preview.balances).map(([id,n])=>(s.accounts.find(a=>a.id===id)?.name||id)+': '+moneyGBP(n)).join(' · ');return;}
   const request={...values,action,operationId,expectedFinanceRevision:s.revision,...(id?{id}:{})};if(['expense','income'].includes(mode))request.type=mode;if(mode==='check')delete request.id;if(mode==='legacy-config'){request.legacyId=id;delete request.id;}if('estimate'in request)request.estimate=request.estimate==='yes';if('reminder'in request)request.reminder=request.kind==='expense'&&request.reminder==='yes';if('horizon'in request)request.horizon=Number(request.horizon);if('budgetDay'in request)request.budgetDay=request.budgetDay?Number(request.budgetDay):null;if('billsReviewed'in request)request.billsReviewed=request.billsReviewed==='yes';const out=await run(request);drawer.classList.remove('show');if(out.result?.check?.differenceMinor&&out.result.check.basis==='booked'){const b=document.createElement('button');b.className='btn';b.textContent='Review explicit reconciliation';b.onclick=()=>run({action:'finance.balance.reconcile',id:out.result.check.id,operationId:crypto.randomUUID()}).catch(()=>{});feedback.append(b);}
  }catch(error){f.querySelector('[data-error]').textContent=error.message;}finally{button.disabled=false;}};
 }
 function widget(host){const s=read(),p=protection(s,s.settings.primaryAccountId,today(),{zone:profileZone(services.storage.profile.preferences)}),a=s.accounts.find(a=>a.id===p.accountId);host.innerHTML=`<div class="dom612-finance"><div class="dom612-finance-main"><div><strong>${a?moneyGBP(p.remainingMinor):'Set up Finance'}</strong><span>${p.remainingMinor<0?'Recorded funding shortfall':p.ready?'Estimated available to transfer':'Provisional · check balance / commitments'}</span></div></div><p class="muted">${esc(a?.name||'GBP accounts')} · ${s.settings.horizon}-day protection</p>${buttons([['Review','overview']])}</div>`;host.querySelector('button').onclick=e=>{e.stopPropagation();tab='overview';services.navigate('finances');render();};}
 window.DOMOSFinance={render,form,widget,read,totals:()=>{const v=services.plan(context,{action:'finance.summary'}).result;return {balance:v.accountBalance,total:v.accountBalance,income:v.income,spent:v.expenses,safe:v.protection.remainingMinor/100,currency:'GBP'};},formatMajor:value=>moneyGBP(Math.round(Number(value||0)*100)),openBill:id=>{tab='bills';services.navigate('finances');render();if(!id)return;const legacy=read().legacy.bills.find(b=>b.id===id);if(legacy?.ruleId&&read().rules.some(r=>r.id===legacy.ruleId))form('rule',legacy.ruleId);else if(legacy)form('legacy-config',id);else if(read().rules.some(r=>r.id===id))form('rule',id);else form('occurrence',id);}};
 window.eval('financeTotals=function(){return window.DOMOSFinance.totals()};money=function(value){return window.DOMOSFinance.formatMajor(value)};renderFinance=function(){window.DOMOSFinance.render()};openFinanceAccount=function(id){window.DOMOSFinance.form("account",id)};openTransaction=function(id){window.DOMOSFinance.form(id?"correct":"expense",id)};openFinanceBill=function(id){if(id)window.DOMOSFinance.openBill(id);else window.DOMOSFinance.form("bill")};openFinanceBudget=function(id){window.DOMOSFinance.form("budget",id)};openFinanceSaving=function(id){window.DOMOSFinance.form("saving",id)};toggleFinanceBill=function(){throw Error("Record an actual bill payment in Finance")};');
 window.addEventListener('domos-profile-refreshed',render);window.addEventListener('storage',e=>{if(e.key===FINANCE_KEY){render();window.DOMOS612?.enhanceDashboard?.();}});render();return window.DOMOSFinance;
}
