import {reviewData,reviewPeriod,reviewFor,periodSummary,suggestions,taskDeadline} from '../application/reviews.js';
import {dayInZone,shiftDay,profileZone,civilLabel,clockInZone,civilInstant} from '../application/date-time.js';
import {trackingValue,habitStatusLabel} from './habits-trackers-ui.js';
import {weekKey} from '../application/goals.js';
import {installDateReconciliation} from '../application/rollover.js';
import './reviews.css';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,attrs='')=>`<button type="button" data-review="${action}" ${attrs}>${label}</button>`;
const duration=ms=>`${Math.floor(ms/3600000)}h ${Math.floor(ms%3600000/60000)}m`;
export function installReviews(services,profileId){
 const context={profileId},prefs=()=>services.storage.profile.preferences||{},today=()=>dayInZone(services.now(),profileZone(prefs()));
 let kind='daily',date=today(),id=null,mode='summary',step='summary',limit=5,busy=false,reset=false,historyFilter='all',actionError='';const drafts=new Map(),checkinSubmissions=new Map();
 const page=document.createElement('div');page.id='page-reviews';page.className='page rv-page';document.querySelector('.main').append(page);
 const correction=document.createElement('dialog');correction.className='rv-correction';correction.setAttribute('aria-label','Correct recorded work');document.body.append(correction);const status=document.createElement('div');status.className='rv-notice';status.hidden=true;status.setAttribute('role','status');document.body.append(status);
 function model(){const data=reviewData(services,context),row=id?data[kind==='daily'?'dailyReviews':'weeklyReviews'].find(r=>r.id===id):reviewFor(data,kind,date,prefs()),period=row||reviewPeriod(kind,date,prefs());return {data,row,period,summary:periodSummary(data,period,{now:services.now()}),ahead:suggestions(data,period,{now:services.now()}),pins:[...data.trackerPins].sort((a,b)=>a.order-b.order).map(p=>data.trackers.find(t=>t.id===p.trackerId&&!t.archived)).filter(Boolean)}}
 const draftKey=m=>kind+'|'+m.period.periodKey;
 function captureDraft(){const area=page.querySelector('[data-reflection]');if(area)drafts.set(area.dataset.key,area.value);}
 function notice(text,undoId){status.hidden=false;status.replaceChildren(document.createTextNode(text));if(undoId){const b=document.createElement('button');b.textContent='Undo';b.onclick=async()=>{try{await services.undo(context,undoId);render(true);notice('Undone.')}catch(e){notice(e.message)}};status.append(b)}const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','Dismiss review message');close.onclick=()=>status.hidden=true;status.append(close)}
 async function act(request){if(busy)return;actionError='';captureDraft();busy=true;page.setAttribute('aria-busy','true');page.querySelectorAll('button').forEach(b=>b.disabled=true);try{const o=await services.execute(context,{kind,date,...(id?{id}:{}),...request},{source:'ui'});if(o.status==='confirmation-required'){window.DOMOSActions.requestUI(request);return}if(o.result.review){id=o.result.review.id;date=o.result.review.startDate;}render(true);notice('Saved.',o.undoId);return o;}catch(e){actionError=e.message;notice(e.message)}finally{busy=false;page.removeAttribute('aria-busy');page.querySelectorAll('button').forEach(b=>b.disabled=false)}}
 function metrics(m){const s=m.summary,currency=s.transactions[0]?.currency||prefs().currency||'GBP',money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(n),tiles=[];
  if(s.tasksCompleted)tiles.push(['Tasks completed',s.tasksCompleted]);if(s.milliseconds)tiles.push(['Work recorded',duration(s.milliseconds)]);if(s.transactions.length)tiles.push(['Spending recorded',money(s.spending)]);if(s.routines.some(r=>r.completed))tiles.push(['Routine steps recorded',s.routines.reduce((n,r)=>n+r.completed,0)]);if(s.events.length)tiles.push(['Events on the calendar',s.events.length]);if(s.goalActivity.length)tiles.push(['Goal activity records',s.goalActivity.length]);
  return `<div class="rv-metrics">${tiles.map(([label,value])=>`<article><small>${esc(label)}</small><strong>${esc(value)}</strong></article>`).join('')}</div>${!s.hasRecordedActivity?'<div class="rv-empty"><h2>A quiet page for this period.</h2><p>No activity was recorded. That does not mean nothing happened.</p></div>':''}${!s.milliseconds?'<p class="rv-muted">No work time recorded.</p>':''}${s.milliseconds?`<details class="rv-card"><summary>Recorded Work Sessions</summary>${m.data.workSessions.filter(w=>(w.segments||[]).some(segment=>Date.parse(segment.start)<Date.parse(m.period.periodEnd)&&Date.parse(segment.end||new Date(services.now()).toISOString())>Date.parse(m.period.periodStart))).map(w=>`<article class="rv-row"><b>${esc(w.title||'Work session')}</b>${w.status==='stopped'?button('Correct time','work-correct',`data-session="${esc(w.id)}"`):'<span>Running or paused · stays intact</span>'}</article>`).join('')}</details>`:''}${s.habits.length?`<section class="rv-card"><h2>Habits</h2>${s.habits.map(h=>`<article class="rv-row"><b>${esc(h.habit.name)}</b><span>${h.quota?`${h.value} / ${h.target} this ${h.habit.schedule.kind==='monthly'?'month':'week'}${h.habit.direction==='atMost'?' · AT MOST target':''}`:h.status?esc(habitStatusLabel(h.habit,h.status)):`${h.periodStatus.value} target met${h.periodStatus.minimumMet?' · '+h.periodStatus.minimumMet+' minimum met':''} · ${h.periodStatus.target} eligible scheduled opportunities`}</span></article>`).join('')}</section>`:''}${s.trackers.length?`<section class="rv-card"><h2>Tracker observations</h2><p class="rv-muted">${kind==='weekly'?'Averages weight each recorded day equally; missing days stay absent.':'Recorded observations, without a success or failure judgement.'}</p>${s.trackers.map(t=>`<article class="rv-row"><b>${esc(t.tracker.name)}</b><span>${esc(trackingValue(t.tracker,t.periodValue))} · ${t.recordedDays} recorded day${t.recordedDays===1?'':'s'}</span></article>`).join('')}</section>`:''}`;
 }
 function aheadHTML(m){if(!m.ahead.length&&m.period.startDate<shiftDay(today(),-1))return '';return `<section class="rv-card" id="rvAhead"><h2>For ${esc(civilLabel(shiftDay(today(),1),{weekday:'long',day:'numeric',month:'long'}))}</h2>${m.ahead.length?m.ahead.map(s=>`<p>${esc(s.text)}</p>`).join(''):'<p>Nothing pressing needs adjusting.</p>'}</section>`}
 function loopHTML(m){const loops=m.summary.loops;return `<section class="rv-card"><h2>${kind==='daily'?'Loose Ends':'Open Loops'}</h2><p class="rv-muted">Only planned or due commitments from this period, plus overdue important deadlines. Nothing moves automatically. Decisions update the current task; ${kind==='weekly'?'Next Week':'Tomorrow'} means ${esc(civilLabel(kind==='weekly'?shiftDay(weekKey(today(),prefs().weekStart??1),7):shiftDay(today(),1)))}.</p>${loops.length?loops.slice(0,limit).map(t=>`<article class="rv-loop"><div><b>${esc(t.title)}</b><small>${t.date?'Planned '+esc(civilLabel(t.date)): 'Unscheduled'}${taskDeadline(t)?' · Deadline '+esc(civilLabel(taskDeadline(t))):''}</small></div><div class="rv-actions">${button(kind==='daily'?'Tomorrow':'Next Week','loop',`data-task="${esc(t.id)}" data-decision="${kind==='daily'?'tomorrow':'nextWeek'}"`)}<label class="rv-date-action">Choose Date<input type="date" aria-label="Reschedule ${esc(t.title)}" data-task-date="${esc(t.id)}"></label>${button('Backlog','loop',`data-task="${esc(t.id)}" data-decision="backlog"`)}${button('Leave For Now','loop',`data-task="${esc(t.id)}" data-decision="leave"`)}${button('Complete','loop',`data-task="${esc(t.id)}" data-decision="complete"`)}</div></article>`).join(''):'<p>No relevant loose ends need a decision.</p>'}${loops.length>limit?button('View More','more'):''}</section>`}
 function checkinHTML(m){return `<section class="rv-card"><h2>Optional Quick Check-In</h2><p>Record what you notice. ${m.period.startDate!==today()?'These measurements will explicitly apply to '+esc(civilLabel(m.period.startDate))+'; the time you record them is also retained.':'Entries apply to today.'}</p>${m.pins.map(t=>`<form data-checkin="${esc(t.id)}"><b>${esc(t.name)}</b><label>${t.type==='yesno'?'<select name="value"><option value="true">Yes</option><option value="false">No</option></select>':t.type==='rating'?`<select name="value">${Array.from({length:(t.max??5)-(t.min??1)+1},(_,i)=>`<option>${i+(t.min??1)}</option>`).join('')}</select>`:t.type==='time'?'<input name="value" type="time" required>':`<input name="value" type="number" step="${t.type==='count'?'1':'any'}" required placeholder="${esc(t.unit|| (t.type==='duration'?'minutes':'Value'))}">`}<span class="sr-only">${esc(t.name)} value</span></label>${m.period.startDate!==today()?'<label class="rv-attribution"><input name="attribute" type="checkbox" required> Applies to this reviewed date</label>':''}<button type="submit">Log ${esc(t.name)}</button></form>`).join('')}<p class="rv-muted">Uses your existing pinned Trackers. Separate logs remain separate observations.</p></section>`}
 function focusHTML(m){return `<section class="rv-card"><h2>Focus & Goals</h2>${m.summary.focusKnown?`<p class="rv-muted">Recorded selections for this period. Current Goal status is shown; older priorities are never reconstructed from today's list.</p>${m.summary.focus.map(f=>`<article class="rv-row"><div><b>${esc(f.name)}</b><small>Selected ${esc(civilLabel(f.week))} · ${esc(f.state)} · Current Goal: ${esc(m.data.goals.find(g=>g.id===f.goalId)?.status||'Status unavailable')}${!f.timezone?' · Original timezone not recorded':''}</small></div>${button('Open','focus-open',`data-kind="${esc(f.kind)}" data-target="${esc(f.targetId)}"`)}</article>`).join('')}`:'<p>No recorded Focus selections are available for this period.</p>'}</section>`}
 const resetDate=m=>weekKey(shiftDay(m.period.startDate,7),prefs().weekStart??1);
 function resetHTML(m){const next=resetDate(m),goals=m.data.goals.filter(g=>!['Completed','Archived','Paused'].includes(g.status)),objectives=m.data.objectives.filter(o=>!['Completed','Archived'].includes(o.status)),payday=window.eval("(()=>{const p=typeof nextPaydayInfo==='function'?nextPaydayInfo():{};return p.date?p.date.getFullYear()+'-'+String(p.date.getMonth()+1).padStart(2,'0')+'-'+String(p.date.getDate()).padStart(2,'0'):''})()"),future=[...m.data.events.filter(e=>e.date>=next&&e.date<shiftDay(next,7)).map(e=>({label:e.title,date:e.date})),...m.data.tasks.filter(t=>taskDeadline(t)>=next&&taskDeadline(t)<shiftDay(next,7)).map(t=>({label:t.title+' · deadline',date:taskDeadline(t)})),...m.data.financeBills.filter(b=>!b.paid&&b.due>=next&&b.due<shiftDay(next,7)).map(b=>({label:b.name+' · unpaid bill',date:b.due}))];
  return `<section class="rv-card"><h2>Optional Next Week Reset</h2><p>Prepare the week of ${esc(civilLabel(next))}. Keep up to three priorities. Nothing carries forward until you choose it.</p>${m.summary.focus.map(f=>`<article class="rv-row"><b>${esc(f.name)}</b><div class="rv-actions">${button('Continue','focus-continue',`data-focus="${esc(f.id)}" data-date="${next}"`)}${button('Complete priority','focus-done',`data-focus="${esc(f.id)}"`)}${button('Remove','focus-remove',`data-focus="${esc(f.id)}"`)}</div></article>`).join('')}<form data-new-focus><label>Select New<select name="target">${goals.map(g=>`<option value="goal|${esc(g.id)}">${esc(g.name)}</option>`).join('')}${objectives.map(o=>`<option value="objective|${esc(o.id)}">Objective · ${esc(o.name)}</option>`).join('')}</select></label><button type="submit" ${!goals.length&&!objectives.length?'disabled':''}>Set Weekly Focus</button></form>${payday&&payday>=next&&payday<shiftDay(next,7)?'<p>Configured payday: '+esc(civilLabel(payday))+'</p>':''}${future.length?'<h3>Recorded upcoming commitments</h3>'+future.slice(0,5).map(x=>`<p>${esc(civilLabel(x.date))} · ${esc(x.label)}</p>`).join(''):''}${button('Not Now','reset-close')}</section>`;
 }
 function historyHTML(){const d=reviewData(services,context),rows=[...d.dailyReviews,...d.weeklyReviews].filter(r=>r.periodKey&&(historyFilter==='all'||r.status===historyFilter)).sort((a,b)=>b.startDate.localeCompare(a.startDate));return `<section class="rv-card"><h2>Reviews</h2><p>Summaries exist even when no review was started. Use the date above to open any day's Summary.</p><label>Show<select data-history-filter><option value="all">All Reviews</option><option value="IN_PROGRESS" ${historyFilter==='IN_PROGRESS'?'selected':''}>In Progress</option><option value="COMPLETED" ${historyFilter==='COMPLETED'?'selected':''}>Completed</option></select></label>${rows.map(r=>`<article class="rv-row"><div><b>${r.kind==='weekly'?'Week of':'Day'} ${esc(civilLabel(r.startDate))}</b><small>${r.status==='COMPLETED'?'Completed':'In Progress'} · ${esc(r.timezone)}</small></div>${button(r.status==='COMPLETED'?'Open / Edit':'Resume','history-open',`data-kind="${esc(r.kind)}" data-id="${esc(r.id)}" data-date="${r.startDate}"`)}</article>`).join('')||'<p>No Reviews started. There is nothing to catch up on.</p>'}</section>`}
 function render(force=false){if(!force&&page.contains(document.activeElement)&&document.activeElement.matches('input,textarea,select'))return;captureDraft();const m=model(),s=m.summary,key=draftKey(m),reflection=drafts.has(key)?drafts.get(key):m.row?.reflection||'';const steps=[['summary',kind==='weekly'?'Your Week':'Your Day'],...(kind==='weekly'?[['focus','Focus & Goals']]:[]),...(s.loops.length?[[ 'loops',kind==='weekly'?'Open Loops':'Loose Ends']]:[]),...(kind==='daily'&&m.pins.length?[['checkin','Check-In']]:[]),['reflection','Reflection']];if(!steps.some(([k])=>k===step))step='summary';
  page.innerHTML=`<header class="rv-header"><div><span class="rv-eyebrow">${mode==='history'?'YOUR RECORDED REVIEWS':kind==='weekly'?'YOUR WEEK, RECONSTRUCTED':'YOUR DAY, RECONSTRUCTED'}</span><h1>${mode==='history'?'Review History':kind==='weekly'?'Weekly Review':mode==='summary'?'Daily Summary':'Daily Review'}</h1><p>${esc(civilLabel(m.period.startDate,{weekday:'long',day:'numeric',month:'long',year:'numeric'}))}${kind==='weekly'?' — '+esc(civilLabel(shiftDay(m.period.endDate,-1))):''} · ${esc(m.period.timezone)}${s.inProgress?' · Period still in progress':''}</p></div><div class="rv-actions">${button('Daily','daily')}${button('Weekly','weekly')}${button('Reviews','history')}<label><span class="sr-only">Review date</span><input type="date" data-review-date value="${date}" max="${today()}"></label></div></header>${mode==='history'?historyHTML():`<div class="rv-status-row"><span>${m.row?.status==='COMPLETED'?'Review completed · facts continue to update':m.row?'Review in progress':'Review is optional. Your Summary is already available.'}</span><div class="rv-actions">${mode==='summary'?button(m.row?'Open Review':'Start Daily Review','start'):button(m.row?.status==='COMPLETED'?'Save Review':'Finish Review','finish','class="rv-primary"')}${m.row?.status==='COMPLETED'?button('Reopen','reopen'):''}</div></div>${mode!=='summary'?`<nav class="rv-steps" aria-label="Review sections">${steps.map(([k,label])=>button(label,'step',`data-step="${k}" aria-current="${step===k?'step':'false'}"`)).join('')}</nav>`:''}${step==='summary'?metrics(m)+(kind==='daily'?aheadHTML(m):focusHTML(m)):step==='loops'?loopHTML(m):step==='checkin'?checkinHTML(m):step==='focus'?focusHTML(m):`<section class="rv-card"><h2>${kind==='weekly'?'What stands out from this week?':'Anything worth remembering from today?'}</h2><p class="rv-muted">Optional. A short thought is enough; leaving this blank is fine.</p><label><span class="sr-only">Review reflection</span><textarea data-reflection data-key="${esc(key)}" maxlength="5000" rows="5" placeholder="Only if something is worth keeping…">${esc(reflection)}</textarea></label><div class="rv-actions">${button('Save reflection','save')}${button(m.row?.status==='COMPLETED'?'Save Review':'Finish Review','finish','class="rv-primary"')}</div></section>`}${mode!=='summary'?'<p class="rv-muted">You can finish from any section. No journaling or catch-up is required.</p>':''}${kind==='weekly'&&m.row?.status==='COMPLETED'&&m.period.endDate>=reviewPeriod('weekly',today(),prefs()).startDate?button('Plan Next Week · Optional','reset-open'):''}${reset?resetHTML(m):''}`}`;
  bind();renderEntries();
 }
 function open(options={}){captureDraft();kind=options.kind||'daily';date=options.date||today();id=options.id||null;mode=options.mode||'summary';step=options.step||'summary';limit=5;reset=false;render(true);window.eval("showPage('reviews')");page.querySelector('h1').setAttribute('tabindex','-1');page.querySelector('h1').focus();}
 function correctWork(sessionId){const m=model(),w=m.data.workSessions.find(s=>s.id===sessionId);if(!w||w.status!=='stopped')return;const local=stamp=>dayInZone(stamp,m.period.timezone)+'T'+clockInZone(stamp,m.period.timezone);correction.innerHTML=`<form><h2>Correct recorded work</h2><p>Update actual intervals in ${esc(m.period.timezone)}. Breaks stay separate and the planned schedule stays unchanged.</p>${w.segments.map((segment,i)=>`<fieldset><legend>Work interval ${i+1}</legend><label>Start<input name="start${i}" type="datetime-local" value="${local(segment.start)}" required></label><label>End<input name="end${i}" type="datetime-local" value="${local(segment.end)}" required></label><details><summary>If the clock repeats this time</summary><label>Start occurrence<select name="startChoice${i}"><option value="">Choose only if needed</option><option value="earlier">Earlier</option><option value="later">Later</option></select></label><label>End occurrence<select name="endChoice${i}"><option value="">Choose only if needed</option><option value="earlier">Earlier</option><option value="later">Later</option></select></label></details></fieldset>`).join('')}<p data-error role="alert"></p><footer><button type="button" data-cancel>Cancel</button><button type="submit">Save correction</button></footer></form>`;correction.querySelector('[data-cancel]').onclick=()=>correction.close();correction.querySelector('form').onsubmit=async e=>{e.preventDefault();const elements=e.target.elements;try{const instant=(name,choice,old)=>elements[name].value===local(old)?old:civilInstant(...elements[name].value.split('T'),m.period.timezone,elements[choice].value),segments=w.segments.map((s,i)=>({start:instant('start'+i,'startChoice'+i,s.start),end:instant('end'+i,'endChoice'+i,s.end)})),o=await act({action:'work.correct',id:sessionId,segments});if(o)correction.close();else correction.querySelector('[data-error]').textContent=actionError||'The correction was not saved.';}catch(error){correction.querySelector('[data-error]').textContent=error.message}};correction.showModal();correction.querySelector('input').focus();}
 function bind(){page.querySelectorAll('[data-review]').forEach(b=>b.onclick=async()=>{const a=b.dataset.review,m=model();captureDraft();if(a==='daily'||a==='weekly')return open({kind:a,mode:a==='weekly'?'review':'summary'});if(a==='work-correct')return correctWork(b.dataset.session);if(a==='history')return open({mode:'history'});if(a==='step'){step=b.dataset.step;render(true);return}if(a==='more'){limit+=5;render(true);return}if(a==='start'){mode='review';await act({action:'review.start'});return}if(a==='finish'){await act({action:'review.complete',reflection:drafts.get(draftKey(m))??m.row?.reflection??''});return}if(a==='save')return act({action:'review.save',reflection:drafts.get(draftKey(m))||''});if(a==='reopen'){mode='review';return act({action:'review.reopen'})}if(a==='loop')return act({action:'review.loop',taskId:b.dataset.task,decision:b.dataset.decision});if(a==='history-open')return open({kind:b.dataset.kind,id:b.dataset.id,date:b.dataset.date,mode:'review'});if(a==='reset-open'||a==='reset-close'){reset=a==='reset-open';render(true);return}if(a==='focus-open'){if(b.dataset.kind==='goal')window.DOMOSGoals.showGoal(b.dataset.target);else{const objective=m.data.objectives.find(o=>o.id===b.dataset.target);if(objective)window.DOMOSGoals.showGoal(objective.goalId,objective.id)}return}if(a.startsWith('focus-'))return act({action:'focus.'+({ 'focus-continue':'continue','focus-done':'done','focus-remove':'remove'}[a]),id:b.dataset.focus,date:b.dataset.date});});
  page.querySelector('[data-review-date]').onchange=e=>{if(e.target.value)open({kind,date:e.target.value,mode:mode==='history'?'summary':mode})};page.querySelector('[data-history-filter]')?.addEventListener('change',e=>{historyFilter=e.target.value;render(true)});
  page.querySelectorAll('[data-task-date]').forEach(input=>input.onchange=()=>input.value&&act({action:'review.loop',taskId:input.dataset.taskDate,decision:'date',targetDate:input.value}));
  page.querySelectorAll('[data-checkin]').forEach(form=>{form.onsubmit=async e=>{e.preventDefault();const stamp=Date.now(),previous=checkinSubmissions.get(form.dataset.checkin),submissionId=previous&&stamp-previous.time<700?previous.id:services.uuid();checkinSubmissions.set(form.dataset.checkin,{id:submissionId,time:stamp});const m=model(),t=m.pins.find(t=>t.id===form.dataset.checkin),value=form.elements.value.value;await act({action:'review.checkin',trackerId:t.id,value:t.type==='yesno'?value==='true':t.type==='time'?value:Number(value),submissionId,attributeToDate:form.elements.attribute?.checked||m.period.startDate===today()});}});
  page.querySelector('[data-new-focus]')?.addEventListener('submit',e=>{e.preventDefault();const [focusKind,targetId]=e.target.elements.target.value.split('|');act({action:'focus.set',kind:focusKind,targetId,date:resetDate(model())})});
 }
 function renderEntries(){let dash=document.getElementById('rvDashboardEntries');if(!dash){dash=document.createElement('div');dash.id='rvDashboardEntries';dash.className='rv-entry-bar';document.querySelector('#page-dashboard .hero')?.append(dash);}if(dash){dash.innerHTML=button("Today's Review",'entry-today')+button("Yesterday's Summary",'entry-yesterday')+button('Weekly Review','entry-week');dash.querySelectorAll('button').forEach(b=>b.onclick=()=>open(b.dataset.review==='entry-week'?{kind:'weekly',mode:'review'}:{date:b.dataset.review==='entry-yesterday'?shiftDay(today(),-1):today(),mode:b.dataset.review==='entry-today'?'review':'summary'}));}
  let history=document.getElementById('rvHistoryEntries');if(!history){history=document.createElement('div');history.id='rvHistoryEntries';history.className='rv-entry-bar';document.querySelector('#page-history .hero')?.append(history);}if(history){history.innerHTML=button('Daily Summary','history-summary')+button('Review this day','history-review')+button('Reviews','history-list');history.querySelectorAll('button').forEach(b=>b.onclick=()=>open({date:document.getElementById('dom62HistoryDate')?.value||today(),mode:b.dataset.review==='history-list'?'history':b.dataset.review==='history-review'?'review':'summary'}));}
 }
 const api={open,render,handleResult(request,result){if(result.summary&&['summary.get','review.open','review.loops','review.list'].includes(request.action))open({kind:result.summary.period.kind,date:result.summary.period.startDate,id:result.review?.id,mode:request.action==='summary.get'?'summary':request.action==='review.list'?'history':'review',step:request.action==='review.loops'?'loops':'summary'});else if(result.review){if(!page.classList.contains('active'))open({kind:result.review.kind,id:result.review.id,date:result.review.startDate,mode:'review'});else{id=result.review.id;kind=result.review.kind;date=result.review.startDate;render(true)}}else if(request.action==='focus.get')open({kind:'weekly',mode:'review',step:'focus'});},search(query){const q=query.trim().toLowerCase();return q?[...services.read(context,'lifeos4.dailyReviews',[]),...services.read(context,'lifeos4.weeklyReviews',[])].filter(r=>r.periodKey&&(r.startDate.includes(q)||(r.reflection||'').toLowerCase().includes(q)|| (r.kind+' review').includes(q))).map(r=>({id:r.id,kind:'review',reviewKind:r.kind,date:r.startDate,title:(r.kind==='weekly'?'Weekly Review · ':'Daily Review · ')+civilLabel(r.startDate),type:r.status==='COMPLETED'?'Completed Review':'In-progress Review'})):[];},get state(){return {kind,date,id,mode,step}}};window.DOMOSReviews=api;
 window.addEventListener('storage',()=>render());window.addEventListener('domos-tracking-changed',()=>render());renderEntries();
 const clock=installDateReconciliation(services,change=>{window.DOMOSTracking?.onDateChange?.();window.eval(`if(${JSON.stringify(change.previousDate)}!==null&&dashSelectedDate===${JSON.stringify(change.previousDate)}){dashSelectedDate=${JSON.stringify(change.date)};dashCalView={year:Number(dashSelectedDate.slice(0,4)),month:Number(dashSelectedDate.slice(5,7))-1}};renderDashboard();renderTasks();renderRoutines();updateLiveClock()`);window.DOMOSHabitTracking?.render?.();window.DOMOSGoals?.renderDashboard?.();renderEntries();if(page.classList.contains('active'))render();});api.clock=clock;return api;
}
