import { JSDOM, VirtualConsole } from 'jsdom';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const errors=[];
const vc=new VirtualConsole();
vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(readFileSync('src/index.html','utf8'),{
  url:'http://localhost/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,
  beforeParse(w){w.structuredClone=structuredClone;w.fetch=async()=>({json:async()=>({current:{temperature_2m:12,weather_code:3}})});w.confirm=()=>true;w.alert=()=>{};w.prompt=()=>null;}
});
const w=dom.window,d=w.document;
w.DOMOSUpdater={getState:()=>({currentVersion:'6.1.2',status:'up-to-date'}),subscribe:()=>()=>{}};
const ui=readFileSync('src/v612-ui.js','utf8').replace(/^import .*;\r?\n/,'').replace('export function initV612','function initV612');
w.eval(`(()=>{${ui}\nwindow.audit={timerAction,readTimer,timerTotals,backupPayload,financeSnapshot,daysToPayday,renderSettings,validateBackup,restoreBackup};initV612();})()`);
const run=code=>w.eval(code);
const field=(id,value)=>{d.getElementById(id).value=value;};
let failed=0,passed=0;
function test(name,fn){try{fn();console.log('PASS '+name);passed++;}catch(e){console.log('FAIL '+name+' — '+e.message);failed++;}}
test('startup has no script errors',()=>assert.deepEqual(errors,[]));
for(const page of ['dashboard','tasks','calendar','routine','finances','goals','notes','settings'])test('navigate '+page,()=>{run(`showPage('${page}')`);assert(d.getElementById('page-'+page).classList.contains('active'));});
test('Work Deadlines includes undated upcoming task',()=>assert(d.getElementById('dom612Deadlines').textContent.includes('Test Work Task')));
test('task create and full render after Settings replacement',()=>{run('newTask()');assert(d.getElementById('drawer').classList.contains('show'));});
test('task save, search, priority and persistence',()=>{const id=run('tasks.at(-1).id');run(`openTask('${id}')`);field('fTitle','Audit <task>');field('fPri','High');run(`saveTask('${id}')`);field('taskSearch','Audit');field('priorityFilter','High');run('renderTasks()');assert(d.getElementById('todayCol').textContent.includes('Audit <task>'));assert(w.localStorage.getItem('lifeos4.tasks').includes('Audit <task>'));field('taskSearch','');field('priorityFilter','');});
test('task duplicate, complete, delete, undo and redo',()=>{const id=run('tasks.at(-1).id');run(`duplicateTask('${id}')`);const dup=run('tasks.at(-1).id');run(`toggleTask('${dup}')`);assert.equal(run(`tasks.find(t=>t.id==='${dup}').status`),'completed');run(`deleteTask('${dup}')`);run('doUndo()');assert(run(`tasks.some(t=>t.id==='${dup}')`));run('doRedo()');assert(!run(`tasks.some(t=>t.id==='${dup}')`));});
test('calendar event create edit delete',()=>{run('newEvent()');const id=run('events.at(-1).id');field('eTitle','Audit event');run(`saveEvent('${id}')`);assert(d.getElementById('monthGrid').textContent.includes('Audit event'));run(`deleteEvent('${id}')`);assert(!run(`events.some(e=>e.id==='${id}')`));});
test('all Settings tabs render',()=>{for(const tab of ['general','appearance','dashboard','shortcuts','data','weather','updates','about']){w.audit.renderSettings(tab);assert(d.getElementById('dom612SettingsPanel').textContent.trim());}});
test('routine create edit pause resume delete',()=>{run('newRoutine()');field('rName','Audit routine');run("selectedRoutineDays=['mon','tue','wed','thu','fri','sat','sun'];addRoutineStep({name:'Audit step',mode:'duration',minutes:20});saveRoutine()");const id=run('routines.at(-1).id');assert(run(`getRoutineOccurrences(localTodayISO()).some(r=>r.id==='${id}')`));run(`toggleRoutine('${id}')`);assert(!run(`getRoutineOccurrences(localTodayISO()).some(r=>r.id==='${id}')`));run(`toggleRoutine('${id}');openRoutine('${id}')`);field('rName','Edited audit routine');run('saveRoutine()');assert(run(`routines.find(r=>r.id==='${id}').name==='Edited audit routine'`));run(`openRoutine('${id}');deleteCurrentRoutine()`);assert(!run(`routines.some(r=>r.id==='${id}')`));run('doUndo();doRedo()');assert(!run(`routines.some(r=>r.id==='${id}')`));});
test('goals create edit complete delete',()=>{run('openGoal()');field('gName','Audit goal');field('gProgress','40');run('saveGoal()');const id=run('goals.at(-1).id');assert(d.getElementById('dom612Goals').textContent.includes('40%'));run(`openGoal('${id}')`);field('gProgress','100');run('saveGoal()');assert.equal(d.getElementById('goalComplete').textContent,'1');run(`openGoal('${id}');deleteGoal()`);});
test('notes save search select delete and escaped preview',()=>{run('newNote()');const id=run('activeNoteId');field('noteTitleInput','Audit note');field('noteBodyInput','<img src=x onerror="bad()">');run(`saveNoteLive('${id}');renderNotes()`);assert.equal(d.querySelectorAll('#notesList img').length,0);field('noteSearch','Audit');run('renderNotes()');assert(d.getElementById('notesList').textContent.includes('Audit note'));run(`selectNote('${id}');deleteNote('${id}')`);});
test('finance account create edit delete',()=>{run('openFinanceAccount()');field('faName','Audit account');field('faBalance','1000');run("saveFinanceAccount('')");const id=run('financeAccounts.at(-1).id');assert.equal(run('financeTotals().total'),1000);run(`openFinanceAccount('${id}')`);field('faBalance','1200');run(`saveFinanceAccount('${id}')`);assert.equal(run('financeTotals().total'),1200);run(`deleteFinanceAccount('${id}')`);});
test('finance budget create and edit',()=>{run('openFinanceBudget()');field('fbCat','Food');field('fbLimit','200');run("saveFinanceBudget('')");assert.equal(run('financeBudgets.at(-1).limit'),200);});
test('finance bill create and savings reserve',()=>{run('openFinanceBill()');field('fblName','Audit bill');field('fblAmount','50');run('saveFinanceBill();openFinanceSaving()');field('fsName','Audit savings');field('fsCurrent','100');field('fsTarget','500');run("saveFinanceSaving('')");assert.equal(run('financeTotals().bills'),50);assert.equal(run('financeTotals().reserved'),100);});
test('finance transaction save filter and transfer exclusion',()=>{run('openTransaction()');field('txDesc','Audit transaction');field('txAmount','25');field('txCategory','Food');run("saveTransaction('');financeTab='transactions';renderFinance()");assert(d.getElementById('financeTxRows').textContent.includes('Audit transaction'));assert.equal(run('financeTotals().spent'),25);});
for(const tab of ['overview','accounts','budget','transactions','bills','savings','insights'])test('finance tab '+tab,()=>run(`financeTab='${tab}';renderFinance()`));
test('finance widget requested button removed',()=>{run("showPage('dashboard')");assert(!d.getElementById('dom612Finance').textContent.includes('Open Finances'));});
test('widget rename persists through enhancement',()=>{run("openRename('finance')");field('renameInput','My money');run('saveRename()');assert(d.querySelector('[data-id="finance"] h3').textContent.includes('My money'));});
test('widget hide restore and layout edit',()=>{run("hideWidget('goals')");assert(!d.querySelector('#dashGrid [data-id="goals"]'));run("restoreWidget('goals');toggleEdit(true)");assert(d.body.classList.contains('edit'));run('toggleEdit(false)');});
test('timer start pause stop reset',()=>{w.audit.timerAction('start');assert(w.audit.readTimer().running);w.audit.timerAction('pause');assert(!w.audit.readTimer().running);w.audit.timerAction('stop');assert.equal(w.audit.readTimer().sessionMs,0);w.audit.timerAction('reset');assert.equal(w.audit.readTimer().elapsedMs,0);});
test('backup contains current app data only',()=>{w.localStorage.setItem('unrelated','private');const p=w.audit.backupPayload();assert.equal(p.format,'DOM.OS Backup');assert(p.data['lifeos4.tasks']);assert(!('unrelated' in p.data));});
test('DOM contains no duplicate IDs',()=>{const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);});
test('appearance and general preference controls persist',()=>{w.audit.renderSettings('appearance');d.querySelector('[data-accent="#479cff"]').click();assert.equal(d.documentElement.style.getPropertyValue('--g'),'#479cff');d.querySelector('[data-density="compact"]').click();assert.equal(d.body.dataset.sidebarDensity,'compact');w.audit.renderSettings('general');const c=d.querySelector('[data-setting-toggle="reduceMotion"]');c.checked=true;c.dispatchEvent(new w.Event('change'));assert(d.body.classList.contains('dom612-no-animations'));});
test('shortcut editing and reset',()=>{w.audit.renderSettings('shortcuts');d.querySelector('[data-key="newTask"]').click();d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'y',ctrlKey:true,bubbles:true}));assert.equal(run('keys.newTask'),'Ctrl+Y');d.getElementById('resetKeys').click();assert.equal(run('keys.newTask'),'Ctrl+T');});
test('Escape closes goal and routine editors',()=>{run('openGoal();newRoutine()');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!d.getElementById('goalModal').classList.contains('show'));assert(!d.getElementById('routineModal').classList.contains('show'));});
test('task drag to completed updates persisted status',()=>{run('renderTasks()');const card=d.querySelector('#upcomingCol .taskcard');const id=card.dataset.task;const ev={preventDefault(){},dataTransfer:{getData:()=>id}};d.getElementById('completedCol').ondrop(ev);assert.equal(run(`tasks.find(t=>t.id==='${id}').status`),'completed');});
test('schedule navigation and calendar opening retain selected month',()=>{run("dashSelectedDate='2026-11-15';store.set('dashSelectedDate',dashSelectedDate);renderDashboard()");d.querySelector('[data-open-calendar]').click();assert(d.getElementById('calTitle').textContent.includes('November'));});
test('quick note autosaves plain text',()=>{const q=d.getElementById('quickNote');q.value='Audit quick note';q.dispatchEvent(new w.Event('input'));assert.equal(JSON.parse(w.localStorage.getItem('lifeos4.quickNote')),'Audit quick note');});
test('finance payday calculations agree',()=>assert.equal(run('financeDaysToPayday()'),w.audit.daysToPayday()));
test('calendar template create edit delete',()=>{run('newCalendarTemplate()');const id=run('calendarTemplates.at(-1).id');field('ctTitle','Audit template');field('ctDur','45');run(`saveCalendarTemplate('${id}');openCalendarTemplate('${id}')`);assert.equal(d.getElementById('ctTitle').value,'Audit template');run(`deleteCalendarTemplate('${id}')`);assert(!run(`calendarTemplates.some(t=>t.id==='${id}')`));});
test('notes list refreshes during typing',()=>{run('newNote()');const id=run('activeNoteId');field('noteTitleInput','Live title');run(`saveNoteLive('${id}')`);assert(d.querySelector('.note-row.active').textContent.includes('Live title'));});
test('text undo does not trigger application undo',()=>{const before=run('undo.length');d.getElementById('noteTitleInput').dispatchEvent(new w.KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true}));assert.equal(run('undo.length'),before);});
test('completed work is excluded from deadlines',()=>{run('renderDashboard()');assert(!d.getElementById('dom612Deadlines').textContent.includes('Test Work Task'));});
test('calendar and schedule preserve literal task titles',()=>{run("showPage('calendar');viewDate=new Date();renderCalendar();dashSelectedDate=localTodayISO();renderDashSchedule()");assert(d.getElementById('monthGrid').textContent.includes('Audit <task>'));assert(d.getElementById('dashSchedule').textContent.includes('Audit <task>'));});
async function asyncTest(name,fn){try{await fn();console.log('PASS '+name);passed++;}catch(e){console.log('FAIL '+name+' — '+e.message);failed++;}}
await asyncTest('Today completion persists and updates progress',async()=>{run('renderDashboard()');const button=d.querySelector('.routine-check');button.click();await new Promise(r=>setTimeout(r,260));assert(Object.values(JSON.parse(w.localStorage.getItem('lifeos4.routineChecks'))).includes(true));assert(!d.querySelector('.dom612-today-progress').textContent.includes('0 of'));});
await asyncTest('backup import rejects malformed collections before writes',async()=>{w.audit.renderSettings('data');let alerts=[];w.alert=x=>alerts.push(x);const input=d.querySelector('[data-import]');const file=new w.File([JSON.stringify({format:'DOM.OS Backup',version:1,data:{'lifeos4.tasks':'{}'}})],'invalid.json',{type:'application/json'});Object.defineProperty(input,'files',{value:[file]});const before=w.localStorage.getItem('lifeos4.tasks');input.onchange({target:input});await new Promise(r=>setTimeout(r,30));assert(alerts.length);assert.equal(w.localStorage.getItem('lifeos4.tasks'),before);});
await asyncTest('cross-window task updates refresh board',async()=>{const tasks=JSON.parse(w.localStorage.getItem('lifeos4.tasks'));tasks.push({id:'cross-window',title:'Synced task',status:'upcoming',priority:'Medium',date:''});w.localStorage.setItem('lifeos4.tasks',JSON.stringify(tasks));w.dispatchEvent(new w.StorageEvent('storage',{key:'lifeos4.tasks'}));await new Promise(r=>setTimeout(r,130));assert(d.getElementById('upcomingCol').textContent.includes('Synced task'));});
test('cancelled task event and template drafts are not saved',()=>{
 for(const [create,key] of [['newTask','tasks'],['newEvent','events'],['newCalendarTemplate','calendarTemplates']]){const before=w.localStorage.getItem('lifeos4.'+key);run(create+'()');run('persist();closeDrawer()');assert.equal(w.localStorage.getItem('lifeos4.'+key),before);}
});
test('undo of a new task removes it without restoring a placeholder',()=>{run('newTask()');const id=run('tasks.at(-1).id');field('fTitle','Draft regression');run(`saveTask('${id}');doUndo()`);assert(!run(`tasks.some(t=>t.id==='${id}')`));});
test('invalid task and finance values leave saved data unchanged',()=>{run('newTask()');field('fTitle','');const before=w.localStorage.getItem('lifeos4.tasks');run('saveTask(tasks.at(-1).id)');assert.equal(w.localStorage.getItem('lifeos4.tasks'),before);run('closeDrawer();openFinanceBudget()');field('fbCat','Invalid');field('fbLimit','-1');const budgets=w.localStorage.getItem('lifeos4.financeBudgets');run("saveFinanceBudget('');closeDrawer()");assert.equal(w.localStorage.getItem('lifeos4.financeBudgets'),budgets);});
test('finance transaction edit delete controls work',()=>{const id=run('transactions.at(-1).id');run("financeTab='transactions';renderFinance()");assert(d.getElementById('financeTxRows').textContent.includes('Edit'));run(`openTransaction('${id}')`);field('txAmount','30');run(`saveTransaction('${id}')`);assert.equal(run(`transactions.find(t=>t.id==='${id}').amount`),30);run(`deleteFinanceRecord('transactions','${id}')`);assert(!run(`transactions.some(t=>t.id==='${id}')`));});
test('finance bill edit paid unpaid delete controls work',()=>{const id=run('financeBills.at(-1).id');run(`openFinanceBill('${id}')`);field('fblAmount','75');run(`saveFinanceBill('${id}')`);assert.equal(run('financeTotals().bills'),75);run(`toggleFinanceBill('${id}')`);assert.equal(run('financeTotals().bills'),0);run(`toggleFinanceBill('${id}')`);assert.equal(run('financeTotals().bills'),75);run(`deleteFinanceRecord('financeBills','${id}')`);assert.equal(run('financeTotals().bills'),0);});
test('budgets and savings can be deleted',()=>{for(const kind of ['financeBudgets','financeSavings']){const id=run(kind+'.at(-1).id');run(`deleteFinanceRecord('${kind}','${id}')`);assert(!run(`${kind}.some(t=>t.id==='${id}')`));}});
test('pay cycle includes payday excludes next payday and clamps February',()=>{run("store.set('paydayDay',31)");const p=run('payCycleRange(new Date(2026,2,1))');assert.equal(p.start,'2026-02-28');assert.equal(p.end,'2026-03-31');const on=run('payCycleRange(new Date(2026,2,31))');assert.equal(on.start,'2026-03-31');assert.equal(on.end,'2026-04-30');run("store.set('paydayDay',28)");});
test('running timer retains time after midnight',()=>{const midnight=new Date();midnight.setHours(0,0,0,0);w.localStorage.setItem('domos612.workTimer',JSON.stringify({day:'2000-01-01',running:true,startedAt:midnight.getTime()-3600000,elapsedMs:1234,sessionMs:1234,sessionCount:2}));const t=w.audit.readTimer();assert(t.running);assert.equal(t.startedAt,midnight.getTime());assert.equal(t.elapsedMs,0);assert(w.audit.timerTotals(t).total>=0);w.audit.timerAction('reset');});
test('stale saves merge independent remote task edits',()=>{run("tasks=store.get('tasks',[])");const remote=JSON.parse(w.localStorage.getItem('lifeos4.tasks'));remote.push({id:'remote-new',title:'Remote addition',status:'upcoming',date:''});w.localStorage.setItem('lifeos4.tasks',JSON.stringify(remote));run("tasks.push({id:'local-new',title:'Local addition',status:'upcoming',date:''});persist()");const saved=JSON.parse(w.localStorage.getItem('lifeos4.tasks'));assert(saved.some(t=>t.id==='remote-new'));assert(saved.some(t=>t.id==='local-new'));});
test('conflicting task edits preserve the remote saved value',()=>{run("tasks=store.get('tasks',[])");const remote=JSON.parse(w.localStorage.getItem('lifeos4.tasks'));remote.find(t=>t.id==='remote-new').title='Remote rename';w.localStorage.setItem('lifeos4.tasks',JSON.stringify(remote));assert.throws(()=>run("tasks.find(t=>t.id==='remote-new').title='Local rename';persist()"),/another window/);assert.equal(JSON.parse(w.localStorage.getItem('lifeos4.tasks')).find(t=>t.id==='remote-new').title,'Remote rename');run("tasks=store.get('tasks',[])");});
test('backup validation rejects unsafe IDs and duplicate IDs',()=>{for(const records of [[{id:"bad' onclick='x"}],[{id:'duplicate'},{id:'duplicate'}]])assert.throws(()=>w.audit.validateBackup({format:'DOM.OS Backup',version:1,data:{'lifeos4.tasks':JSON.stringify(records)}}),/record ID/);});
test('backup round trip restores supported data',()=>{const p=w.audit.backupPayload();w.audit.validateBackup(p);w.localStorage.setItem('lifeos4.quickNote','"changed"');w.audit.restoreBackup(p.data);assert.equal(w.localStorage.getItem('lifeos4.quickNote'),p.data['lifeos4.quickNote']);});
test('backup quota failure rolls back earlier writes',()=>{const proto=Object.getPrototypeOf(w.localStorage),set=proto.setItem;const before=w.localStorage.getItem('lifeos4.quickNote');proto.setItem=function(k,v){if(k==='lifeos4.fail')throw new Error('Quota exceeded');return set.call(this,k,v)};try{assert.throws(()=>w.audit.restoreBackup({'lifeos4.quickNote':'"new"','lifeos4.fail':'[]'}),/Quota/);assert.equal(w.localStorage.getItem('lifeos4.quickNote'),before);}finally{proto.setItem=set;}});
test('updater states show inline progress only while busy',()=>{const get=w.DOMOSUpdater.getState;try{for(const status of ['up-to-date','checking','available','downloading','installing','installed','error']){w.DOMOSUpdater.getState=()=>({currentVersion:'6.1.2',latestVersion:'6.1.3',status,available:['available','downloading','installing','installed'].includes(status),progress:42});w.audit.renderSettings('updates');const panel=d.getElementById('dom612SettingsPanel');assert.equal(!!panel.querySelector('[data-update-install]'),status==='available');assert.equal(!!panel.querySelector('.dom612-inline-update-progress'),['downloading','installing'].includes(status));assert(!panel.textContent.includes('Download Progress'));}}finally{w.DOMOSUpdater.getState=get;}});
await asyncTest('weather failure reports unavailable after request completes',async()=>{w.fetch=async()=>{throw new Error('offline')};w.audit.renderSettings('weather');await d.querySelector('[data-refresh-weather]').onclick();assert(d.getElementById('toast').textContent.includes('Weather unavailable'));});
await asyncTest('cross-window notes and dashboard names refresh',async()=>{run('closeDrawer();closeRoutineBuilder();closeRename()');w.localStorage.setItem('lifeos4.notes',JSON.stringify([{id:'remote-note',title:'Remote note',body:'From another window'}]));const dashboard=JSON.parse(w.localStorage.getItem('lifeos4.dashboard'));dashboard.names.finance='Shared money';w.localStorage.setItem('lifeos4.dashboard',JSON.stringify(dashboard));w.dispatchEvent(new w.StorageEvent('storage',{key:'lifeos4.notes'}));await new Promise(r=>setTimeout(r,140));assert.equal(run('notes[0].title'),'Remote note');assert(d.querySelector('[data-id="finance"] h3').textContent.includes('Shared money'));});
await asyncTest('cross-window refresh waits until the editor closes',async()=>{run("openTask('local-new')");const records=JSON.parse(w.localStorage.getItem('lifeos4.tasks'));records.push({id:'deferred-new',title:'Deferred task',status:'upcoming',date:''});w.localStorage.setItem('lifeos4.tasks',JSON.stringify(records));w.dispatchEvent(new w.StorageEvent('storage',{key:'lifeos4.tasks'}));await new Promise(r=>setTimeout(r,140));assert(!run("tasks.some(t=>t.id==='deferred-new')"));run('closeDrawer()');await new Promise(r=>setTimeout(r,140));assert(run("tasks.some(t=>t.id==='deferred-new')"));});
test('collection quota failure rolls back multi-key persistence',()=>{run('tasks=store.get("tasks",[]);dash=store.get("dashboard",dash)');const proto=Object.getPrototypeOf(w.localStorage),set=proto.setItem,before=w.localStorage.getItem('lifeos4.tasks');proto.setItem=function(k,v){if(k==='lifeos4.dashboard')throw new Error('Quota exceeded');return set.call(this,k,v)};try{assert.throws(()=>run("tasks.push({id:'quota-task',title:'Must roll back'});dash.names.finance='Quota change';persist()"),/Quota/);assert.equal(w.localStorage.getItem('lifeos4.tasks'),before);}finally{proto.setItem=set;run('tasks=store.get("tasks",[]);dash=store.get("dashboard",dash)');}});
console.log(`RESULT ${passed} passed; ${failed} failed`);
dom.window.close();process.exitCode=failed?1:0;
