use serde_json::Value;
use std::collections::{HashMap,HashSet};

const MAX:i64=9_000_000_000_000;
pub fn bill_source(s:&Value,id:&str)->bool {
 let Some(rules)=s["rules"].as_array() else{return false};let Some(r)=rules.iter().find(|r|r["kind"]=="expense"&&r["archived"]!=true&&r["reminder"]!=false&&id.starts_with(&format!("{}:",r["id"].as_str().unwrap_or("")))) else{return false};
 let nominal=&id[r["id"].as_str().unwrap_or("").len()+1..];if day(&Value::String(nominal.into())).is_err(){return false}
 let o=s["occurrences"].as_array().and_then(|rows|rows.iter().find(|o|o["id"]==id));if o.map(|o|o["status"]=="skipped"||o["status"]=="cancelled").unwrap_or(false){return false}
 let terms=r["amountHistory"].as_array().and_then(|rows|rows.iter().rev().find(|v|v["effectiveFrom"].as_str().map(|d|d<=nominal).unwrap_or(false)));let amount=o.or(terms).unwrap_or(r)["amountMinor"].as_i64().unwrap_or(0);let paid=s["transactions"].as_array().map(|rows|rows.iter().filter(|t|t["occurrenceId"]==id&&t["voided"]!=true).map(|t|t["amountMinor"].as_i64().unwrap_or(0)).sum::<i64>()).unwrap_or(0);amount>paid
}
fn minor(v:&Value)->Result<i64,String>{let n=v.as_i64().ok_or("Finance amounts must be integer pennies")?;if n.unsigned_abs()>MAX as u64{return Err("Finance amount outside safe range".into())}Ok(n)}
fn timestamp(v:&Value)->Result<(),String>{let s=v.as_str().ok_or("Finance timestamp missing")?;let b=s.as_bytes();if ![20,24].contains(&b.len())||b[10]!=b'T'||b[13]!=b':'||b[16]!=b':'||b[b.len()-1]!=b'Z'||b.len()==24&&(b[19]!=b'.'||!b[20..23].iter().all(u8::is_ascii_digit)){return Err("Invalid UTC Finance timestamp".into())}day(&Value::String(s[..10].into()))?;for (start,max) in [(11,23),(14,59),(17,59)]{let n:u32=s[start..start+2].parse().map_err(|_|"Invalid Finance clock")?;if n>max{return Err("Invalid Finance clock".into())}}Ok(())}
fn day(v:&Value)->Result<&str,String>{let s=v.as_str().ok_or("Finance date missing")?;let b=s.as_bytes();if b.len()!=10||b[4]!=b'-'||b[7]!=b'-'||!b.iter().enumerate().all(|(i,c)|i==4||i==7||c.is_ascii_digit()){return Err("Invalid Finance civil date".into())}let year:u32=s[..4].parse().map_err(|_|"Invalid year")?;let month:usize=s[5..7].parse().map_err(|_|"Invalid month")?;let d:u32=s[8..].parse().map_err(|_|"Invalid day")?;let leap=year%4==0&&(year%100!=0||year%400==0);let lengths=[31,if leap{29}else{28},31,30,31,30,31,31,30,31,30,31];if !(1..=12).contains(&month)||d<1||d>lengths[month-1]{return Err("Invalid Finance date".into())}Ok(s)}
pub fn validate(s:&Value,profile:&str)->Result<(),String>{
 if s["version"]!=1||s["profileId"]!=profile||s["currency"]!="GBP"{return Err("Unsupported or foreign Finance document".into())}day(&s["cutoverDate"])?;if s["revision"].as_u64().map(|r|r>9_007_199_254_740_991).unwrap_or(true){return Err("Invalid Finance revision".into())}
 for key in ["budgets","savings","bills","quarantine"]{if !s["legacy"][key].is_array(){return Err("Finance legacy preservation data missing".into())}}
 let mut groups=HashMap::new();
 for key in ["accounts","transactions","rules","occurrences","allocations","checks","operations"]{let rows=s[key].as_array().ok_or("Finance collection missing")?;let mut ids=HashSet::new();for r in rows{let id=r["id"].as_str().ok_or("Finance ID missing")?;if id.is_empty()||!id.bytes().all(|c|c.is_ascii_alphanumeric()||b"_.:-".contains(&c))||!ids.insert(id)||r["profileId"]!=profile{return Err("Duplicate or foreign Finance identity".into())}}groups.insert(key,rows);}
 let accounts:HashMap<&str,&Value>=groups["accounts"].iter().map(|a|(a["id"].as_str().unwrap(),a)).collect();let mut balances=HashMap::new();
 for (id,a) in &accounts{if a["currency"]!="GBP"||!a["supported"].is_boolean()||!a["archived"].is_boolean(){return Err("Unsupported account currency or lifecycle".into())}day(&a["openingDate"])?;if !a["verifiedAt"].is_null(){timestamp(&a["verifiedAt"])?;}balances.insert(*id,minor(&a["openingMinor"])?);}
 let rules:HashMap<&str,&Value>=groups["rules"].iter().map(|a|(a["id"].as_str().unwrap(),a)).collect();let occurrences:HashMap<&str,&Value>=groups["occurrences"].iter().map(|a|(a["id"].as_str().unwrap(),a)).collect();let mut paid:HashMap<&str,i64>=HashMap::new();
 for r in groups["rules"]{if r["currency"]!="GBP"||!r["day"].is_null()&&r["day"].as_u64().map(|d|!(1..=31).contains(&d)).unwrap_or(true)||!["none","preceding-friday"].contains(&r["weekend"].as_str().unwrap_or("")){return Err("Invalid recurrence currency or policy".into())}day(&r["anchor"])?;if minor(&r["amountMinor"])?<0||!accounts.contains_key(r["accountId"].as_str().unwrap_or(""))||!["income","expense"].contains(&r["kind"].as_str().unwrap_or(""))||!["once","weekly","four-weekly","monthly","quarterly","annually"].contains(&r["frequency"].as_str().unwrap_or("")){return Err("Invalid Finance schedule".into())}}
 for r in groups["rules"]{if !r["legacySourceId"].is_null()&&!r["legacySourceId"].is_string(){return Err("Invalid legacy conversion source".into())}if let Some(source)=r["legacySourceId"].as_str(){if !s["legacy"]["bills"].as_array().unwrap().iter().any(|b|b["id"]==source&&b["ruleId"]==r["id"])||groups["rules"].iter().any(|other|other["id"]!=r["id"]&&other["legacySourceId"]==source){return Err("Invalid duplicate legacy conversion".into())}}if r.get("amountHistory").is_some(){let revisions=r["amountHistory"].as_array().ok_or("Invalid rule amount history")?;if revisions.is_empty(){return Err("Empty rule amount history".into())}let mut previous="";for v in revisions{let from=day(&v["effectiveFrom"])?;if from<=previous||minor(&v["amountMinor"])?<0{return Err("Invalid rule amount history order".into())}if v.get("estimate").is_some()&&!v["estimate"].is_boolean()||v.get("category").is_some()&&!v["category"].is_string(){return Err("Invalid rule terms".into())}previous=from;}}}
 for o in groups["occurrences"]{if o["currency"]!="GBP"{return Err("Invalid occurrence currency".into())}day(&o["date"])?;let nominal=day(&o["nominalDate"])?;let rule_id=o["ruleId"].as_str().unwrap_or("");let r=rules.get(rule_id).ok_or("Occurrence rule missing")?;if minor(&o["amountMinor"])?<0||!accounts.contains_key(o["accountId"].as_str().unwrap_or(""))||o["kind"]!=r["kind"]||o["accountId"]!=r["accountId"]||o["id"]!=format!("{rule_id}:{nominal}"){return Err("Invalid Finance occurrence".into())}}
 for t in groups["transactions"]{
  for field in ["description","category","notes"]{if t.get(field).is_some()&&t[field].as_str().map(|v|v.encode_utf16().count()>5000).unwrap_or(true){return Err("Invalid transaction details".into())}}
  timestamp(&t["createdAt"])?;if t.get("voided").is_some()&&!t["voided"].is_boolean(){return Err("Invalid reversal lifecycle".into())}
  let amount=minor(&t["amountMinor"])?;let effective=day(&t["effectiveDate"])?;let kind=t["type"].as_str().unwrap_or("");if !t["posted"].is_boolean()||t["posted"]==false&&t["historical"]!=true||!t["createdAt"].is_string()||t["currency"]!="GBP"||!["income","expense","adjustment","transfer"].contains(&kind)||kind!="adjustment"&&amount<=0{return Err("Invalid Finance transaction".into())}
  let id=t["accountId"].as_str().unwrap_or("");let posted=t["posted"]==true;let active=t["voided"]!=true;
  if posted {let a=accounts.get(id).ok_or("Posting account missing")?;if a["supported"]!=true||effective<day(&a["openingDate"])?{return Err("Posting crosses opening cutover".into())}}
  if kind=="transfer"{let to=t["toAccountId"].as_str().unwrap_or("");let a=accounts.get(to).ok_or("Transfer destination missing")?;if to==id||a["supported"]!=true||posted&&effective<day(&a["openingDate"])?{return Err("Invalid transfer".into())}if posted&&active{let next=balances[to].checked_add(amount).ok_or("Balance overflow")?;if next.unsigned_abs()>MAX as u64{return Err("Unsafe account balance".into())}balances.insert(to,next);}}
  if posted&&active{let delta=if kind=="expense"||kind=="transfer"{-amount}else{amount};let next=balances[id].checked_add(delta).ok_or("Balance overflow")?;if next.unsigned_abs()>MAX as u64{return Err("Unsafe account balance".into())}balances.insert(id,next);}
  if let Some(oid)=t["occurrenceId"].as_str(){let o=occurrences.get(oid).ok_or("Payment occurrence missing")?;if !t["internalTransfer"].is_null()&&t["internalTransfer"]!=false||o["kind"]!=t["type"]||accounts.get(id).map(|a|a["supported"]!=true).unwrap_or(true){return Err("Invalid settlement relationship".into())}if active{let n=paid.get(oid).unwrap_or(&0).checked_add(amount).ok_or("Settlement overflow")?;paid.insert(oid,n);}}
 }
 if balances.values().any(|v|v.unsigned_abs()>MAX as u64){return Err("Unsafe account balance".into())}
 for (id,n) in paid{if n>minor(&occurrences[id]["amountMinor"])?{return Err("Overallocated bill payment".into())}}
 for a in groups["allocations"]{if a["currency"]!="GBP"{return Err("Invalid allocation currency".into())}if minor(&a["amountMinor"])?<0||!accounts.contains_key(a["accountId"].as_str().unwrap_or("")){return Err("Invalid protected allocation".into())}if a["kind"]=="bill"{let r=rules.get(a["ruleId"].as_str().unwrap_or("")).ok_or("Reserve obligation missing")?;if r["kind"]!="expense"||r["accountId"]!=a["accountId"]{return Err("Invalid reserve relationship".into())}}}
 for c in groups["checks"]{if c["currency"]!="GBP"{return Err("Invalid observation currency".into())}timestamp(&c["observedAt"])?;for key in ["observedMinor","recordedMinor","differenceMinor"]{minor(&c[key])?;}if c["differenceMinor"].as_i64()!=c["observedMinor"].as_i64().zip(c["recordedMinor"].as_i64()).map(|(a,b)|a-b)||!accounts.contains_key(c["accountId"].as_str().unwrap_or(""))||!["booked","available"].contains(&c["basis"].as_str().unwrap_or("")){return Err("Invalid balance observation".into())}}
 let mut reserves=HashSet::new();for a in groups["allocations"]{if !["independent","essentials","buffer","bill"].contains(&a["kind"].as_str().unwrap_or("")){return Err("Invalid allocation purpose".into())}if a.get("settlementBaselineMinor").is_some(){minor(&a["settlementBaselineMinor"])?;}if a["kind"]=="bill"&&!reserves.insert(a["ruleId"].as_str().unwrap_or("")){return Err("Duplicate linked reserve".into())}if !a["startDate"].is_null(){day(&a["startDate"])?;}if !a["endDate"].is_null(){day(&a["endDate"])?;}}
 for a in groups["allocations"]{if a["kind"]=="essentials"{let start=day(&a["startDate"])?;let end=day(&a["endDate"])?;if end<start||groups["allocations"].iter().any(|b|b["id"]!=a["id"]&&b["kind"]=="essentials"&&b["accountId"]==a["accountId"]&&b["category"]==a["category"]&&b["startDate"].as_str().map(|d|d<=end).unwrap_or(false)&&b["endDate"].as_str().map(|d|d>=start).unwrap_or(false)){return Err("Essentials allowances cannot overlap".into())}}}
 for key in ["primaryAccountId","spendingAccountId"]{if let Some(id)=s["settings"][key].as_str(){if !id.is_empty()&&accounts.get(id).map(|a|a["supported"]!=true).unwrap_or(true){return Err("Planning account missing or unsupported".into())}}}
 for b in s["legacy"]["budgets"].as_array().unwrap(){if b["needsReview"]!=true||b.get("limitMinor").is_some(){minor(&b["limitMinor"])?;}}for g in s["legacy"]["savings"].as_array().unwrap(){for key in ["savedMinor","targetMinor"]{if g["needsReview"]!=true||g.get(key).is_some(){minor(&g[key])?;}}}
 if !s["settings"]["budgetDay"].is_null(){let d=s["settings"]["budgetDay"].as_u64().ok_or("Invalid budget cycle day")?;if !(1..=31).contains(&d){return Err("Invalid budget cycle day".into())}}
 let horizon=s["settings"]["horizon"].as_u64().ok_or("Planning horizon missing")?;if !(1..=366).contains(&horizon){return Err("Invalid planning horizon".into())}Ok(())
}

#[cfg(test)]mod tests{
 use super::*;use serde_json::json;
 #[test]fn bill_sources_use_effective_dated_amounts(){let s=json!({"rules":[{"id":"r","kind":"expense","amountMinor":0,"amountHistory":[{"effectiveFrom":"2024-10-01","amountMinor":10000},{"effectiveFrom":"2026-10-09","amountMinor":0}]}],"occurrences":[],"transactions":[]});assert!(bill_source(&s,"r:2024-10-01"));assert!(!bill_source(&s,"r:2026-11-01"));}
 #[test]fn canonical_bill_sources_track_partial_settlement_cancellation_and_reversal(){let id="r:2026-10-10";let mut s=json!({"rules":[{"id":"r","kind":"expense","amountMinor":10000}],"occurrences":[],"transactions":[]});assert!(bill_source(&s,id));assert!(!bill_source(&s,"r:not-a-date"));s["transactions"]=json!([{"occurrenceId":id,"amountMinor":4000}]);assert!(bill_source(&s,id));s["transactions"][0]["amountMinor"]=json!(10000);assert!(!bill_source(&s,id));s["transactions"][0]["voided"]=json!(true);assert!(bill_source(&s,id));s["occurrences"]=json!([{"id":id,"status":"skipped"}]);assert!(!bill_source(&s,id));}
}
