// Instants stay UTC/offset ISO timestamps. Date-only plans are civil dates, never instants.
export const localZone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
export function profileZone(preferences={}){return preferences.timeZone||localZone()}
export function dayInZone(timestamp=Date.now(),zone){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(timestamp));return ['year','month','day'].map(k=>parts.find(p=>p.type===k).value).join('-')}
export function clockInZone(timestamp,zone,format='24h'){return new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:format==='12h'?'h12':'h23'}).format(new Date(timestamp))}
export function shiftDay(day,offset){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)}
export function civilLabel(day,options={weekday:'short',day:'numeric',month:'short'}){return new Intl.DateTimeFormat('en-GB',{...options,timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'))}
export function civilClock(time,format='24h'){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time||''))return '';if(format!=='12h')return time;const [hour,minute]=time.split(':');return `${Number(hour)%12||12}:${minute} ${Number(hour)<12?'am':'pm'}`}
export function zoneOffset(timestamp,zone){return new Intl.DateTimeFormat('en-GB',{timeZone:zone,timeZoneName:'shortOffset'}).formatToParts(new Date(timestamp)).find(x=>x.type==='timeZoneName').value}
export function midnightInZone(day,zone){let low=Date.parse(day+'T00:00:00Z')-36*3600000,high=low+72*3600000;while(high-low>1){const mid=Math.floor((low+high)/2);if(dayInZone(mid,zone)<day)low=mid;else high=mid}return high}
const boundsCache=new Map();
export function dayBounds(day,zone){zone=zone||localZone();const key=zone+'|'+day;if(!boundsCache.has(key)){if(boundsCache.size>1000)boundsCache.clear();boundsCache.set(key,{start:midnightInZone(day,zone),end:midnightInZone(shiftDay(day,1),zone)})}return boundsCache.get(key)}
export function installProfileClock(profile,now=()=>Date.now()) {return {zone:()=>profileZone(profile.preferences),today:()=>dayInZone(now(),profileZone(profile.preferences)),dayAt:timestamp=>dayInZone(timestamp,profileZone(profile.preferences)),clock:timestamp=>clockInZone(timestamp??now(),profileZone(profile.preferences),profile.preferences?.timeFormat),dateLabel:civilLabel,civilClock:time=>civilClock(time,profile.preferences?.timeFormat),timestampLabel:timestamp=>new Intl.DateTimeFormat('en-GB',{timeZone:profileZone(profile.preferences),dateStyle:'medium',timeStyle:'short',hourCycle:profile.preferences?.timeFormat==='12h'?'h12':'h23'}).format(new Date(timestamp))}}

// A user-entered wall time may be missing or repeated during DST. Never guess a fold.
export function civilInstant(day,time,zone,choice='') {if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||shiftDay(day,0)!==day||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw Error('Choose a valid local date and time.');const {start,end}=dayBounds(day,zone),matches=[],formatter=new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'});for(let n=start;n<end;n+=60000)if(formatter.format(n)===time)matches.push(n);if(!matches.length)throw Error('This local time does not exist because the clocks change.');if(matches.length>1&&!['earlier','later'].includes(choice))throw Error('This time occurs twice. Choose the earlier or later occurrence.');return new Date(choice==='later'?matches.at(-1):matches[0]).toISOString();}
