import {dayInZone,profileZone,shiftDay} from './date-time.js';

// A single, versioned profile document is committed atomically by SQLite. Legacy
// collections remain an immutable migration source, never an alternate ledger.
export const FINANCE_KEY='lifeos4.financeDomain';
export const FINANCE_COLLECTIONS=['transactions','financeAccounts','financeBudgets','financeBills','financeSavings'];
const COMMAND_FIELDS=new Set(['action','operationId','id','amount','accountId','toAccountId','type','date','description','category','notes','name','bank','currency','source','externalReference','reason','basis','anchor','frequency','day','weekend','estimate','reminder','kind','legacyId','status','transactionId','ruleId','startDate','endDate','target','horizon','budgetDay','primaryAccountId','spendingAccountId','billsReviewed','collection','mode','expectedFinanceRevision','effectiveDate']);
const MAX=9000000000000;
export function minor(value,{signed=false,zero=false}={}){
 const raw=typeof value==='number'?String(value):value;
 if(typeof raw!=='string'||!new RegExp(signed?'^-?\\d+(?:\\.\\d{1,2})?$':'^\\d+(?:\\.\\d{1,2})?$').test(raw.trim()))throw Error('Enter GBP with at most two decimal places.');
 const s=raw.trim(),negative=s.startsWith('-'),[whole,fraction='']=s.replace('-','').split('.'),n=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'));
 if(n>BigInt(MAX)||(!zero&&n===0n))throw Error('Amount is outside the supported range.');return Number(negative?-n:n);
}
export function pennies(value){if(!Number.isSafeInteger(value)||Math.abs(value)>MAX)throw Error('Invalid exact-penny value.');return value;}
export function moneyGBP(value){pennies(value);const sign=value<0?'-':'';return sign+'£'+Math.floor(Math.abs(value)/100).toLocaleString('en-GB')+'.'+String(Math.abs(value)%100).padStart(2,'0');}
export function financeDay(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||shiftDay(value,0)!==value)throw Error('Choose a valid calendar date.');return value;}
const name=value=>{if(typeof value!=='string'||!value.trim()||value.length>500)throw Error('Enter a name up to 500 characters.');return value.trim();};
const stamp=now=>new Date(now).toISOString();
const safeSum=values=>values.reduce((n,v)=>pennies(n+pennies(v)),0);
export function migrateFinance(profile,data,now=Date.now()){
 if(data.financeDomain){validateFinance(data.financeDomain,profile.id);return structuredClone(data.financeDomain);}
 const day=dayInZone(now,profileZone(profile.preferences)),state={version:1,revision:0,profileId:profile.id,currency:'GBP',cutoverDate:day,migratedAt:stamp(now),accounts:[],transactions:[],rules:[],occurrences:[],allocations:[],checks:[],operations:[],settings:{horizon:30,budgetDay:Number(data.paydayDay)||null,primaryAccountId:'',spendingAccountId:'',billsReviewedAt:null},legacy:{budgets:structuredClone(data.financeBudgets||[]),savings:structuredClone(data.financeSavings||[]),bills:structuredClone(data.financeBills||[]),quarantine:[]}};
 const quarantine=(collection,row,error)=>state.legacy.quarantine.push({id:'quarantine-'+state.legacy.quarantine.length,collection,raw:structuredClone(row),reason:String(error.message||error),reviewed:false});
 const originalCurrency=profile.preferences?.currency||'GBP';state.legacy.originalCurrency=originalCurrency;
 for(const b of state.legacy.budgets){b.currency=originalCurrency;try{if(originalCurrency!=='GBP')throw Error('Legacy currency requires review');b.limitMinor=minor(b.limit,{zero:true});}catch(e){b.needsReview=true;quarantine('financeBudgets',b,e);}}
 for(const g of state.legacy.savings){g.currency=originalCurrency;try{if(originalCurrency!=='GBP')throw Error('Legacy currency requires review');g.savedMinor=minor(g.current,{zero:true});g.targetMinor=minor(g.target,{zero:true});}catch(e){g.needsReview=true;quarantine('financeSavings',g,e);}}
 for(const row of data.financeAccounts||[]){try{if(originalCurrency!=='GBP')throw Error('Legacy account currency is '+originalCurrency+'; review before establishing a GBP position.');state.accounts.push({...row,id:row.id,profileId:profile.id,currency:'GBP',openingMinor:minor(row.balance,{signed:true,zero:true}),openingDate:day,openingSource:'unverified-legacy-snapshot',verifiedAt:null,verificationBasis:null,archived:false,supported:['Current','Savings','Cash'].includes(row.type||'Current'),type:row.type||'Current'});}catch(error){quarantine('financeAccounts',row,error);}}
 for(const row of data.transactions||[]){try{if(originalCurrency!=='GBP')throw Error('Legacy transaction currency requires review.');financeDay(row.date);if(!['income','expense'].includes(row.type))throw Error('Unknown legacy type');state.transactions.push({...row,profileId:profile.id,currency:'GBP',amountMinor:minor(row.amount),posted:false,historical:true,createdAt:stamp(now),effectiveDate:row.date,source:'legacy',legacyAccountMissing:!!row.accountId&&!state.accounts.some(a=>a.id===row.accountId)});}catch(error){quarantine('transactions',row,error);}}
 validateFinance(state,profile.id);return state;
}
export function balance(state,id){const account=state.accounts.find(a=>a.id===id);if(!account)throw Error('Choose an account in this profile.');return safeSum([account.openingMinor,...state.transactions.filter(t=>t.posted&&!t.voided&&(t.accountId===id||t.toAccountId===id)).map(t=>t.type==='transfer'?(t.accountId===id?-t.amountMinor:t.amountMinor):t.type==='expense'?-t.amountMinor:t.amountMinor)]);}
export function validateFinance(s,profileId){
 if(!s||s.version!==1||s.profileId!==profileId||s.currency!=='GBP')throw Error('Finance belongs to another profile or an unsupported version.');if(!Number.isSafeInteger(s.revision)||s.revision<0)throw Error('Invalid Finance revision.');financeDay(s.cutoverDate);if(!s.legacy||!['budgets','savings','bills','quarantine'].every(k=>Array.isArray(s.legacy[k])))throw Error('Legacy Finance preservation data is missing.');
 for(const key of ['accounts','transactions','rules','occurrences','allocations','checks','operations']){if(!Array.isArray(s[key]))throw Error('Invalid Finance collection.');const ids=new Set();for(const r of s[key]){if(typeof r.id!=='string'||!/^[A-Za-z0-9_.:-]+$/.test(r.id)||ids.has(r.id)||r.profileId!==profileId)throw Error('Invalid Finance record identity.');ids.add(r.id);}}
 const account=id=>s.accounts.find(a=>a.id===id);
 for(const a of s.accounts){pennies(a.openingMinor);financeDay(a.openingDate);if(a.currency!=='GBP'||typeof a.supported!=='boolean'||typeof a.archived!=='boolean')throw Error('Unsupported account currency or lifecycle.');}
 for(const t of s.transactions){if(t.voided!==undefined&&typeof t.voided!=='boolean')throw Error('Invalid reversal lifecycle.');if(typeof t.posted!=='boolean'||!t.posted&&t.historical!==true||!Number.isFinite(Date.parse(t.createdAt)))throw Error('Transaction posting/provenance is missing.');for(const field of ['description','category','notes'])if(t[field]!==undefined&&(typeof t[field]!=='string'||t[field].length>5000))throw Error('Transaction details must be text up to 5,000 characters.');pennies(t.amountMinor);financeDay(t.effectiveDate);if(t.currency!=='GBP'||!['income','expense','transfer','adjustment'].includes(t.type)||t.type!=='adjustment'&&t.amountMinor<=0)throw Error('Invalid financial transaction.');if(t.posted&&(!account(t.accountId)||!account(t.accountId).supported||t.effectiveDate<account(t.accountId).openingDate))throw Error('Posting crosses an opening position or missing account.');if(t.type==='transfer'&&(!account(t.toAccountId)||t.toAccountId===t.accountId||!account(t.toAccountId).supported||t.posted&&t.effectiveDate<account(t.toAccountId).openingDate))throw Error('Invalid linked transfer.');if(t.occurrenceId&&t.internalTransfer)throw Error('Internal transfers cannot settle obligations.');if(t.occurrenceId&&!s.occurrences.some(o=>o.id===t.occurrenceId&&o.kind===t.type&&account(t.accountId)))throw Error('Invalid settlement relationship.');}
 for(const r of s.rules){if(r.currency!=='GBP'||r.day!==null&&r.day!==undefined&&(!Number.isInteger(r.day)||r.day<1||r.day>31)||!['none','preceding-friday'].includes(r.weekend))throw Error('Invalid schedule currency or calendar policy.');pennies(r.amountMinor);financeDay(r.anchor);if(!account(r.accountId)||r.amountMinor<0||!['income','expense'].includes(r.kind)||!['once','weekly','four-weekly','monthly','quarterly','annually'].includes(r.frequency))throw Error('Invalid recurring rule.');}
 for(const r of s.rules)if(r.legacySourceId&&(!s.legacy.bills.some(b=>b.id===r.legacySourceId&&b.ruleId===r.id)||s.rules.some(other=>other.id!==r.id&&other.legacySourceId===r.legacySourceId)))throw Error('Invalid duplicate legacy conversion.');
 for(const r of s.rules)if(r.amountHistory!==undefined){if(!Array.isArray(r.amountHistory)||!r.amountHistory.length)throw Error('Invalid rule amount history.');let previous='';for(const v of r.amountHistory){financeDay(v.effectiveFrom);pennies(v.amountMinor);if(v.amountMinor<0||v.effectiveFrom<=previous)throw Error('Invalid rule amount history order.');if(v.estimate!==undefined&&typeof v.estimate!=='boolean'||v.category!==undefined&&typeof v.category!=='string')throw Error('Invalid rule terms.');previous=v.effectiveFrom;}}
 for(const o of s.occurrences){if(o.currency!=='GBP')throw Error('Invalid occurrence currency.');pennies(o.amountMinor);financeDay(o.date);financeDay(o.nominalDate);const r=s.rules.find(r=>r.id===o.ruleId);if(!account(o.accountId)||!r||r.accountId!==o.accountId||r.kind!==o.kind||o.id!==r.id+':'+o.nominalDate||o.amountMinor<0)throw Error('Invalid occurrence.');}
 for(const a of s.allocations){if(a.currency!=='GBP')throw Error('Invalid protection currency.');pennies(a.amountMinor);if(a.amountMinor<0||!account(a.accountId)||!['independent','essentials','buffer','bill'].includes(a.kind)||a.kind==='bill'&&!s.rules.some(r=>r.id===a.ruleId&&r.accountId===a.accountId&&r.kind==='expense'))throw Error('Invalid protected allocation.');if(a.startDate!==undefined&&a.startDate!==null)financeDay(a.startDate);if(a.endDate!==undefined&&a.endDate!==null)financeDay(a.endDate);if(a.kind==='essentials'&&(!a.startDate||!a.endDate||a.endDate<a.startDate))throw Error('Choose a valid essentials period.');}
 for(const a of s.allocations){if(a.settlementBaselineMinor!==undefined)pennies(a.settlementBaselineMinor);if(a.kind==='bill'&&s.allocations.some(b=>b.id!==a.id&&b.kind==='bill'&&b.ruleId===a.ruleId))throw Error('Edit the existing linked reserve instead of creating another.');if(a.kind==='essentials'&&s.allocations.some(b=>b.id!==a.id&&b.kind==='essentials'&&b.accountId===a.accountId&&b.category===a.category&&b.startDate<=a.endDate&&b.endDate>=a.startDate))throw Error('Essentials allowances for this account/category cannot overlap.');}
 for(const o of s.occurrences){const paid=settled(s,o.id);if(paid>o.amountMinor)throw Error('Payment exceeds the obligation; change its amount explicitly first.');}
 for(const a of s.accounts){balance(s,a.id);if(a.verifiedAt&&!Number.isFinite(Date.parse(a.verifiedAt)))throw Error('Invalid verification time.');}for(const c of s.checks){if(c.currency!=='GBP')throw Error('Invalid observation currency.');for(const k of ['observedMinor','recordedMinor','differenceMinor'])pennies(c[k]);if(!account(c.accountId)||c.differenceMinor!==c.observedMinor-c.recordedMinor||!['booked','available'].includes(c.basis)||!Number.isFinite(Date.parse(c.observedAt)))throw Error('Invalid balance observation.');}
 for(const b of s.legacy.budgets)if(!b.needsReview||b.limitMinor!==undefined)pennies(b.limitMinor);for(const g of s.legacy.savings){if(!g.needsReview||g.savedMinor!==undefined)pennies(g.savedMinor);if(!g.needsReview||g.targetMinor!==undefined)pennies(g.targetMinor);}
 if(s.settings.budgetDay!==null&&s.settings.budgetDay!==undefined&&(!Number.isInteger(s.settings.budgetDay)||s.settings.budgetDay<1||s.settings.budgetDay>31))throw Error('Choose a budget day from 1 to 31.');
 if(!Number.isInteger(s.settings.horizon)||s.settings.horizon<1||s.settings.horizon>366)throw Error('Use a planning horizon from 1 to 366 days.');
 for(const id of [s.settings.primaryAccountId,s.settings.spendingAccountId])if(id&&!account(id)?.supported)throw Error('Choose a supported planning account.');return s;
}
function scheduled(rule,index){
 if(rule.frequency==='once')return index===0?rule.anchor:null;
 if(['weekly','four-weekly'].includes(rule.frequency))return shiftDay(rule.anchor,index*(rule.frequency==='weekly'?7:28));
 const [year,month,day]=rule.anchor.split('-').map(Number),months=index*({monthly:1,quarterly:3,annually:12}[rule.frequency]),d=new Date(Date.UTC(year,month-1+months,1,12)),last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0,12)).getUTCDate();d.setUTCDate(Math.min(rule.day||day,last));let out=d.toISOString().slice(0,10);
 if(rule.weekend==='preceding-friday'){const weekday=d.getUTCDay();if(weekday===0||weekday===6)out=shiftDay(out,weekday===0?-2:-1);}return out;
}
function ruleTerms(rule,nominal){const revisions=rule.amountHistory||[],v=revisions.filter(v=>v.effectiveFrom<=nominal).at(-1);return v?{amountMinor:v.amountMinor,estimate:v.estimate??rule.estimate,category:v.category??rule.category}: {amountMinor:rule.amountMinor,estimate:rule.estimate,category:rule.category};}
export function settled(s,id){return safeSum(s.transactions.filter(t=>t.occurrenceId===id&&!t.voided).map(t=>t.amountMinor));}
export function getOccurrence(s,id){
 const existing=s.occurrences.find(o=>o.id===id);if(existing)return {...existing,settledMinor:settled(s,id),outstandingMinor:Math.max(0,existing.amountMinor-settled(s,id))};
 const r=s.rules.find(r=>id.startsWith(r.id+':'));if(!r||r.archived)throw Error('Choose an active recurring occurrence.');const nominal=id.slice(r.id.length+1);financeDay(nominal);let found=false;for(let i=0;i<20000;i++){const d=scheduled(r,i);if(!d||d>nominal)break;if(d===nominal){found=true;break;}}if(!found)throw Error('This date is not an occurrence of the schedule.');return {id,ruleId:r.id,profileId:s.profileId,currency:'GBP',kind:r.kind,name:r.name,date:nominal,nominalDate:nominal,accountId:r.accountId,...ruleTerms(r,nominal),status:'expected',settledMinor:0,outstandingMinor:ruleTerms(r,nominal).amountMinor};
}
export function occurrences(s,start,end){
 financeDay(start);financeDay(end);if(end<start||Date.parse(end)-Date.parse(start)>732*86400000)throw Error('Choose a forecast window of at most 732 days.');const result=[];
 for(const r of s.rules){if(r.archived)continue;for(let i=0;i<20000;i++){const nominal=scheduled(r,i);if(!nominal||nominal>end)break;const id=r.id+':'+nominal,override=s.occurrences.find(o=>o.id===id),o={id,ruleId:r.id,profileId:s.profileId,currency:'GBP',kind:r.kind,name:r.name,date:nominal,nominalDate:nominal,accountId:r.accountId,...ruleTerms(r,nominal),status:'expected',...override};if(o.date>=start&&o.date<=end&&!['skipped','cancelled'].includes(o.status)){o.settledMinor=settled(s,id);o.outstandingMinor=Math.max(0,o.amountMinor-o.settledMinor);result.push(o);}}}
 // Delayed exceptions may move into the window from an earlier nominal date.
 for(const o of s.occurrences){if(o.date>=start&&o.date<=end&&!result.some(x=>x.id===o.id)&&!['skipped','cancelled'].includes(o.status)&&s.rules.some(r=>r.id===o.ruleId&&!r.archived)){result.push({...o,settledMinor:settled(s,o.id),outstandingMinor:Math.max(0,o.amountMinor-settled(s,o.id))});}}
 return result.sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
}
export function actualTransactions(s){return s.transactions.filter(t=>!t.voided&&!t.internalTransfer&&['income','expense'].includes(t.type)).map(t=>({...t,amount:t.amountMinor/100,date:t.effectiveDate,category:t.category||'Uncategorised'}));}
export function budgetSummary(s,today){
 const d=s.settings.budgetDay,monthly=(y,m)=>{const date=new Date(Date.UTC(y,m,1,12)),last=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,0,12)).getUTCDate();date.setUTCDate(Math.min(d||1,last));return date.toISOString().slice(0,10);},[y,m]=today.split('-').map(Number);let start=monthly(y,m-1);if(start>today)start=monthly(y,m-2);const [sy,sm]=start.split('-').map(Number),end=monthly(sy,sm),transactions=actualTransactions(s).filter(t=>t.date>=start&&t.date<end);
 return {start,end,items:s.legacy.budgets.filter(b=>!b.archived).map(b=>({...b,spentMinor:safeSum(transactions.filter(t=>t.type==='expense'&&t.category===b.category).map(t=>t.amountMinor))}))};
}
export function protection(s,accountId,today,{zone}={}){
 const a=s.accounts.find(a=>a.id===accountId);if(!a?.supported)return {accountId,ready:false,gaps:['Choose a supported cash account.'],balanceMinor:0,protectedMinor:0,remainingMinor:0,horizon:s.settings.horizon,commitments:[]};
 const end=shiftDay(today,s.settings.horizon),start=s.rules.length?s.rules.reduce((d,r)=>r.anchor<d?r.anchor:d,today):today,earliest=start<shiftDay(today,-366)?shiftDay(today,-366):start;
 const obligationRows=occurrences(s,earliest,end).filter(o=>o.kind==='expense'&&o.accountId===accountId),due=obligationRows.filter(o=>o.outstandingMinor>0),commitments=due.map(o=>({id:o.id,name:o.name,amountMinor:o.outstandingMinor,estimate:!!o.estimate,overdue:o.date<today}));
 // Older unresolved occurrences are surfaced, not silently deemed settled.
 const oldRules=s.rules.filter(r=>r.kind==='expense'&&r.accountId===accountId&&!r.archived&&r.anchor<earliest);
 const older=new Map();let capped=false;for(const r of oldRules){let amount=0,nextId=null;for(let i=0;i<20000;i++){const nominal=scheduled(r,i);if(!nominal||nominal>=earliest)break;const id=r.id+':'+nominal,o=s.occurrences.find(o=>o.id===id);if(!o||!['skipped','cancelled'].includes(o.status)){if(!o||o.date<earliest){const remaining=Math.max(0,(o?.amountMinor??ruleTerms(r,nominal).amountMinor)-settled(s,id));amount=pennies(amount+remaining);if(remaining&&!nextId)nextId=id;}}if(i===19999)capped=true;}if(amount){older.set(r.id,amount);commitments.push({id:'older:'+r.id,name:'Older '+r.name,amountMinor:amount,overdue:true,estimate:!!r.estimate,nextOccurrenceId:nextId});}}
 const linked=new Set(s.allocations.filter(x=>x.accountId===accountId&&x.kind==='bill').map(x=>x.ruleId));
 for(const x of s.allocations.filter(x=>x.accountId===accountId&&x.kind!=='bill'&&(x.kind!=='essentials'||x.endDate>=today&&x.startDate<=end))){let amount=x.amountMinor;if(x.kind==='essentials'){const used=safeSum(actualTransactions(s).filter(t=>t.accountId===accountId&&t.type==='expense'&&(!x.category||t.category===x.category)&&t.date>=(x.startDate||today)&&t.date<=(x.endDate||end)).map(t=>t.amountMinor));amount=Math.max(0,amount-used);}commitments.push({id:x.id,name:x.name,amountMinor:amount});}
 // Linked reserves cover their bill once. Excess earmarks remain protected.
 for(const ruleId of linked){const reserve=Math.max(0,safeSum(s.allocations.filter(x=>x.accountId===accountId&&x.kind==='bill'&&x.ruleId===ruleId).map(x=>x.amountMinor))-Math.max(0,safeSum(s.transactions.filter(t=>!t.voided&&s.occurrences.some(o=>o.id===t.occurrenceId&&o.ruleId===ruleId)).map(t=>t.amountMinor))-safeSum(s.allocations.filter(x=>x.accountId===accountId&&x.kind==='bill'&&x.ruleId===ruleId).map(x=>x.settlementBaselineMinor||0)))),outstanding=pennies(safeSum(due.filter(o=>o.ruleId===ruleId).map(o=>o.outstandingMinor))+(older.get(ruleId)||0));if(reserve>outstanding)commitments.push({id:'reserve:'+ruleId,name:'Additional bill reserve',amountMinor:reserve-outstanding});}
 const gaps=[];if(a.verificationNeedsReview)gaps.push('Activity covered by a balance check changed. Check Balance again.');if(!a.verifiedAt)gaps.push('Check Balance: opening position is unverified.');else if(Date.parse(today)-Date.parse(dayInZone(a.verifiedAt,zone))>7*86400000)gaps.push('Balance verification is more than 7 days old.');if(!s.settings.billsReviewedAt)gaps.push('Review Commitments: bill setup is incomplete.');if(s.legacy.bills.some(b=>!b.reviewed))gaps.push('Legacy bills need review.');if(s.legacy.quarantine.some(q=>!q.reviewed))gaps.push('Some legacy records need review.');if(due.some(o=>o.estimate))gaps.push('Some bill amounts or due dates are estimates.');if(older.size||capped)gaps.push(capped?'Older schedule exceeds bounded analysis; review its start date.':'Older unpaid obligations need catch-up review.');
 const recorded=balance(s,accountId),protectedMinor=safeSum(commitments.map(c=>c.amountMinor));return {accountId,balanceMinor:recorded,protectedMinor,remainingMinor:pennies(recorded-protectedMinor),horizon:s.settings.horizon,commitments,gaps,ready:gaps.length===0,verifiedAt:a.verifiedAt};
}
export function forecast(s,today,{accountId,scenarioMinor=0,toAccountId}={}){
 pennies(scenarioMinor);const end=shiftDay(today,s.settings.horizon),balances=Object.fromEntries(s.accounts.filter(a=>a.supported&&!a.archived).map(a=>[a.id,balance(s,a.id)])),rows=[];
 if(accountId){if(!(accountId in balances))throw Error('Choose a forecast account.');balances[accountId]=pennies(balances[accountId]-scenarioMinor);if(toAccountId){if(!(toAccountId in balances)||toAccountId===accountId)throw Error('Choose a different destination.');balances[toAccountId]=pennies(balances[toAccountId]+scenarioMinor);}}
 const events=occurrences(s,today,end).filter(o=>o.outstandingMinor>0);for(const a of s.allocations.filter(a=>a.kind==='essentials'&&a.endDate>=today&&a.startDate<=end)){const used=safeSum(actualTransactions(s).filter(t=>t.type==='expense'&&t.accountId===a.accountId&&(!a.category||t.category===a.category)&&t.date>=a.startDate&&t.date<=a.endDate).map(t=>t.amountMinor)),remaining=Math.max(0,a.amountMinor-used);if(remaining)events.push({id:'allowance:'+a.id,name:a.name,kind:'expense',accountId:a.accountId,date:a.endDate>end?end:a.endDate,outstandingMinor:remaining,estimate:true});}events.sort((a,b)=>a.date.localeCompare(b.date)||(a.kind==='expense'?-1:1));
 for(const o of events){if(!(o.accountId in balances))continue;balances[o.accountId]=pennies(balances[o.accountId]+(o.kind==='income'?o.outstandingMinor:-o.outstandingMinor));rows.push({...o,projectedMinor:balances[o.accountId],shortfall:balances[o.accountId]<0,conditional:o.kind==='income'});}return {balances,rows,assumptions:'Projection only. Same-day payments precede income; expected receipts are conditional. Remaining essentials allowances are estimated outflows. Protected earmarks are not additional payments. Nothing here is posted.'};
}
export function financeProjection(s,collection,today=dayInZone()){
 if(collection==='transactions')return actualTransactions(s);
 if(collection==='financeAccounts')return s.accounts.map(a=>({...a,balance:balance(s,a.id)/100}));
 if(collection==='financeBudgets')return s.legacy.budgets;
 if(collection==='financeSavings')return s.legacy.savings;
 if(collection==='financeBills')return [...s.legacy.bills.map(b=>({...b,needsReview:true})),...occurrences(s,shiftDay(today,-366),shiftDay(today,366)).filter(o=>o.kind==='expense').map(o=>({...o,due:o.date,amount:o.amountMinor/100,paid:o.outstandingMinor===0,archived:s.rules.find(r=>r.id===o.ruleId)?.reminder===false}))];
}
export function financePlan(services,context,request){
 const action=request.action,raw=services.storage.getItem(FINANCE_KEY);if(!raw)return null;
 if(!action.startsWith('finance.')&&action!=='transaction.create'&&!(action==='record.delete'&&FINANCE_COLLECTIONS.includes(request.collection)))return null;
 if(Object.keys(request).some(k=>!COMMAND_FIELDS.has(k)))throw Error('Unsupported Finance command fields.');if(request.currency&&request.currency!=='GBP')throw Error('Finance Phase 1 records GBP only; no currency conversion is performed.');
 const before=raw,s=JSON.parse(raw);validateFinance(s,context.profileId);const now=services.now(),today=dayInZone(now,profileZone(services.storage.profile.preferences)),changes={},result={},makeId=()=>services.uuid(),owned=id=>{const a=s.accounts.find(a=>a.id===id);if(!a||!a.supported||a.archived)throw Error('Choose an active GBP cash account in this profile.');return a;};let risk='low-risk-write';
 if(action==='finance.draft'){if(!['check','transfer','bills','forecast'].includes(request.mode))throw Error('Choose a Finance action.');return {risk:'safe-read',changes,result:{financeDraft:request.mode}};}
 if(action==='finance.summary'||action==='finance.get'){const p=protection(s,request.accountId||s.settings.primaryAccountId,today,{zone:profileZone(services.storage.profile.preferences)}),tx=actualTransactions(s);return {risk:'safe-read',changes,result:{finance:s,protection:p,currency:'GBP',income:safeSum(tx.filter(t=>t.type==='income').map(t=>t.amountMinor))/100,expenses:safeSum(tx.filter(t=>t.type==='expense').map(t=>t.amountMinor))/100,accountBalance:safeSum(s.accounts.filter(a=>a.supported&&!a.archived).map(a=>balance(s,a.id)))/100}};}
 if(action==='finance.forecast')return {risk:'safe-read',changes,result:{forecast:forecast(s,today,{accountId:request.accountId,scenarioMinor:request.amount?minor(request.amount,{zero:true}):0,toAccountId:request.toAccountId})}};
 if(action==='record.delete')throw Error('Finance records must be archived or reversed through Finance.');
 const operationId=request.operationId||makeId();if(typeof operationId!=='string'||!/^[A-Za-z0-9_.:-]{1,150}$/.test(operationId))throw Error('Invalid operation identity.');const signature=JSON.stringify(Object.fromEntries(Object.keys(request).filter(k=>!['operationId','expectedFinanceRevision'].includes(k)).sort().map(k=>[k,request[k]])));const prior=s.operations.find(o=>o.id===operationId);if(prior){if(prior.signature!==signature)throw Error('Operation identity was already used for a different request.');return {risk:'safe-read',changes,result:{item:prior.result,retried:true}};}
 if(request.expectedFinanceRevision!==undefined&&request.expectedFinanceRevision!==s.revision)throw Error('Finance changed while this form was open. Reopen it before saving.');
 const postingBoundary=(id,effectiveDate)=>{const a=owned(id);if(effectiveDate<a.openingDate)throw Error('This date crosses the opening cutover. Add historical information explicitly.');if(a.verifiedAt&&effectiveDate<dayInZone(a.verifiedAt,profileZone(services.storage.profile.preferences)))throw Error('This activity predates the checked balance. Explain an adjustment or add explicit historical information instead.');return a;};
 const transaction=(type,accountId,amountMinor,extra={})=>{const a=owned(accountId),effectiveDate=financeDay(request.date||today);if(effectiveDate>today)throw Error('Future income/payments belong in expected schedules.');postingBoundary(accountId,effectiveDate);if(type==='transfer')postingBoundary(extra.toAccountId,effectiveDate);const row={id:makeId(),profileId:s.profileId,currency:'GBP',accountId,type,amountMinor,effectiveDate,createdAt:stamp(now),source:request.source||'manual',externalReference:request.externalReference||null,posted:true,description:request.description||'',category:request.category||'Uncategorised',notes:request.notes||'',...extra};s.transactions.push(row);return row;};
 const occurrence=id=>{let o=s.occurrences.find(x=>x.id===id);if(!o){o=getOccurrence(s,id);delete o.settledMinor;delete o.outstandingMinor;s.occurrences.push(o);}return o;};
 if(action==='finance.account.save'){
  if(request.id){const a=s.accounts.find(a=>a.id===request.id);if(!a)throw Error('Choose an account in this profile.');a.name=name(request.name);a.bank=request.bank||'';if(request.type&&request.type!==a.type)throw Error('Account type cannot silently change its balance semantics.');result.item=a;}
  else{const a={id:makeId(),profileId:s.profileId,name:name(request.name),bank:request.bank||'',currency:'GBP',type:request.type||'Current',supported:true,openingMinor:minor(request.amount||'0',{signed:true,zero:true}),openingDate:today,openingSource:'user-entered',verifiedAt:null,archived:false};if(!['Current','Savings','Cash'].includes(a.type))throw Error('Use Current, Savings or Cash.');s.accounts.push(a);if(!s.settings.primaryAccountId)s.settings.primaryAccountId=a.id;result.item=a;}
 }else if(action==='finance.account.reopen'){const a=s.accounts.find(a=>a.id===request.id);if(!a?.supported)throw Error('Choose a supported archived account.');a.archived=false;result.item=a;
 }else if(action==='finance.account.archive'){const a=s.accounts.find(a=>a.id===request.id);if(!a)throw Error('Account not found.');if(s.rules.some(r=>r.accountId===a.id&&!r.archived)||s.allocations.some(x=>x.accountId===a.id))throw Error('Move or archive its commitments before archiving this account.');a.archived=true;if(s.settings.primaryAccountId===a.id)s.settings.primaryAccountId='';if(s.settings.spendingAccountId===a.id)s.settings.spendingAccountId='';risk='always-confirm';result.item=a;
 }else if(action==='transaction.create'||action==='finance.transaction.create'){const type=request.type||'expense',accountId=request.accountId||(type==='income'?s.settings.primaryAccountId:s.settings.spendingAccountId||s.settings.primaryAccountId);if(!['income','expense'].includes(type))throw Error('Choose income or expense.');result.item=transaction(type,accountId,minor(request.amount));if(result.item.amountMinor>=100000)risk='confirm';
 }else if(action==='finance.transfer'){owned(request.toAccountId);if(request.toAccountId===request.accountId)throw Error('Choose two different accounts.');result.item=transaction('transfer',request.accountId,minor(request.amount),{toAccountId:request.toAccountId});risk='confirm';
 }else if(action==='finance.transaction.correct'||action==='finance.transaction.reverse'){
  const old=s.transactions.find(t=>t.id===request.id);if(!old||old.voided)throw Error('Choose an active transaction.');if(old.historical)throw Error('Legacy history is preserved; use an explicit historical annotation.');if(request.accountId&&request.accountId!==old.accountId||request.toAccountId&&request.toAccountId!==old.toAccountId)throw Error('Reverse and record a replacement to change transaction accounts safely.');for(const id of [old.accountId,old.toAccountId].filter(Boolean)){const a=s.accounts.find(a=>a.id===id);if(a?.verifiedAt&&(Date.parse(old.createdAt)<=Date.parse(a.verifiedAt)||old.checkId||old.explainsId||old.remainderOf))a.verificationNeedsReview=true;}old.voided=true;old.reversedAt=stamp(now);old.reversalReason=request.reason||'User correction';risk='always-confirm';
  if(action==='finance.transaction.correct'){const amountMinor=minor(request.amount,{signed:old.type==='adjustment'}),replacement={...old,id:makeId(),amountMinor,voided:false,reversedAt:null,reversalReason:null,correctsId:old.id,createdAt:stamp(now),description:request.description??old.description,category:request.category??old.category,notes:request.notes??old.notes};if(request.date){replacement.effectiveDate=financeDay(request.date);if(replacement.effectiveDate!==old.effectiveDate)for(const id of [old.accountId,old.toAccountId].filter(Boolean))postingBoundary(id,replacement.effectiveDate);if(replacement.effectiveDate<owned(old.accountId).openingDate||replacement.effectiveDate>today)throw Error('Correction crosses the posting cutover.');}s.transactions.push(replacement);result.item=replacement;}else result.item=old;
 }else if(action==='finance.history.correct'||action==='finance.history.reverse'){const old=s.transactions.find(t=>t.id===request.id&&t.historical&&!t.voided);if(!old)throw Error('Choose an active historical record.');old.voided=true;old.reversedAt=stamp(now);old.reversalReason='Historical correction / exclusion; no ledger posting';risk='always-confirm';result.item=old;if(action==='finance.history.correct'){const effectiveDate=financeDay(request.date||old.effectiveDate);if(effectiveDate>today)throw Error('Choose a recorded historical date.');const replacement={...old,id:makeId(),voided:false,reversedAt:null,reversalReason:null,correctsId:old.id,source:'manual-historical-correction',createdAt:stamp(now),amountMinor:minor(request.amount),effectiveDate,description:request.description??old.description,category:request.category??old.category,notes:request.notes??old.notes};s.transactions.push(replacement);result.item=replacement;}
 }else if(action==='finance.history.create'){const effectiveDate=financeDay(request.date),accountId=request.accountId||'';if(effectiveDate>today||accountId&&!s.accounts.some(a=>a.id===accountId))throw Error('Choose a past date and an account in this profile, or Unallocated.');if(!['income','expense'].includes(request.type))throw Error('Choose income or expense.');result.item={id:makeId(),profileId:s.profileId,currency:'GBP',type:request.type,amountMinor:minor(request.amount),accountId,effectiveDate,createdAt:stamp(now),source:'manual-historical',posted:false,historical:true,description:request.description||'',category:request.category||'Uncategorised'};s.transactions.push(result.item);risk='confirm';
 }else if(action==='finance.history.annotate'){const old=s.transactions.find(t=>t.id===request.id&&t.historical);if(!old)throw Error('Choose a historical record.');old.annotation=String(request.notes||'').slice(0,5000);result.item=old;
 }else if(action==='finance.balance.check'){
  const a=owned(request.accountId),observed=minor(request.amount,{signed:true,zero:true}),basis=request.basis||'booked';if(!['booked','available'].includes(basis))throw Error('Choose posted/booked or available balance.');const recorded=balance(s,a.id),difference=pennies(observed-recorded),check={id:makeId(),profileId:s.profileId,currency:'GBP',accountId:a.id,observedMinor:observed,recordedMinor:recorded,differenceMinor:difference,basis,observedAt:stamp(now),reconciled:false};s.checks.push(check);result.check=check;
  if(basis==='booked'&&difference===0){a.verifiedAt=stamp(now);a.verificationNeedsReview=false;a.verificationBasis=basis;check.reconciled=true;}
 }else if(action==='finance.balance.reconcile'){
  const check=s.checks.find(c=>c.id===request.id);if(!check||check.reconciled||check.basis!=='booked')throw Error('Choose an unreconciled posted/booked balance check.');const a=owned(check.accountId);if(balance(s,a.id)!==check.recordedMinor)throw Error('Activity changed after this check. Check Balance again.');result.item=transaction('adjustment',a.id,check.differenceMinor,{description:'Unexplained balance reconciliation',checkId:check.id});check.reconciled=true;a.verifiedAt=check.observedAt;a.verificationNeedsReview=false;a.verificationBasis=check.basis;risk='confirm';
 }else if(action==='finance.adjustment.explain'){
  const adjustment=s.transactions.find(t=>t.id===request.id&&t.type==='adjustment'&&!t.voided);if(!adjustment)throw Error('Choose an unexplained adjustment.');const amount=minor(request.amount),remaining=Math.abs(adjustment.amountMinor)-amount;if(remaining<0)throw Error('Explanation exceeds the remaining adjustment.');adjustment.voided=true;adjustment.reversedAt=stamp(now);const type=adjustment.amountMinor<0?'expense':'income';result.item=transaction(type,adjustment.accountId,amount,{effectiveDate:adjustment.effectiveDate,explainsId:adjustment.id});if(remaining)s.transactions.push({...adjustment,id:makeId(),voided:false,reversedAt:null,amountMinor:remaining*(type==='expense'?-1:1),createdAt:stamp(now),remainderOf:adjustment.id});risk='confirm';
 }else if(action==='finance.rule.save'){
  if(request.legacyId){const legacy=s.legacy.bills.find(b=>b.id===request.legacyId);if(!legacy)throw Error('Legacy bill not found.');if(legacy.ruleId){const linked=s.rules.find(r=>r.id===legacy.ruleId);if(!linked)throw Error('The legacy bill link needs review.');return {risk:'safe-read',changes,result:{item:linked,conversionExisting:true}};}if(legacy.reviewed)throw Error('This legacy bill was already reviewed. Add a new commitment explicitly.');}
  owned(request.accountId);const r={id:request.id||makeId(),profileId:s.profileId,currency:'GBP',...(request.legacyId?{legacySourceId:request.legacyId}:{}),name:name(request.name),kind:request.kind,amountMinor:minor(request.amount,{zero:true}),accountId:request.accountId,anchor:financeDay(request.anchor),frequency:request.frequency,day:request.day?Number(request.day):null,weekend:request.weekend||'none',estimate:!!request.estimate,category:request.category||'Uncategorised',reminder:request.kind==='expense'&&request.reminder!==false,createdAt:stamp(now)};
  if(r.day!==null&&(!Number.isInteger(r.day)||r.day<1||r.day>31)||!['none','preceding-friday'].includes(r.weekend))throw Error('Invalid recurrence settings.');if(request.id){const old=s.rules.find(r=>r.id===request.id);if(!old)throw Error('Rule not found.');if(['kind','accountId','anchor','frequency','day','weekend'].some(k=>old[k]!==r[k]))throw Error('Archive this rule and create a replacement to change its schedule/account while preserving occurrences.');r.amountHistory=structuredClone(old.amountHistory||[{effectiveFrom:scheduled(old,0),amountMinor:old.amountMinor,estimate:old.estimate,category:old.category}]);if(['amountMinor','estimate','category'].some(k=>old[k]!==r[k])){const effectiveFrom=financeDay(request.effectiveDate||today);if(effectiveFrom<today||effectiveFrom<r.amountHistory.at(-1).effectiveFrom)throw Error('Rule edits must apply prospectively.');const revision={effectiveFrom,amountMinor:r.amountMinor,estimate:r.estimate,category:r.category};if(r.amountHistory.at(-1).effectiveFrom===effectiveFrom)r.amountHistory[r.amountHistory.length-1]=revision;else r.amountHistory.push(revision);}Object.assign(old,r);risk='confirm';}else s.rules.push(r);result.item=r;
  if(request.legacyId){const legacy=s.legacy.bills.find(b=>b.id===request.legacyId);if(!legacy)throw Error('Legacy bill not found.');legacy.reviewed=true;legacy.ruleId=r.id;}
 }else if(action==='finance.rule.reopen'){const r=s.rules.find(r=>r.id===request.id);if(!r)throw Error('Rule not found.');owned(r.accountId);r.archived=false;result.item=r;risk='confirm';
 }else if(action==='finance.rule.archive'){const r=s.rules.find(r=>r.id===request.id);if(!r)throw Error('Rule not found.');if(s.allocations.some(a=>a.ruleId===r.id))throw Error('Remove linked protection first.');r.archived=true;result.item=r;risk='confirm';
 }else if(action==='finance.occurrence.update'){const o=occurrence(request.id);if(request.date)o.date=financeDay(request.date);if(request.amount!==undefined)o.amountMinor=minor(request.amount,{zero:true});if(request.status){if(!['expected','skipped','cancelled'].includes(request.status)||request.status!=='expected'&&settled(s,o.id)>0)throw Error('Reverse payments before cancelling a settled occurrence.');o.status=request.status;}result.item=o;risk='confirm';
 }else if(action==='finance.occurrence.pay'){
  const o=occurrence(request.id);if(['skipped','cancelled'].includes(o.status))throw Error('This occurrence is inactive.');if(request.transactionId){const t=s.transactions.find(t=>t.id===request.transactionId);if(!t||t.voided||t.internalTransfer||t.effectiveDate>today||t.type!==o.kind||!s.accounts.some(a=>a.id===t.accountId&&a.supported&&!a.archived)||t.occurrenceId)throw Error('Choose an unallocated matching transaction.');t.occurrenceId=o.id;result.item=t;}else result.item=transaction(o.kind,request.accountId||o.accountId,minor(request.amount),{occurrenceId:o.id,description:request.description||o.name,category:o.category||s.rules.find(r=>r.id===o.ruleId)?.category||'Uncategorised'});risk='confirm';
 }else if(action==='finance.allocation.save'){owned(request.accountId);const previous=s.allocations.find(x=>x.id===request.id);const sameBill=previous?.kind==='bill'&&request.kind==='bill'&&previous.ruleId===request.ruleId&&previous.accountId===request.accountId;const a={id:request.id||makeId(),profileId:s.profileId,currency:'GBP',name:name(request.name),accountId:request.accountId,amountMinor:minor(request.amount,{zero:true}),kind:request.kind||'independent',ruleId:request.ruleId||'',settlementBaselineMinor:sameBill?previous.settlementBaselineMinor||0:request.kind==='bill'?safeSum(s.transactions.filter(t=>!t.voided&&s.occurrences.some(o=>o.id===t.occurrenceId&&o.ruleId===request.ruleId)).map(t=>t.amountMinor)):0,category:request.category||'',startDate:request.startDate||today,endDate:request.endDate||shiftDay(today,s.settings.horizon)};if(request.id){const old=s.allocations.find(x=>x.id===request.id);if(!old)throw Error('Allocation not found.');if(['amountMinor','kind','ruleId','accountId','category','startDate','endDate'].some(k=>old[k]!==a[k]))risk='confirm';Object.assign(old,a);}else s.allocations.push(a);result.item=a;
 }else if(action==='finance.allocation.remove'){const a=s.allocations.find(a=>a.id===request.id);if(!a)throw Error('Allocation not found.');s.allocations=s.allocations.filter(a=>a.id!==request.id);risk='always-confirm';result.item=a;
 }else if(action==='finance.quarantine.review'){const q=s.legacy.quarantine.find(q=>q.id===request.id);if(!q)throw Error('Choose a preserved record.');q.reviewed=true;q.reviewNote=request.notes||'Reviewed and retained without posting';risk='confirm';result.item=q;
 }else if(action==='finance.legacy.review'){const b=s.legacy.bills.find(x=>x.id===request.id);if(!b)throw Error('Legacy bill not found.');b.reviewed=true;b.reviewNote=request.notes||'No longer a commitment';risk='confirm';result.item=b;
 }else if(action==='finance.budget.archive'||action==='finance.saving.archive'){const rows=s.legacy[action==='finance.budget.archive'?'budgets':'savings'],row=rows.find(x=>x.id===request.id);if(!row)throw Error('Record not found.');row.archived=true;risk='always-confirm';result.item=row;
 }else if(action==='finance.budget.save'||action==='finance.saving.save'){
  const budget=action==='finance.budget.save',key=budget?'budgets':'savings',row={id:request.id||makeId(),currency:'GBP',name:name(request.name),...(budget?{category:name(request.name),limitMinor:minor(request.amount,{zero:true})}:{savedMinor:minor(request.amount,{zero:true}),targetMinor:minor(request.target,{zero:true})})};if(budget){row.limit=row.limitMinor/100;row.needsReview=false;}else{row.current=row.savedMinor/100;row.target=row.targetMinor/100;row.needsReview=false;}const old=s.legacy[key].find(x=>x.id===row.id);if(request.id&&!old)throw Error('Record not found.');if(old)Object.assign(old,row);else s.legacy[key].push(row);result.item=row;
 }else if(action==='finance.settings'){for(const field of ['horizon','budgetDay','primaryAccountId','spendingAccountId'])if(request[field]!==undefined)s.settings[field]=request[field];if(request.billsReviewed===true){if(s.legacy.bills.some(b=>!b.reviewed))throw Error('Review each legacy bill first.');s.settings.billsReviewedAt=stamp(now);}result.settings=s.settings;
 }else throw Error('Unknown Finance command.');
 if(result.item?.amountMinor!==undefined)result.item={...result.item,amount:result.item.amountMinor/100};
 s.revision++;s.operations.push({id:operationId,profileId:s.profileId,signature,result:structuredClone(result.item||result.check||result.settings),timestamp:stamp(now)});validateFinance(s,context.profileId);changes[FINANCE_KEY]=JSON.stringify(s);return {risk,changes,before:{[FINANCE_KEY]:before},result,financeCommand:true,confirmation:financeConfirmation(JSON.parse(before),s,action,result)};
}

export function financeConfirmation(before,after,action,result){
 const item=result.item||result.check||{},account=id=>after.accounts.find(a=>a.id===id)?.name||'Unallocated',lines=[],effects=after.accounts.map(a=>({name:a.name,beforeMinor:before.accounts.some(old=>old.id===a.id)?balance(before,a.id):0,afterMinor:balance(after,a.id)})).filter(a=>a.beforeMinor!==a.afterMinor);
 if(action==='finance.transfer')lines.push('Amount: '+moneyGBP(item.amountMinor),'From: '+account(item.accountId),'To: '+account(item.toAccountId),'Records a completed transfer; does not send money.');
 else if(action==='finance.balance.reconcile'){const c=after.checks.find(c=>c.id===item.checkId);lines.push('Account: '+account(c.accountId),'Observed bank balance: '+moneyGBP(c.observedMinor),'Current ledger balance: '+moneyGBP(c.recordedMinor),'Adjustment: '+moneyGBP(c.differenceMinor));}
 else if(action==='finance.occurrence.pay'){const o=after.occurrences.find(o=>o.id===item.occurrenceId);lines.push('Bill / income: '+o.name,'Amount: '+moneyGBP(item.amountMinor),'Payment account: '+account(item.accountId),item.historical?'Matches historical activity already included in an opening balance.':'Actual recorded payment / receipt.');}
 else {lines.push('Record: '+(item.description||item.name||item.category||action.replace('finance.','').replaceAll('.',' ')));const old=before.transactions.find(t=>t.id===item.correctsId||t.id===item.id)||before.rules.find(r=>r.id===item.id)||before.allocations.find(a=>a.id===item.id);if(old?.amountMinor!==undefined)lines.push('Before: '+moneyGBP(old.amountMinor));if(item.amountMinor!==undefined)lines.push('After / affected amount: '+moneyGBP(item.amountMinor));if(item.accountId)lines.push('Account: '+account(item.accountId));if(item.amountHistory?.length)lines.push('New schedule amount applies from: '+item.amountHistory.at(-1).effectiveFrom);if(item.kind==='bill'&&item.settlementBaselineMinor!==undefined)lines.push('Reserve amount includes payments since its original baseline.');if(item.historical)lines.push('Historical information only; no ledger posting.');}
 if(item.effectiveDate)lines.push('Effective date: '+item.effectiveDate);
 for(const e of effects)lines.push(e.name+': '+moneyGBP(e.beforeMinor)+' → '+moneyGBP(e.afterMinor)+' (change '+moneyGBP(e.afterMinor-e.beforeMinor)+')');
 return {title:'Review financial change',lines};
}
