import {dayInZone,shiftDay,dayBounds,profileZone} from './date-time.js';
import {calendarDays,sessionSlices,sessionDuration} from './life-tracking.js';
import {habitDayStatus} from './habits-trackers.js';

export const GOAL_COLLECTIONS=['lifeAreas','lifeAreaCheckins','goals','objectives','goalActionLinks','goalRelatedAreas','goalMilestones','weeklyFocus','goalActivity','tasks','routines','habits','habitLogs','routineChecks','workSessions','notes','history'];
export const GOAL_STATUSES=['Not Started','On Track','At Risk','Paused','Completed','Archived'];
const active=g=>!['Paused','Completed','Archived'].includes(g.status);
const clamp=n=>Math.max(0,Math.min(100,n));
const stamp=now=>new Date(now).toISOString();
export function goalData(services,context){services.context(context);return Object.fromEntries(GOAL_COLLECTIONS.map(key=>[key,services.read(context,'lifeos4.'+key,key==='routineChecks'?{}:[])]))}
// Older goals are interpreted losslessly; no synthetic creation dates, areas or activity.
export function goalView(g){return {...g,name:g.name||g.title,type:g.type||'outcome',status:g.status||(Number(g.progress)>=100?'Completed':'On Track'),progressMethod:g.progressMethod||'manual',manualProgress:g.manualProgress??g.progress??0,targetDate:g.targetDate??g.date??'',priority:g.priority||'Medium'}}
export function weekKey(day,weekStart=1){return calendarDays(day,'week',weekStart)[0]}
export function focusForWeek(data,day,weekStart=1){const week=weekKey(day,weekStart);return data.weeklyFocus.filter(x=>x.week===week&&x.state==='active').filter(x=>x.kind==='goal'?active(goalView(data.goals.find(g=>g.id===x.targetId)||{status:'Archived'})):!['Completed','Archived'].includes(data.objectives.find(o=>o.id===x.targetId)?.status||'Archived'))}
export function linksFor(data,goalId,objectiveId=null){return data.goalActionLinks.filter(x=>x.goalId===goalId&&(objectiveId===null||x.objectiveId===objectiveId))}
function source(data,link){return data[{task:'tasks',routine:'routines',habit:'habits'}[link.kind]]?.find(x=>x.id===link.actionId)}
function actionFraction(data,link){const record=source(data,link);if(!record)return null;if(link.kind==='task')return record.status==='archived'?null:record.status==='completed'?1:0;if(!link.includeProgress)return null;
 if(link.kind==='habit'){if(!(link.targetCount>0))return null;const dates=new Set(data.habitLogs.filter(x=>x.habitId===record.id&&x.value!==false&&!x.revoked&&x.state!=='SKIPPED'&&(!link.sinceDate||x.date>=link.sinceDate)).map(x=>x.date));const count=[...dates].filter(day=>!record.mode||habitDayStatus(data,record,day).state==='TARGET_MET').length;return Math.min(1,count/link.targetCount)}
 if(link.kind==='routine'){if(!link.occurrenceDate||!record.steps?.length)return null;return record.steps.filter((_,i)=>data.routineChecks[`${link.occurrenceDate}|${record.id}|${i}`]).length/record.steps.length}return null;
}
export function objectiveProgress(data,objective){if(objective.status==='Completed')return {percent:100,label:'Complete',source:'Marked complete',count:0};const fractions=linksFor(data,objective.goalId,objective.id).map(x=>actionFraction(data,x)).filter(x=>x!==null);return fractions.length?{percent:Math.round(fractions.reduce((n,x)=>n+x,0)/fractions.length*100),label:`${fractions.filter(x=>x===1).length} / ${fractions.length} actions complete`,source:'Directly linked completion-based actions',count:fractions.length}:{percent:null,label:'No measurable actions yet',source:'Link a task to calculate progress',count:0}}
export function goalProgress(data,raw){const g=goalView(raw);if(g.type==='ongoing')return {percent:null,label:'Ongoing',source:'Activity, without a completion percentage'};
 if(g.progressMethod==='numeric'){const n=g.numeric||{},start=n.start??0,span=n.target-start;const percent=Number.isFinite(span)&&span!==0&&Number.isFinite(n.current)?clamp((n.current-start)/span*100):null;return {percent:percent===null?null:Math.round(percent),label:percent===null?'Set a numeric target':`${n.current} / ${n.target}${n.unit?' '+n.unit:''}`,source:start!==0?`Starting value: ${start}`:'Numeric target',remaining:percent===null?null:Math.abs(n.target-n.current),numeric:n};}
 if(g.progressMethod==='manual')return {percent:clamp(Number(g.manualProgress)||0),label:`${clamp(Number(g.manualProgress)||0)}%`,source:'Manually tracked'};
 const objectives=data.objectives.filter(x=>x.goalId===g.id&&!['Archived','Paused'].includes(x.status)),parts=objectives.map(o=>({id:o.id,title:o.name,...objectiveProgress(data,o)}));
 const direct=linksFor(data,g.id).filter(x=>!x.objectiveId).map(x=>({title:source(data,x)?.title||source(data,x)?.name||'Linked action',fraction:actionFraction(data,x)})).filter(x=>x.fraction!==null);
 const measurable=parts.filter(x=>x.percent!==null),values=[...measurable.map(x=>x.percent/100),...direct.map(x=>x.fraction)];
 return {percent:values.length?Math.round(values.reduce((n,x)=>n+x,0)/values.length*100):null,label:values.length?'Automatic progress':'No measurable actions yet',source:values.length?`Calculated from ${measurable.length} measurable objective${measurable.length===1?'':'s'} and ${direct.length} direct action${direct.length===1?'':'s'}${parts.length>measurable.length?'; unmeasured objectives excluded':''}`:'Add a completion-based action when useful',parts};
}
function belongs(data,session,goalId,objectiveId){const objective=session.objectiveId&&data.objectives.find(x=>x.id===session.objectiveId);return objectiveId?session.objectiveId===objectiveId:(objective?objective.goalId===goalId:session.goalId===goalId)}
export function goalTime(data,goalId,{objectiveId=null,now=Date.now(),preferences={}}={}){const zone=profileZone(preferences),today=dayInZone(now,zone),week=weekKey(today,preferences.weekStart??1),month=today.slice(0,7)+'-01',sessions=data.workSessions.filter(x=>belongs(data,x,goalId,objectiveId)),sum=(start,end)=>sessions.reduce((n,s)=>n+(s.segments||[]).reduce((m,x)=>m+Math.max(0,Math.min(x.end?Date.parse(x.end):now,end)-Math.max(Date.parse(x.start),start)),0),0);
 return {today:sum(dayBounds(today,zone).start,dayBounds(today,zone).end),week:sum(dayBounds(week,zone).start,dayBounds(shiftDay(week,7),zone).start),month:sum(dayBounds(month,zone).start,now),lifetime:sessions.reduce((n,s)=>n+sessionDuration(s,now),0),sessions:sessions.slice().sort((a,b)=>(b.startedAt||'').localeCompare(a.startedAt||''))};}
export function goalHistory(data,goalId,{now=Date.now(),preferences={}}={}){const entries=data.goalActivity.filter(x=>x.goalId===goalId).map(x=>({...x,kind:'activity'})),objectiveIds=new Set(data.objectives.filter(x=>x.goalId===goalId).map(x=>x.id));
 for(const e of data.history){if(e.goalId===goalId||objectiveIds.has(e.objectiveId)||e.contributions?.some(x=>x.goalId===goalId))entries.push({...e,kind:'completion',label:`${e.title} ${e.action}`})}
 for(const s of goalTime(data,goalId,{now,preferences}).sessions)if(s.status==='stopped'&&s.endedAt)entries.push({id:'work:'+s.id,kind:'work',objectiveId:s.objectiveId||null,timestamp:s.endedAt,label:`Work recorded: ${s.title||'Work session'}`,milliseconds:sessionDuration(s,now)});
 return entries.sort((a,b)=>(b.timestamp||'').localeCompare(a.timestamp||''));}
export function goalSummary(data,raw,options={}){const g=goalView(raw),history=goalHistory(data,g.id,options),today=dayInZone(options.now??Date.now(),profileZone(options.preferences)),week=weekKey(today,options.preferences?.weekStart??1),activity=history.filter(x=>x.timestamp&&dayInZone(x.timestamp,profileZone(options.preferences))>=week&&dayInZone(x.timestamp,profileZone(options.preferences))<=today),time=goalTime(data,g.id,options),links=linksFor(data,g.id),tasks=links.filter(x=>x.kind==='task').map(x=>source(data,x)).filter(x=>x&&!['completed','archived'].includes(x.status)).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||(a.priority==='High'?-1:0)-(b.priority==='High'?-1:0));
 return {...g,progressInfo:goalProgress(data,g),time,history,nextAction:tasks[0]||null,activeThisWeek:activity.length>0||time.week>0,activityCount:activity.filter(x=>x.action==='completed').length,lastActivity:history.find(x=>x.timestamp)?.timestamp||null,links};}
export function areaSummary(data,area,options={}){const goals=data.goals.filter(x=>x.lifeAreaId===area.id).map(x=>goalSummary(data,x,options)),current=goals.filter(active),focus=focusForWeek(data,dayInZone(options.now??Date.now(),profileZone(options.preferences)),options.preferences?.weekStart??1).filter(f=>f.kind==='goal'?goals.some(g=>g.id===f.targetId):data.objectives.some(o=>o.id===f.targetId&&goals.some(g=>g.id===o.goalId)));const relatedGoals=data.goalRelatedAreas.filter(x=>x.areaId===area.id).map(x=>data.goals.find(g=>g.id===x.goalId)).filter(Boolean).map(g=>goalSummary(data,g,options));return {...area,goals,relatedGoals,active:current,paused:goals.filter(x=>x.status==='Paused'),focus,activeThisWeek:current.filter(x=>x.activeThisWeek).length,timeThisWeek:goals.reduce((n,g)=>n+g.time.week,0),activity:goals.flatMap(x=>x.history).sort((a,b)=>(b.timestamp||'').localeCompare(a.timestamp||'')).slice(0,8)}}
export function prioritizedGoals(data,options={}){const day=dayInZone(options.now??Date.now(),profileZone(options.preferences)),focus=focusForWeek(data,day,options.preferences?.weekStart??1),focused=new Set(focus.map(f=>f.kind==='goal'?f.targetId:data.objectives.find(o=>o.id===f.targetId)?.goalId));const deadline=g=>[g.targetDate,...data.objectives.filter(o=>o.goalId===g.id&&!['Completed','Archived','Paused'].includes(o.status)).map(o=>o.targetDate)].filter(Boolean).sort()[0]||'9999';return data.goals.map(g=>({...goalSummary(data,g,options),focused:focused.has(g.id)})).filter(g=>g.status!=='Archived').sort((a,b)=>Number(b.focused)-Number(a.focused)||Number(active(b))-Number(active(a))||deadline(a).localeCompare(deadline(b)));}
export function goalSearch(data,query){const q=String(query||'').trim().toLowerCase();if(!q)return [];return [['Life Area',data.lifeAreas,'area'],['Goal',data.goals,'goal'],['Objective',data.objectives,'objective'],['Milestone',data.goalMilestones,'milestone']].flatMap(([type,rows,kind])=>rows.filter(x=>String(x.name||x.title).toLowerCase().includes(q)).map(x=>({id:x.id,kind,type,title:x.name||x.title,goalId:x.goalId,area:data.lifeAreas.find(a=>a.id===x.lifeAreaId)?.name||'',archived:x.archived||x.status==='Archived'}))).slice(0,30)}

const title=(v,label='title')=>{if(typeof v!=='string'||!v.trim()||v.length>500)throw Error(`Enter a valid ${label}.`);return v.trim()};
const optional=(v,max=10000)=>{if(v===undefined||v===null)return '';if(typeof v!=='string'||v.length>max)throw Error('Invalid text.');return v};
const civil=v=>{if(!v)return '';if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)throw Error('Enter a valid date.');return v};
const finite=v=>{if(typeof v!=='number'||!Number.isFinite(v))throw Error('Enter a finite numeric value.');return v};
function validateGoal(g,data){title(g.name);if(!['outcome','ongoing'].includes(g.type))throw Error('Choose Outcome or Ongoing.');if(!GOAL_STATUSES.includes(g.status))throw Error('Invalid goal status.');if(!['automatic','numeric','manual'].includes(g.progressMethod))throw Error('Invalid progress method.');if(g.lifeAreaId&&!data.lifeAreas.some(x=>x.id===g.lifeAreaId))throw Error('Choose an area in this profile.');civil(g.startDate);civil(g.targetDate);if(!['Low','Medium','High'].includes(g.priority))throw Error('Invalid priority.');optional(g.description);if(g.progressMethod==='manual'&&(finite(g.manualProgress)<0||g.manualProgress>100))throw Error('Progress must be between 0 and 100.');if(g.progressMethod==='numeric'&&g.numeric){finite(g.numeric.current);finite(g.numeric.target);finite(g.numeric.start??0);if(g.numeric.target===(g.numeric.start??0))throw Error('Target must differ from the starting value.');optional(g.numeric.unit,40)}}
export function planGoalAction(services,context,request){const action=request.action;if(!/^(area|goal|objective|milestone|focus)\./.test(action)&&action!=='work.link'&&action!=='goals.get'&&action!=='goals.search')return null;
 const data=goalData(services,context),now=services.now(),preferences=services.storage.profile.preferences||{},today=dayInZone(now,profileZone(preferences)),options={now,preferences},changes={},result={},uuid=services.uuid;let risk='low-risk-write';
 const put=key=>changes['lifeos4.'+key]=JSON.stringify(data[key]);
 const find=(key,id)=>{const record=data[key].find(x=>x.id===id);if(!record)throw Error('Choose an item in this profile.');return record};
 const parent=(goalId,objectiveId)=>{const o=objectiveId?find('objectives',objectiveId):null,g=find('goals',o?.goalId||goalId);if(goalId&&g.id!==goalId)throw Error('Objective belongs to another goal.');return {g,o}};
 const history=(goalId,label,extra={})=>{data.goalActivity.push({id:uuid(),goalId,timestamp:stamp(now),label,...extra});put('goalActivity')};
 const patch=(record,allowed)=>{if(!request.patch||Object.keys(request.patch).some(k=>!allowed.includes(k)))throw Error('Invalid changes.');Object.assign(record,structuredClone(request.patch))};
 if(action==='goals.get')return {risk:'safe-read',changes,result:{goals:prioritizedGoals(data,options)}};
 if(action==='goals.search')return {risk:'safe-read',changes,result:{matches:goalSearch(data,request.query)}};
 if(action==='goal.progress'&&!request.id)return {risk:'safe-read',changes,result:{goals:data.goals.map(g=>({id:g.id,name:g.name,...goalProgress(data,g)}))}};
 if(action==='focus.get')return {risk:'safe-read',changes,result:{focus:focusForWeek(data,today,preferences.weekStart??1),week:weekKey(today,preferences.weekStart??1)}};
 if(['area.get','goal.get','goal.progress','goal.time'].includes(action)){const item=action==='area.get'?areaSummary(data,find('lifeAreas',request.id),options):action==='goal.time'?goalTime(data,request.id,{...options,objectiveId:request.objectiveId}):action==='goal.progress'?goalProgress(data,find('goals',request.id)):goalSummary(data,find('goals',request.id),options);if(action==='goal.time'){find('goals',request.id);if(request.objectiveId&&find('objectives',request.objectiveId).goalId!==request.id)throw Error('Objective belongs to another goal.');}return {risk:'safe-read',changes,result:{[action==='goal.time'?'time':action==='goal.progress'?'progress':'detail']:item,kind:action.split('.')[0]}}}
 if(['goal.draft','objective.draft','area.draft'].includes(action))return {risk:'safe-read',changes,result:{draft:true,kind:action.split('.')[0],goalId:request.goalId||null}};
 if(action==='area.create'){const item={id:uuid(),name:title(request.name),icon:request.icon||'◎',accent:request.accent||'#50bc88',vision:optional(request.vision),order:data.lifeAreas.length,archived:false};if(!/^#[\da-f]{6}$/i.test(item.accent)||item.icon.length>12)throw Error('Invalid area appearance.');data.lifeAreas.push(item);put('lifeAreas');result.item=item;}
 else if(['area.update','area.archive','area.reorder','area.delete'].includes(action)){const a=find('lifeAreas',request.id);if(action==='area.delete'){if(!a.archived||data.goals.some(g=>g.lifeAreaId===a.id)||data.goalRelatedAreas.some(x=>x.areaId===a.id)||data.lifeAreaCheckins.some(x=>x.lifeAreaId===a.id))throw Error('Archive this area to preserve its references. Permanent deletion is only available for an empty archived area.');data.lifeAreas=data.lifeAreas.filter(x=>x.id!==a.id);risk='always-confirm';}
  else if(action==='area.archive')a.archived=request.archived??true;else if(action==='area.reorder'){if(!Array.isArray(request.ids)||new Set(request.ids).size!==data.lifeAreas.length||request.ids.some(id=>!data.lifeAreas.some(x=>x.id===id)))throw Error('Reorder must include every area once.');request.ids.forEach((id,i)=>find('lifeAreas',id).order=i);}
  else{patch(a,['name','icon','accent','vision']);a.name=title(a.name);optional(a.vision);if(!/^#[\da-f]{6}$/i.test(a.accent||'#50bc88')||optional(a.icon,12).length>12)throw Error('Invalid area appearance.');}put('lifeAreas');result.item=a;}
 else if(action==='area.checkin'){find('lifeAreas',request.id);if(!Number.isInteger(request.rating)||request.rating<1||request.rating>5)throw Error('Choose a rating from 1 to 5.');const item={id:uuid(),lifeAreaId:request.id,date:today,timestamp:stamp(now),rating:request.rating,note:optional(request.note)};data.lifeAreaCheckins.push(item);put('lifeAreaCheckins');result.item=item;}
 else if(action==='goal.create'){const area=find('lifeAreas',request.lifeAreaId);if(area.archived)throw Error('Choose an active area.');const item={id:uuid(),name:title(request.name),type:request.type||'outcome',lifeAreaId:area.id,status:'Not Started',progressMethod:'automatic',manualProgress:0,startDate:today,targetDate:'',priority:'Medium',description:'',createdAt:stamp(now)};validateGoal(item,data);data.goals.push(item);put('goals');history(item.id,'Goal created');result.item=item;}
 else if(['goal.update','goal.archive','goal.pause','goal.complete','goal.delete'].includes(action)){let g=find('goals',request.id);Object.assign(g,goalView(g));const previous=structuredClone(g);if(action==='goal.delete'){const linked=data.objectives.some(x=>x.goalId===g.id)||data.goalActionLinks.some(x=>x.goalId===g.id)||data.workSessions.some(x=>x.goalId===g.id)||data.goalMilestones.some(x=>x.goalId===g.id)||data.notes.some(x=>x.goalId===g.id)||data.goalActivity.some(x=>x.goalId===g.id)||data.history.some(x=>x.goalId===g.id||x.contributions?.some(c=>c.goalId===g.id));if(g.status!=='Archived'||linked)throw Error('Archive this goal to keep its history. Permanent deletion requires an empty archived goal.');data.goals=data.goals.filter(x=>x.id!==g.id);risk='always-confirm';}
  else{if(action==='goal.update')patch(g,['name','type','description','lifeAreaId','status','startDate','targetDate','priority','progressMethod','manualProgress','numeric']);else g.status=action==='goal.archive'?'Archived':action==='goal.pause'?'Paused':'Completed';validateGoal(g,data);if(g.lifeAreaId!==previous.lifeAreaId){data.goalRelatedAreas=data.goalRelatedAreas.filter(x=>!(x.goalId===g.id&&x.areaId===g.lifeAreaId));put('goalRelatedAreas');}if(g.status!==previous.status)history(g.id,`Status changed: ${previous.status} → ${g.status}`);else if(g.progressMethod!==previous.progressMethod||g.manualProgress!==previous.manualProgress||JSON.stringify(g.numeric)!==JSON.stringify(previous.numeric))history(g.id,'Progress updated');else history(g.id,'Goal updated');}put('goals');result.item=g;}
 else if(['objective.create','objective.update','objective.complete','objective.archive'].includes(action)){let o;if(action==='objective.create'){const g=find('goals',request.goalId);if(goalView(g).status==='Archived')throw Error('Restore the archived goal before adding an objective.');o={id:uuid(),goalId:g.id,name:title(request.name),description:'',status:'Not Started',targetDate:civil(request.targetDate),createdAt:stamp(now)};data.objectives.push(o);history(g.id,`Objective created: ${o.name}`,{objectiveId:o.id});}
  else{o=find('objectives',request.id);if(action==='objective.update')patch(o,['name','description','status','targetDate']);else o.status=action==='objective.complete'?'Completed':'Archived';title(o.name);optional(o.description);civil(o.targetDate);if(!GOAL_STATUSES.includes(o.status))throw Error('Invalid objective status.');history(o.goalId,`Objective ${o.status==='Completed'?'completed':'updated'}: ${o.name}`,{objectiveId:o.id});}put('objectives');result.item=o;}
 else if(action==='goal.related'){find('goals',request.id);if(!Array.isArray(request.areaIds)||new Set(request.areaIds).size!==request.areaIds.length)throw Error('Choose distinct related areas.');const primary=find('goals',request.id).lifeAreaId;for(const id of request.areaIds){find('lifeAreas',id);if(id===primary)throw Error('Primary area is already counted.');}data.goalRelatedAreas=data.goalRelatedAreas.filter(x=>x.goalId!==request.id);data.goalRelatedAreas.push(...request.areaIds.map(areaId=>({id:uuid(),goalId:request.id,areaId})));put('goalRelatedAreas');history(request.id,'Related areas updated');result.item=find('goals',request.id);}
 else if(['goal.action.link','goal.action.unlink','goal.action.create'].includes(action)){const {g,o}=parent(request.goalId,request.objectiveId);const key={task:'tasks',routine:'routines',habit:'habits'}[request.kind];if(!key)throw Error('Choose Task, Routine or Habit.');let record;
  if(action==='goal.action.create'){const name=title(request.title||request.name);record=request.kind==='task'?{id:uuid(),title:name,desc:'',status:'upcoming',date:civil(request.date),time:'',priority:'Medium',createdAt:stamp(now)}:request.kind==='routine'?{id:uuid(),name,icon:'↻',active:true,days:request.days||['mon','tue','wed','thu','fri'],time:'',duration:10,start:'',end:'',steps:[{name,mode:'duration',minutes:10}]}:{id:uuid(),name,active:true,createdAt:stamp(now)};data[key].push(record);put(key);}else record=find(key,request.actionId);
  if(action==='goal.action.unlink')data.goalActionLinks=data.goalActionLinks.filter(x=>!(x.goalId===g.id&&x.kind===request.kind&&x.actionId===record.id));else{if(request.includeProgress&&request.kind==='habit'&&!(Number.isInteger(request.targetCount)&&request.targetCount>0))throw Error('Set a habit completion target before counting it in progress.');if(request.includeProgress&&request.kind==='routine'&&!civil(request.occurrenceDate))throw Error('Choose a single routine occurrence for progress.');data.goalActionLinks=data.goalActionLinks.filter(x=>!(x.goalId===g.id&&x.kind===request.kind&&x.actionId===record.id));data.goalActionLinks.push({id:uuid(),goalId:g.id,objectiveId:o?.id||null,kind:request.kind,actionId:record.id,includeProgress:request.kind==='task'||request.includeProgress===true,targetCount:request.targetCount||null,occurrenceDate:request.occurrenceDate||null,sinceDate:today,createdAt:stamp(now)});}put('goalActionLinks');history(g.id,`${action==='goal.action.unlink'?'Unlinked':'Linked'} ${request.kind}: ${record.title||record.name}`,{objectiveId:o?.id||null});result.item=record;}
 else if(action==='work.link'){const {g,o}=parent(request.goalId,request.objectiveId),s=find('workSessions',request.id);s.goalId=g.id;s.objectiveId=o?.id||null;put('workSessions');history(g.id,'Work session linked',{objectiveId:o?.id||null});result.item=s;}
 else if(['milestone.create','milestone.update','milestone.complete'].includes(action)){let m;if(action==='milestone.create'){find('goals',request.goalId);m={id:uuid(),goalId:request.goalId,title:title(request.title),targetDate:civil(request.targetDate),completed:false,achievedDate:'',createdAt:stamp(now)};data.goalMilestones.push(m);}else{m=find('goalMilestones',request.id);if(action==='milestone.update')patch(m,['title','targetDate','completed','achievedDate']);else{m.completed=true;m.achievedDate=today;}title(m.title);civil(m.targetDate);civil(m.achievedDate);if(typeof m.completed!=='boolean')throw Error('Invalid milestone completion.');if(m.completed&&!m.achievedDate)m.achievedDate=today;}put('goalMilestones');history(m.goalId,`Milestone ${m.completed?'completed':'saved'}: ${m.title}`);result.item=m;}
 else if(['focus.set','focus.remove','focus.continue','focus.done'].includes(action)){let item;if(action==='focus.set'){if(!['goal','objective'].includes(request.kind))throw Error('Focus must be a Goal or Objective.');const target=find(request.kind==='goal'?'goals':'objectives',request.targetId),goalId=request.kind==='goal'?target.id:target.goalId;if(!active(goalView(find('goals',goalId)))||['Completed','Archived'].includes(target.status))throw Error('Choose an active goal or objective.');const focusDate=civil(request.date)||today,week=weekKey(focusDate,preferences.weekStart??1),existing=data.weeklyFocus.find(x=>x.week===week&&x.kind===request.kind&&x.targetId===target.id&&x.state==='active');if(week<weekKey(today,preferences.weekStart??1))throw Error('Choose the current or an upcoming Focus period; historical selections cannot be invented.');if(existing)return {risk,changes,result:{item:existing}};if(focusForWeek(data,focusDate,preferences.weekStart??1).length>=3)throw Error('Keep this week focused: remove or finish an item before adding another.');item={id:uuid(),week,weekStart:preferences.weekStart??1,timezone:profileZone(preferences),periodStart:new Date(dayBounds(week,profileZone(preferences)).start).toISOString(),periodEnd:new Date(dayBounds(shiftDay(week,7),profileZone(preferences)).start).toISOString(),kind:request.kind,targetId:target.id,goalId,state:'active',createdAt:stamp(now)};data.weeklyFocus.push(item);history(goalId,'Weekly Focus added',{week});}
  else{item=find('weeklyFocus',request.id);if(action==='focus.continue'){const plan=planGoalAction(services,context,{action:'focus.set',kind:item.kind,targetId:item.targetId,date:request.date});return plan;}item.state=action==='focus.done'?'done':'removed';history(item.goalId,`Weekly Focus ${item.state}`,{week:item.week});}put('weeklyFocus');result.item=item;}
 else if(['goal.note.create','goal.note.update'].includes(action)){const {g,o}=parent(request.goalId,request.objectiveId);let n;if(action==='goal.note.create'){n={id:uuid(),goalId:g.id,objectiveId:o?.id||null,title:title(request.title||'Goal note'),body:optional(request.body),updated:now};data.notes.push(n);}else{n=find('notes',request.id);if(n.goalId!==g.id)throw Error('Note belongs to another goal.');patch(n,['title','body']);title(n.title);optional(n.body);n.updated=now;}put('notes');result.item=n;}
 else throw Error('Unknown goal action.');
 const before=Object.fromEntries(Object.keys(changes).map(key=>[key,services.storage.getItem(key)]));return {risk,changes,before,result};
}
