import {dayInZone,profileZone,shiftDay,dayBounds,clockInZone,civilInstant} from './date-time.js';
import {routineItems,sessionDuration} from './life-tracking.js';
import {habitDue,habitDayStatus} from './habits-trackers.js';

export const NOTIFICATION_DEFAULTS=Object.freeze({enabled:true,sound:true,volume:0.35,chime:'soft',calendarAdvance:15,calendar:true,tasks:true,routines:true,deadlines:true,habits:false,finance:true,work:true,reviews:false,weeklyReviews:false,breakMinutes:0,sessionMinutes:0,quietStart:'22:00',quietEnd:'08:00',quietEnabled:false,priorityRepeats:0,repeatMinutes:10,privateContent:false});
export function notificationPreferences(value={}){return {...NOTIFICATION_DEFAULTS,...value}}
// Recurrent automatic reminders choose the earlier fold and the first valid minute after a gap.
// User-entered schedules retain civilInstant's explicit disambiguation requirements.
const instantCache=new Map();
export function reminderInstant(day,time,zone){const key=[day,time,zone].join('|');if(instantCache.has(key))return instantCache.get(key);let result;try{result=Date.parse(civilInstant(day,time,zone,'earlier'))}catch(error){if(!error.message.includes('does not exist'))throw error;const bounds=dayBounds(day,zone);for(let t=bounds.start;t<bounds.end;t+=60000)if(clockInZone(t,zone)>=time){result=t;break}}if(!Number.isFinite(result))throw Error('No valid reminder time on this date.');if(instantCache.size>3000)instantCache.clear();instantCache.set(key,result);return result}
export function quietAt(now,prefs,zone){if(!prefs.quietEnabled)return false;const clock=clockInZone(now,zone),a=prefs.quietStart,b=prefs.quietEnd;return a===b|| (a<b?clock>=a&&clock<b:clock>=a||clock<b)}
// Lossless UTF-8 hex identity avoids hash collisions and is accepted by existing record IDs.
export function occurrenceId(profileId,kind,id,occurrence,reminder,version){return 'n-'+[...new TextEncoder().encode(JSON.stringify([profileId,kind,id,occurrence,reminder,version]))].map(x=>x.toString(16).padStart(2,'0')).join('')}
export function notificationData(services,context){services.context(context);return {...services.trackingData(context),financeBills:services.read(context,'lifeos4.financeBills',[]),dailyReviews:services.read(context,'lifeos4.dailyReviews',[]),weeklyReviews:services.read(context,'lifeos4.weeklyReviews',[]),notificationStates:services.read(context,'lifeos4.notificationStates',[]),notificationOverrides:services.read(context,'lifeos4.notificationOverrides',[]),weekStart:services.storage.profile.preferences?.weekStart,preferences:notificationPreferences(services.read(context,'lifeos4.notificationPreferences',{}))}}
export function reminderCandidates(data,{profileId,zone,now=Date.now(),pastDays=7,futureDays=7}){
 if(!profileId)throw Error('Explicit profile required.');const prefs=notificationPreferences(data.preferences),today=dayInZone(now,zone),days=Array.from({length:pastDays+futureDays+1},(_,i)=>shiftDay(today,i-pastDays)),result=[];
 const add=(kind,row,day,time,reminder,offset=0,end=null,urgency='standard',extra={})=>{
  if(!row.id||!day||!time)return;const override=(data.notificationOverrides||[]).find(x=>x.kind===kind&&x.sourceId===row.id)||{};if(override.enabled===false)return;
  const start=reminderInstant(day,time,zone),due=start-offset*60000,version=JSON.stringify([day,time,zone,offset,extra.version||'',override.urgency||urgency,override.enabled]),id=occurrenceId(profileId,kind,row.id,day,reminder,version);
  result.push({id,profileId,kind,sourceId:row.id,occurrence:day,reminder,version,title:row.title||row.name||'Reminder',due,start,end:end??start+3600000,urgency:override.urgency||urgency,offset,...extra});
 };
 for(const row of data.tasks||[]){if(['completed','archived'].includes(row.status))continue;const o=(data.notificationOverrides||[]).find(x=>x.kind==='task'&&x.sourceId===row.id)||{};if(prefs.tasks&&row.date&&row.time)add('task',row,row.date,row.time,'start',o.advance??0,null,'standard',{version:row.duration||0});const deadline=row.deadline||row.dueDate;if(prefs.deadlines&&deadline){const date=deadline.slice(0,10),time=deadline.slice(11,16)||row.deadlineTime||'09:00';add('task',row,date,time,'deadline',o.deadlineAdvance??0,Infinity,'standard')}}
 if(prefs.calendar)for(const row of data.events||[]){if(row.archived||row.cancelled||!row.time)continue;const o=(data.notificationOverrides||[]).find(x=>x.kind==='event'&&x.sourceId===row.id)||{};add('event',row,row.date,row.time,'advance',o.advance??prefs.calendarAdvance,reminderInstant(row.date,row.time,zone)+Math.max(1,Number(row.duration)||30)*60000,'standard',{version:row.duration||30})}
 for(const day of days){
  if(prefs.routines){const steps=routineItems(data,day);for(const row of data.routines||[]){const own=steps.filter(s=>s.sourceId===row.id);if(!own.length||own.every(s=>s.completed))continue;const first=own.find(s=>s.time);if(first)add('routine',row,day,row.time||first.time,'start',0,dayBounds(day,zone).end,'standard',{version:own.map(s=>[s.time,s.duration,s.title])})}}
  if(prefs.habits)for(const row of data.habits||[]){const o=(data.notificationOverrides||[]).find(x=>x.kind==='habit'&&x.sourceId===row.id);if(!o?.time||!habitDue(data,row,day)||['TARGET_MET','SKIPPED'].includes(habitDayStatus(data,row,day,{zone}).state)||['weekly','monthly'].includes(row.schedule?.kind))continue;add('habit',row,day,o.time,'optional',0,dayBounds(day,zone).end,'informational')}
  if(prefs.reviews&&day===today&&!data.dailyReviews?.some(r=>r.localDate===day&&r.status==='COMPLETED'))add('review',{id:'daily',title:'Daily Review is available'},day,'19:00','optional',0,dayBounds(day,zone).end,'informational');
  if(prefs.weeklyReviews&&day===today&&new Date(day+'T12:00Z').getUTCDay()===((data.weekStart??1)+6)%7&&!data.weeklyReviews?.some(r=>r.endDate===shiftDay(day,1)&&r.status==='COMPLETED'))add('review',{id:'weekly',title:'Weekly Review is available'},day,'18:00','optional',0,dayBounds(day,zone).end,'informational');
 }
 if(prefs.finance)for(const row of data.financeBills||[]){if(row.paid===true||row.archived||row.needsReview)continue;const day=row.due||row.dueDate;if(/^\d{4}-\d{2}-\d{2}$/.test(day||''))add('bill',row,day,'09:00','due',0,Infinity,'standard')}
 if(prefs.work)for(const row of data.workSessions||[]){if(row.status!=='running')continue;const last=row.segments?.at(-1);if(!last||last.end)continue;for(const [reminder,minutes] of [['break',prefs.breakMinutes],['session-end',prefs.sessionMinutes]])if(minutes>0){const settled=sessionDuration({...row,segments:row.segments.filter(s=>s.end)},now),due=Date.parse(last.start)+Math.max(0,minutes*60000-settled),day=dayInZone(due,zone),version=JSON.stringify([minutes,zone]);result.push({id:occurrenceId(profileId,'work',row.id,row.startedAt||row.segments[0].start,reminder,version),profileId,kind:'work',sourceId:row.id,title:row.title||'Work session',occurrence:day,reminder,version,due,start:due,end:Infinity,urgency:'standard'})}}
 return result.filter(x=>Number.isFinite(x.due)&&x.occurrence<=shiftDay(today,futureDays)&& (x.occurrence>=shiftDay(today,-pastDays)||['task','bill'].includes(x.kind))).map(x=>({...x,end:Number.isFinite(x.end)?x.end:253402300799000})).sort((a,b)=>a.due-b.due);
}
export function attention(candidates,states,now){const map=new Map(states.map(x=>[x.id,x])),needs=[],upcoming=[],snoozed=[];for(const item of candidates){const raw=map.get(item.id)||{},state=raw.snoozeUntil?{...raw,snoozeUntil:Math.max(raw.snoozeUntil,item.due)}:raw,entry={...item,state};if(item.end<now&& !['task','bill','work'].includes(item.kind))continue;if(state.snoozeUntil>now)snoozed.push(entry);else if(item.due>now)upcoming.push(entry);else needs.push(entry)}return {needs,upcoming,snoozed,badge:new Set(needs.filter(x=>x.urgency!=='informational').map(x=>x.kind+':'+x.sourceId)).size}}
export function currentCommitments(data,{zone,now=Date.now()}){const day=dayInZone(now,zone),timed=[];for(const [kind,rows] of [['task',data.tasks||[]],['event',data.events||[]]])for(const x of rows)if(x.date===day&&x.time&&!['completed','archived'].includes(x.status)&&!x.cancelled){const start=reminderInstant(day,x.time,zone);timed.push({...x,kind,sourceId:x.id,start,end:start+(Number(x.duration)||30)*60000})}for(const r of data.routines||[]){const steps=routineItems(data,day).filter(x=>x.sourceId===r.id);if(!steps.length||steps.every(x=>x.completed))continue;const first=steps.find(x=>x.time);if(first){const start=reminderInstant(day,r.time||first.time,zone);timed.push({...r,title:r.name,kind:'routine',sourceId:r.id,start,end:start+steps.reduce((n,x)=>n+x.duration,0)*60000})}}let current=timed.filter(x=>x.start<=now&&x.end>now);for(const s of data.workSessions||[])if(s.status==='running'){const planned=current.find(x=>x.kind==='task'&&x.sourceId===s.taskId);if(planned)current=current.filter(x=>x!==planned);current.unshift({...s,plannedStart:planned?.start,plannedEnd:planned?.end,title:s.title||'Work session',sourceId:s.id,kind:'work',start:Date.parse(s.segments.at(-1)?.start),end:null})}return {current,next:timed.filter(x=>x.start>now).sort((a,b)=>a.start-b.start).slice(0,3)}}
export function planNotificationAction(services,context,request){if(!request.action.startsWith('notification.'))return null;const data=notificationData(services,context),now=services.now(),zone=profileZone(services.storage.profile.preferences),candidates=reminderCandidates(data,{profileId:context.profileId,zone,now}),changes={},result={};let risk='low-risk-write';
 if(request.action==='notification.get')return {risk:'safe-read',changes,result:{attention:attention(candidates,data.notificationStates,now)}};
 if(request.action==='notification.current')return {risk:'safe-read',changes,result:{commitments:currentCommitments(data,{zone,now})}};
 if(request.action==='notification.open')return {risk:'safe-read',changes,result:{attention:attention(candidates,data.notificationStates,now),openAttention:true}};
 if(request.action==='notification.preferences'){const patch=request.patch;if(!patch||Object.keys(patch).some(k=>!(k in NOTIFICATION_DEFAULTS)))throw Error('Invalid notification preferences.');const p={...data.preferences,...patch};for(const key of ['enabled','sound','calendar','weeklyReviews','tasks','routines','deadlines','habits','finance','work','reviews','quietEnabled','privateContent'])if(typeof p[key]!=='boolean')throw Error('Choose an enabled or disabled preference.');for(const [key,min,max] of [['volume',0,1],['calendarAdvance',0,1440],['breakMinutes',0,1440],['sessionMinutes',0,1440],['priorityRepeats',0,3],['repeatMinutes',5,120]])if(!Number.isFinite(p[key])||p[key]<min||p[key]>max)throw Error('Invalid '+key);if(!['soft','clear'].includes(p.chime)||![p.quietStart,p.quietEnd].every(x=>/^([01]\d|2[0-3]):[0-5]\d$/.test(x)))throw Error('Choose a valid chime and quiet hours.');changes['lifeos4.notificationPreferences']=JSON.stringify(p);result.preferences=p;
 }else if(request.action==='notification.override'){if(!['task','event','routine','habit','bill'].includes(request.kind))throw Error('Unsupported reminder source.');const collection={task:'tasks',event:'events',routine:'routines',habit:'habits',bill:'financeBills'}[request.kind];if(!data[collection].some(x=>x.id===request.sourceId))throw Error('Choose a source in this profile.');const patch=request.patch||{};if(Object.keys(patch).some(x=>!['enabled','advance','deadlineAdvance','urgency','time'].includes(x))||patch.urgency&&!['informational','standard','priority'].includes(patch.urgency)||patch.enabled!==undefined&&typeof patch.enabled!=='boolean'||['advance','deadlineAdvance'].some(x=>patch[x]!==undefined&&(!Number.isFinite(patch[x])||patch[x]<0||patch[x]>1440))||patch.time!==undefined&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(patch.time))throw Error('Invalid reminder override.');const rows=structuredClone(data.notificationOverrides),id=request.kind+'-'+request.sourceId,old=rows.find(x=>x.id===id);if(old)Object.assign(old,patch);else rows.push({id,kind:request.kind,sourceId:request.sourceId,...patch});changes['lifeos4.notificationOverrides']=JSON.stringify(rows);result.override=rows.find(x=>x.id===id);
 }else if(['notification.snooze','notification.dismiss'].includes(request.action)){const item=candidates.find(x=>x.id===request.id);if(!item)throw Error('That reminder is no longer relevant.');const rows=structuredClone(data.notificationStates);let row=rows.find(x=>x.id===item.id);if(!row){row={id:item.id,sourceId:item.sourceId,kind:item.kind,occurrence:item.occurrence,version:item.version};rows.push(row)}if(request.action.endsWith('snooze')){const until=request.until?Date.parse(request.until):Math.max(now,item.due)+(request.minutes??10)*60000;if(!Number.isFinite(until)||until<=Math.max(now,item.due)||until>Math.max(now,item.due)+30*86400000)throw Error('Choose a future snooze within 30 days.');row.snoozeUntil=until;row.dismissedAt=null}else{row.dismissedAt=now;row.snoozeUntil=null}row.updatedAt=now;changes['lifeos4.notificationStates']=JSON.stringify(rows);result.reminder={...item,state:row};
 }else throw Error('Unknown notification action.');return {risk,changes,before:Object.fromEntries(Object.keys(changes).map(k=>[k,services.storage.getItem(k)])),result};
}
