import {dayInZone,dayBounds,shiftDay,profileZone} from './date-time.js';
import {historyForDay,routineItems,sessionSlices} from './life-tracking.js';
import {validDay,habitDayStatus,habitSummary,trackerSummary,trackingWeekSummary} from './habits-trackers.js';
import {weekKey,goalData} from './goals.js';

export const REVIEW_COLLECTIONS=['dailyReviews','weeklyReviews','reviewAcknowledgements'];
export function reviewData(services,context){services.context(context);return {workTimeBaseline:services.workBaseline(context),...services.trackingData(context),...goalData(services,context),financeBills:services.read(context,'lifeos4.financeBills',[]),...Object.fromEntries(REVIEW_COLLECTIONS.map(k=>[k,services.read(context,'lifeos4.'+k,[])]))}}
export function reviewPeriod(kind,date,preferences={}){
 validDay(date);const timezone=profileZone(preferences),weekStart=preferences.weekStart??1;if(!Number.isInteger(weekStart)||weekStart<0||weekStart>6)throw Error('Invalid week start.');
 const startDate=kind==='weekly'?weekKey(date,weekStart):date,endDate=shiftDay(startDate,kind==='weekly'?7:1);
 return {kind,localDate:kind==='daily'?date:null,startDate,endDate,timezone,weekStart,periodStart:new Date(dayBounds(startDate,timezone).start).toISOString(),periodEnd:new Date(dayBounds(endDate,timezone).start).toISOString(),periodKey:kind==='daily'?date:[startDate,timezone,weekStart].join('|')};
}
export function daysOf(period){const days=[];for(let d=period.startDate;d<period.endDate;d=shiftDay(d,1))days.push(d);return days}
export function taskDeadline(task){return task.deadline||task.dueDate||''}
const unfinished=t=>!['completed','archived'].includes(t.status);
export function loopVersion(task,today){const due=taskDeadline(task);return JSON.stringify([task.date||'',task.time||'',due,task.priority||'Medium',due?(due<today?'overdue':due<=shiftDay(today,2)?'approaching':'later'):'none']);}
export function openLoops(data,period,today){return (data.tasks||[]).filter(unfinished).filter(t=>(t.date>=period.startDate&&t.date<period.endDate)||(taskDeadline(t)>=period.startDate&&taskDeadline(t)<period.endDate)||(taskDeadline(t)&&taskDeadline(t)<today&&t.priority==='High')).filter(t=>!(data.reviewAcknowledgements||[]).some(a=>a.sourceId===t.id&&a.version===loopVersion(t,today)&&a.action==='leave')).sort((a,b)=>Number(b.priority==='High')-Number(a.priority==='High')||(taskDeadline(a)||a.date||'').localeCompare(taskDeadline(b)||b.date||''));}
function taskFacts(data,period){const ids=new Set();for(const e of data.history||[])if(e.kind==='task'&&e.action==='completed'&&Date.parse(e.timestamp)>=Date.parse(period.periodStart)&&Date.parse(e.timestamp)<Date.parse(period.periodEnd))ids.add(e.sourceId);for(const t of data.tasks||[])if(t.completedAt&&Date.parse(t.completedAt)>=Date.parse(period.periodStart)&&Date.parse(t.completedAt)<Date.parse(period.periodEnd)&&t.status==='completed')ids.add(t.id);return ids.size;}
export function periodSummary(data,period,{now=Date.now()}={}){
 const days=daysOf(period),zone=period.timezone,today=dayInZone(now,zone),observed=days.filter(d=>d<=today),work=data.workSessions||[];
 const milliseconds=(data.workTimeBaseline?.entries||[]).filter(b=>b.date>=period.startDate&&b.date<period.endDate&&b.timeZone===zone).reduce((n,b)=>n+b.milliseconds,0)+observed.reduce((n,d)=>n+work.reduce((s,w)=>s+sessionSlices(w,d,zone,now).reduce((m,x)=>m+x.milliseconds,0),0),0);
 const transactions=(data.transactions||[]).filter(t=>t.date>=period.startDate&&t.date<period.endDate&&!t.internalTransfer),routines=[];
 for(const d of observed){const items=routineItems(data,d),keys=new Set(Object.entries(data.routineChecks||{}).filter(([key,value])=>key.startsWith(d+'|')&&value).map(([key])=>key)),last=new Map();for(const e of data.history||[])if(e.kind==='routine'&&e.date===d)last.set(e.sourceId,e);for(const [key,e] of last)if(e.action==='completed'&&data.routineChecks?.[key]===undefined)keys.add(key);if(items.length||keys.size)routines.push({date:d,total:items.length,completed:keys.size});}
 const habits=period.kind==='weekly'?trackingWeekSummary(data,observed.at(-1)||period.startDate,{zone,weekStart:period.weekStart}).habits.filter(h=>h.opportunities.some(x=>x.logged||x.state==='SKIPPED')||h.quota&&h.value>0): (data.habits||[]).map(h=>({habit:h,status:habitDayStatus(data,h,period.startDate,{zone})})).filter(h=>h.status.logged||h.status.state==='SKIPPED');
 const trackers=(data.trackers||[]).map(t=>{const s=trackerSummary(data,t,period.endDate>shiftDay(today,1)?today:shiftDay(period.endDate,-1),{zone,days:Math.max(1,observed.length)}),series=s.series.filter(x=>x.date>=period.startDate&&x.date<period.endDate),numbers=series.filter(x=>typeof x.value==='number'||typeof x.value==='boolean').map(x=>Number(x.value));return {...s,series,recordedDays:series.length,periodValue:t.aggregation==='total'?numbers.length?numbers.reduce((a,b)=>a+b,0):null:t.aggregation==='latest'?series.at(-1)?.value??null:numbers.length?numbers.reduce((a,b)=>a+b,0)/numbers.length:null};}).filter(t=>t.recordedDays);
 const focus=(data.weeklyFocus||[]).filter(f=>f.week===period.startDate&&(!f.timezone||f.timezone===zone)&& (f.weekStart??period.weekStart)===period.weekStart).map(f=>({...f,name:(f.kind==='goal'?data.goals:data.objectives)?.find(x=>x.id===f.targetId)?.name||'Earlier priority (record unavailable)'}));
 const goalActivity=(data.goalActivity||[]).filter(a=>Date.parse(a.timestamp)>=Date.parse(period.periodStart)&&Date.parse(a.timestamp)<Date.parse(period.periodEnd));
 return {period,tasksCompleted:taskFacts(data,period),milliseconds,routines,habits,trackers,transactions,spendingMinor:transactions.filter(t=>t.type==='expense').reduce((n,t)=>n+(t.amountMinor??Math.round(Number(t.amount)*100)),0),spending:transactions.filter(t=>t.type==='expense').reduce((n,t)=>n+(t.amountMinor??Math.round(Number(t.amount)*100)),0)/100,events:(data.events||[]).filter(e=>e.date>=period.startDate&&e.date<period.endDate),goalActivity,focus,focusKnown:focus.length>0,inProgress:now<Date.parse(period.periodEnd),loops:openLoops(data,period,today),hasRecordedActivity:!!(taskFacts(data,period)||milliseconds||transactions.length||habits.length||trackers.length||goalActivity.length||routines.some(r=>r.completed)||(data.events||[]).some(e=>e.date>=period.startDate&&e.date<period.endDate))};
}
export function suggestions(data,period,{now=Date.now()}={}){
 const today=dayInZone(now,period.timezone);if(period.kind!=='daily'||period.startDate<shiftDay(today,-1)||period.startDate>today)return [];
 const forDate=shiftDay(today,1),out=[],loops=openLoops(data,period,today);if(loops.length)out.push({kind:'tasks',forDate,text:`${loops.length} planned or due task${loops.length===1?' remains':'s remain'} unresolved.`,ids:loops.map(t=>t.id)});
 const events=(data.events||[]).filter(e=>e.date===forDate);if(events.length)out.push({kind:'events',forDate,text:`${events.length} appointment${events.length===1?'':'s'} recorded for ${forDate}${events.filter(e=>e.time).length?' · first at '+events.filter(e=>e.time).sort((a,b)=>a.time.localeCompare(b.time))[0].time:''}.`});
 const bills=(data.financeBills||[]).filter(b=>!b.paid&&!b.needsReview&&b.due===forDate);if(bills.length)out.push({kind:'bills',forDate,text:`${bills.length} recorded unpaid bill${bills.length===1?' is':'s are'} due ${forDate}.`});
 const focus=(data.weeklyFocus||[]).filter(f=>f.week===weekKey(today,period.weekStart)&&f.state==='active'),missing=focus.find(f=>!(data.goalActionLinks||[]).some(l=>l.goalId===f.goalId&&l.kind==='task'&&(data.tasks||[]).some(t=>t.id===l.actionId&&unfinished(t))));if(missing)out.push({kind:'focus',forDate,text:'A Weekly Focus priority has no linked next task.'});return out.slice(0,3);
}
export function reviewFor(data,kind,date,preferences){const p=reviewPeriod(kind,date,preferences);return data[kind==='daily'?'dailyReviews':'weeklyReviews'].find(r=>kind==='daily'?r.localDate===date:r.periodKey===p.periodKey)||null;}
const safeText=value=>{if(typeof value!=='string'||value.length>5000)throw Error('Use a reflection up to 5,000 characters.');return value};
export function planReviewAction(services,context,request){
 const a=request.action;if(!a.startsWith('review.')&&!a.startsWith('summary.'))return null;const data=reviewData(services,context),now=services.now(),preferences=services.storage.profile.preferences||{},today=dayInZone(now,profileZone(preferences)),stamp=new Date(now).toISOString(),changes={},result={},put=(key,v)=>{changes['lifeos4.'+key]=JSON.stringify(v)},kind=request.kind||'daily';if(!['daily','weekly'].includes(kind))throw Error('Choose Daily or Weekly.');const key=kind==='daily'?'dailyReviews':'weeklyReviews';
 let row=request.id?data[key].find(r=>r.id===request.id):reviewFor(data,kind,validDay(request.date||(request.offset?shiftDay(today,request.offset):today)),preferences);if(request.id&&!row)throw Error('Choose a review in this profile.');const period=row||reviewPeriod(kind,validDay(request.date||(request.offset?shiftDay(today,request.offset):today)),preferences);
 if(['summary.get','review.open','review.loops','review.list'].includes(a)){return {risk:'safe-read',changes,result:{review:row||null,summary:periodSummary(data,period,{now}),suggestions:suggestions(data,period,{now}),openReview:a==='review.open',reviews:a==='review.list'?[...data.dailyReviews,...data.weeklyReviews]:undefined}};}
 if(['review.start','review.save','review.complete','review.reopen'].includes(a)){
  if(!row){if(period.startDate>today)throw Error('A future review is not available yet.');row={...period,id:kind==='daily'?'daily-'+period.localDate:'weekly-'+[...period.periodKey].map(c=>c.charCodeAt(0).toString(16)).join(''),status:'IN_PROGRESS',reflection:'',createdAt:stamp,startedAt:stamp,updatedAt:stamp,completedAt:null};data[key].push(row);}
  if(request.reflection!==undefined)row.reflection=safeText(request.reflection);if(a==='review.complete'){row.status='COMPLETED';row.completedAt=stamp;row.firstCompletedAt??=stamp;}else if(a==='review.reopen')row.status='IN_PROGRESS';row.updatedAt=stamp;put(key,data[key]);result.review=row;result.openReview=true;
 }else if(a==='review.loop'){
  if(!['leave','tomorrow','nextWeek','backlog','date','complete'].includes(request.decision))throw Error('Choose a valid loose-end decision.');const task=data.tasks.find(t=>t.id===request.taskId);if(!task||!openLoops(data,period,today).some(t=>t.id===task.id))throw Error('That task is no longer a relevant loose end.');
  if(request.decision==='leave'){const acknowledgements=data.reviewAcknowledgements.filter(x=>!(x.sourceId===task.id&&x.version===loopVersion(task,today)));acknowledgements.push({id:services.uuid(),sourceId:task.id,version:loopVersion(task,today),action:'leave',periodKey:period.periodKey,createdAt:stamp});put('reviewAcknowledgements',acknowledgements);}
  else{const target=request.decision==='tomorrow'?shiftDay(today,1):request.decision==='nextWeek'?shiftDay(weekKey(today,preferences.weekStart??1),7):request.decision==='backlog'||request.decision==='complete'?'':validDay(request.targetDate);const delegated=services.plan(context,request.decision==='complete'?{action:'task.complete',id:task.id}:{action:'task.reschedule',id:task.id,date:target,time:task.time||''});Object.assign(changes,delegated.changes);result.item=delegated.result.item;}
 }else if(a==='review.checkin'){
  if(!data.trackerPins.some(p=>p.trackerId===request.trackerId))throw Error('Choose a pinned Tracker.');if(!request.submissionId||!/^[A-Za-z0-9_.:-]{1,100}$/.test(request.submissionId))throw Error('Missing check-in submission identity.');
  const existing=data.trackerEntries.find(e=>e.sourceReference===`review:${period.periodKey}:${request.submissionId}`);if(existing&&existing.trackerId!==request.trackerId)throw Error('Submission belongs to another Tracker.');if(existing)return {risk:'safe-read',changes,result:{item:existing}};
  if(period.startDate!==today&&!request.attributeToDate)throw Error('Confirm the measurement applies to this review date.');
  const timestamp=period.startDate===today?stamp:new Date(dayBounds(period.startDate,period.timezone).start+(dayBounds(period.startDate,period.timezone).end-dayBounds(period.startDate,period.timezone).start)/2).toISOString();
  const p=services.plan(context,{action:'tracker.log',id:request.trackerId,value:request.value,timestamp,source:'manual',sourceReference:`review:${period.periodKey}:${request.submissionId}`});const entries=JSON.parse(p.changes['lifeos4.trackerEntries']);const entry=entries.find(e=>e.id===p.result.item.id);Object.assign(entry,{recordedAt:stamp,appliesToDate:period.startDate,attributionTimezone:period.timezone,reviewPeriodKey:period.periodKey});put('trackerEntries',entries);result.item=entry;
 }else throw Error('Unknown Review action.');
 return {risk:'low-risk-write',changes,before:Object.fromEntries(Object.keys(changes).map(k=>[k,services.storage.getItem(k)])),result};
}
