import {planSearchAction,openSource} from './search.js';
import {planNotificationAction} from './notifications.js';
import {planReviewAction} from './reviews.js';
import {planTrackingAction,routineHabitChanges} from './tracking-actions.js';
import {planGoalAction} from './goals.js';
import {completionEvidence,workSessionChanges,dayInZone,dailyTimeline,historyForDay,recoveryItems,sessionSlices} from './life-tracking.js';
import {dayBounds,profileZone} from './date-time.js';
import {FINANCE_KEY,FINANCE_COLLECTIONS,financePlan,financeProjection,migrateFinance,validateFinance} from './finance.js';
export const Risk=Object.freeze({READ:'safe-read',WRITE:'low-risk-write',CONFIRM:'confirm',DESTRUCTIVE:'always-confirm'});
const copy=value=>structuredClone(value);
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])]));return value}
function sameRaw(a,b){if(a===b)return true;if(a===null||b===null)return false;try{return JSON.stringify(canonical(JSON.parse(a)))===JSON.stringify(canonical(JSON.parse(b)))}catch{return false}}
function auditAction(value){if(Array.isArray(value))return value.map(auditAction);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key])=>!/^(reasoning|chainOfThought|chain_of_thought|thoughts|analysis)$/i.test(key)).map(([key,item])=>[key,auditAction(item)]));return value}
const text=(value,label,max=500)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw Error(`Enter a valid ${label}.`);return value.trim()};
function date(value){if(value===''||value===undefined)return '';if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||new Date(value+'T12:00:00Z').toISOString().slice(0,10)!==value)throw Error('Enter a valid date.');return value}
function time(value){if(value===''||value===undefined)return '';if(typeof value!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))throw Error('Enter a valid time.');return value}
const number=(v,label,min=0)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min)throw Error(`Enter a valid ${label}.`);return v};
function validateRecords(key,records){
 if(!Array.isArray(records))throw Error('Expected a collection.');const ids=new Set();
 for(const record of records){if(!record||typeof record!=='object'||Array.isArray(record))throw Error('Invalid record.');
  if(!key.endsWith('routineExceptions')){if(typeof record.id!=='string'||!/^[A-Za-z0-9_.:-]+$/.test(record.id)||ids.has(record.id))throw Error('Invalid or duplicate record ID.');ids.add(record.id)}
  if(key==='lifeos4.tasks'){text(record.title,'task title');if(record.date)date(record.date);if(record.deadline)date(record.deadline);if(record.dueDate)date(record.dueDate);if(record.time)time(record.time);if(record.status&&!['today','upcoming','completed','archived'].includes(record.status))throw Error('Invalid task status.');}
  if(key==='lifeos4.events'){text(record.title,'event title');date(record.date);time(record.time);if(record.duration!==undefined)number(record.duration,'duration');}
  if(key==='lifeos4.transactions'){number(record.amount,'amount',0.01);if(!['expense','income'].includes(record.type))throw Error('Invalid transaction type.');date(record.date);}
 }
}
export function timerState(raw,now=Date.now(),zone){
 const day=dayInZone(now,zone),fresh={day,timeZone:zone||profileZone({}),elapsedMs:0,sessionMs:0,sessionCount:0,running:false,startedAt:null,targetHours:8};
 const state={...fresh,...(raw||{})};
 if(state.day!==day){const midnight=dayBounds(day,zone).start;return {...fresh,running:state.running&&Number.isFinite(state.startedAt),startedAt:state.running&&Number.isFinite(state.startedAt)?Math.max(midnight,state.startedAt):null}}
 return state;
}
export function timerTransition(raw,action,now=Date.now(),zone){
 let t=timerState(raw,now,zone);const settle=()=>{if(t.running&&t.startedAt!==null){const delta=Math.max(0,now-t.startedAt);t.elapsedMs+=delta;t.sessionMs+=delta;t.startedAt=null;t.running=false}};
 if(['start','resume'].includes(action)&&!t.running){t.running=true;t.startedAt=now}
 else if(action==='pause')settle();else if(action==='stop'){settle();if(t.sessionMs>0)t.sessionCount++;t.sessionMs=0}
 else if(action==='reset')t=timerState(null,now,zone);else if(!['start','resume'].includes(action))throw Error('Unknown timer action.');return t;
}

export class ApplicationServices {
 constructor(storage,{now=()=>Date.now(),uuid=()=>crypto.randomUUID(),navigate=()=>{},newTask=()=>{},newEvent=()=>{},refresh=()=>{}}={}){this.storage=storage;this.now=now;this.uuid=uuid;this.navigate=navigate;this.newTask=newTask;this.newEvent=newEvent;this.refresh=refresh;this.confirmations=new Map();}
 context(context){if(!context||context.profileId!==this.storage.profile.id)throw Error('This action belongs to another profile.');if(this.storage.failure)throw Error('Saving is paused. Export recovery data before continuing.');}
 read(context,key,fallback=null){this.context(context);const raw=this.storage.getItem(FINANCE_KEY);if(raw&&FINANCE_COLLECTIONS.includes(key.replace('lifeos4.','')))return copy(financeProjection(JSON.parse(raw),key.replace('lifeos4.',''),dayInZone(this.now(),profileZone(this.storage.profile.preferences))));const value=this.storage.getItem(key);return value===null?copy(fallback):JSON.parse(value)}
 initializeFinance(context){return this.coordinate(()=>this.initializeFinanceOrdered(context));}
 async initializeFinanceOrdered(context){this.context(context);await this.storage.flush();if(this.storage.getItem(FINANCE_KEY)){validateFinance(JSON.parse(this.storage.getItem(FINANCE_KEY)),context.profileId);return;}const data=Object.fromEntries(FINANCE_COLLECTIONS.map(k=>[k,this.read(context,'lifeos4.'+k,[])]));data.paydayDay=this.read(context,'lifeos4.paydayDay',null);const state=migrateFinance(this.storage.profile,data,this.now());await this.persistChanges(context,{[FINANCE_KEY]:JSON.stringify(state)},true);}
 applyUIChanges(context,changes,financeCommand=false){
  this.context(context);const before={};
  for(const [key,value] of Object.entries(changes)){
   if(key===FINANCE_KEY){if(!financeCommand||!this.financePermit||value===null)throw Error('Use an approved Finance command.');validateFinance(JSON.parse(value),context.profileId);}
   if(this.storage.getItem(FINANCE_KEY)&&FINANCE_COLLECTIONS.includes(key.replace('lifeos4.','')))throw Error('Legacy Finance is read-only. Use an approved Finance command.');
   if(!/^(lifeos4\.|domos612\.|domos_v)/.test(key))throw Error('Unsupported profile data key.');
   before[key]=this.storage.getItem(key);
   if(value!==null){if(typeof value!=='string')throw Error('Expected serialized profile data.');const parsed=JSON.parse(value);if(Array.isArray(parsed))validateRecords(key,parsed)}
  }
  changes={...changes};const evidence=this.trackingChanges(context,changes);Object.assign(changes,evidence);for(const key of Object.keys(evidence))before[key]=this.storage.getItem(key);
  try{for(const [key,value] of Object.entries(changes))value===null?this.storage.removeItem(key):this.storage.setItem(key,value);if(!financeCommand&&typeof window!=='undefined')window.dispatchEvent(new Event('domos-tracking-changed'))}
  catch(error){for(const [key,value] of Object.entries(before))value===null?this.storage.removeItem(key):this.storage.setItem(key,value);throw error}
 }
 trackingData(context){this.context(context);return Object.fromEntries(['tasks','events','routines','routineExceptions','routineChecks','history','workSessions','habits','habitLogs','habitPausePeriods','habitLinks','trackers','trackerPins','trackerEntries','transactions','reminders','goals','objectives','goalActionLinks'].map(name=>[name,this.read(context,'lifeos4.'+name,name==='routineChecks'?{}:[])]))}
 trackingChanges(context,changes){const before=this.trackingData(context),after={};const linked=routineHabitChanges(before,changes,{now:this.now(),uuid:this.uuid,zone:profileZone(this.storage.profile.preferences)});Object.assign(changes,linked);for(const name of ['tasks','routines','routineChecks','habitLogs'])if('lifeos4.'+name in changes)after[name]=changes['lifeos4.'+name]===null?(name==='routineChecks'?{}:[]):JSON.parse(changes['lifeos4.'+name]);const evidence=completionEvidence(before,after,{now:this.now(),uuid:this.uuid,zone:this.storage.profile.preferences?.timeZone});return {...linked,...(evidence.length?{'lifeos4.history':JSON.stringify([...before.history,...evidence])}:{})}}
 workBaseline(context){const saved=this.read(context,'lifeos4.workTimeBaseline');if(saved)return saved;const raw=this.read(context,'domos612.workTimer'),zone=raw?.timeZone||profileZone(this.storage.profile.preferences);if(!raw?.day)return {entries:[]};const settled=this.read(context,'lifeos4.workSessions',[]).reduce((n,s)=>n+sessionSlices({...s,segments:(s.segments||[]).filter(x=>x.end)},raw.day,zone,this.now()).reduce((m,x)=>m+x.milliseconds,0),0);return {entries:[{date:raw.day,timeZone:zone,milliseconds:Math.max(0,(raw.elapsedMs||0)-settled),sessionCount:Math.max(0,(raw.sessionCount||0)-this.read(context,'lifeos4.workSessions',[]).filter(s=>s.status==='stopped'&&sessionSlices(s,raw.day,zone,this.now()).length).length)}]}}
 timerSnapshot(context,counter=false){
  const now=this.now(),zone=profileZone(this.storage.profile.preferences),day=dayInZone(now,zone),raw=this.read(context,'domos612.workTimer'),sessions=this.read(context,'lifeos4.workSessions',[]),current=sessions.find(s=>['running','paused'].includes(s.status)),legacy=timerState(raw,now,zone);
  const reset=counter?Date.parse(this.read(context,'lifeos4.workCounterReset',{}).timestamp):NaN,cut=Number.isFinite(reset)&&reset>=dayBounds(day,zone).start?reset:null;
  const slices=session=>sessionSlices(session,day,zone,now).map(x=>({...x,milliseconds:Math.max(0,x.end-Math.max(x.start,cut??x.start))}));
  const baseline=cut===null?this.workBaseline(context).entries.filter(x=>x.date===day):[];
  const liveStart=current?.status==='running'?Date.parse(current.segments.at(-1)?.start):!current&&legacy.running?legacy.startedAt:null,startedAt=Number.isFinite(liveStart)?Math.max(dayBounds(day,zone).start,liveStart,cut??liveStart):null,live=startedAt===null?0:Math.max(0,now-startedAt);
  const total=sessions.reduce((n,s)=>n+slices(s).reduce((m,x)=>m+x.milliseconds,0),0)+baseline.reduce((n,x)=>n+x.milliseconds,0)+(!current&&legacy.running?live:0);
  const sessionMs=current?(current.segments||[]).reduce((n,s)=>n+Math.max(0,(s.end?Date.parse(s.end):now)-Date.parse(s.start)),0)-live:legacy.sessionMs;
  return {...legacy,day,timeZone:zone,elapsedMs:Math.max(0,total-live),sessionMs:Math.max(0,sessionMs||0),sessionCount:sessions.filter(s=>s.status==='stopped'&&slices(s).some(x=>x.milliseconds>0)).length+baseline.reduce((n,x)=>n+(x.sessionCount||0),0),running:startedAt!==null,startedAt,targetHours:raw?.targetHours||8,activeSessionId:current?.id||null,counterResetAt:cut};
 }
 plan(context,request){
  this.context(context);if(!request||typeof request.action!=='string')throw Error('Invalid action.');const fp=financePlan(this,context,request);if(fp)return fp;const searchPlan=planSearchAction(this,context,request);if(searchPlan)return searchPlan;const notificationPlan=planNotificationAction(this,context,request);if(notificationPlan)return notificationPlan;const reviewPlan=planReviewAction(this,context,request);if(reviewPlan)return reviewPlan;const trackingPlan=planTrackingAction(this,context,request);if(trackingPlan)return trackingPlan;const goalPlan=planGoalAction(this,context,request);if(goalPlan)return goalPlan;
  const changes={},action=request.action,now=this.now(),zone=profileZone(this.storage.profile.preferences),day=dayInZone(now,zone),get=(name,fallback=[])=>this.read(context,'lifeos4.'+name,fallback),put=(name,data)=>{changes['lifeos4.'+name]=JSON.stringify(data)},result={};let risk=Risk.WRITE;
  const edit=(collection)=>{const records=get(collection);const record=records.find(x=>x.id===request.id);if(!record)throw Error('That item is no longer available.');return {records,record}};
  if(action==='navigate'){if(!['dashboard','tasks','calendar','finances','routine','goals','notes','history','tracking'].includes(request.page))throw Error('Unknown page.');return {risk:Risk.READ,changes,result:{page:request.page}}}
  if(['task.draft','event.draft'].includes(action))return {risk:Risk.READ,changes,result:{draft:true,kind:action.split('.')[0]}};
  if(action==='today.get')return {risk:Risk.READ,changes,result:{date:day,tasks:get('tasks').filter(x=>x.status==='today'&&x.status!=='completed'),events:get('events').filter(x=>x.date===day)}};
  if(action==='schedule.get')return {risk:Risk.READ,changes,result:{date:date(request.date||day),events:get('events').filter(x=>x.date===(request.date||day))}};
  if(['timeline.get','history.get','recovery.get'].includes(action)){const selected=date(request.date||dayInZone(now,this.storage.profile.preferences?.timeZone)),data=this.trackingData(context),options={zone:this.storage.profile.preferences?.timeZone,now};return {risk:Risk.READ,changes,result:action==='timeline.get'?{date:selected,items:dailyTimeline(data,selected,options)}:action==='history.get'?historyForDay(data,selected,options):{items:recoveryItems(data,selected)}}}
  if(action==='work.totals'){const t=this.timerSnapshot(context);return {risk:Risk.READ,changes,result:{milliseconds:t.elapsedMs+(t.running&&t.startedAt!==null?Math.max(0,now-t.startedAt):0),sessionCount:t.sessionCount}}}
  if(action==='finance.summary'){const transactions=get('transactions').filter(x=>!x.internalTransfer);return {risk:Risk.READ,changes,result:{currency:this.storage.profile.preferences?.currency||'GBP',income:transactions.filter(x=>x.type==='income').reduce((sum,x)=>sum+x.amount,0),expenses:transactions.filter(x=>x.type==='expense').reduce((sum,x)=>sum+x.amount,0),accountBalance:get('financeAccounts').reduce((sum,x)=>sum+(Number(x.balance)||0),0)}}}
  if(action==='goal.progress')return {risk:Risk.READ,changes,result:{goals:get('goals').map(x=>({id:x.id,name:x.name,progress:x.progress||0}))}};
  if(action==='task.create'){const record={id:this.uuid(),title:text(request.title,'task title'),desc:request.description||'',status:request.status||'upcoming',priority:request.priority||'Medium',date:date(request.date),time:time(request.time),createdAt:new Date(now).toISOString(),...(request.deadline?{deadline:date(request.deadline)}:{})};put('tasks',[...get('tasks'),record]);result.item=record;}
  else if(['task.update','task.complete','task.reschedule','task.delete'].includes(action)){const {records,record}=edit('tasks');if(action==='task.delete'){put('goalActionLinks',get('goalActionLinks').filter(x=>!(x.kind==='task'&&x.actionId===record.id)));put('tasks',records.filter(x=>x.id!==record.id));risk=Risk.DESTRUCTIVE}else{const patch=action==='task.complete'?{status:'completed',completedAt:new Date(now).toISOString()}:action==='task.reschedule'?{date:date(request.date),time:time(request.time),status:request.date===day?'today':'upcoming'}:request.patch;if(!patch||Object.keys(patch).some(k=>!['title','desc','status','priority','date','time','completedAt','deadline'].includes(k)))throw Error('Invalid task changes.');Object.assign(record,patch);put('tasks',records)}result.item=record;}
  else if(['event.create','event.update','event.move','event.delete'].includes(action)){let records=get('events'),record;if(action==='event.create'){record={id:this.uuid(),title:text(request.title,'event title'),date:date(request.date||day),time:time(request.time),duration:number(request.duration??30,'duration'),type:'event'};records.push(record)}else{record=records.find(x=>x.id===request.id);if(!record)throw Error('That event is no longer available.');if(action==='event.delete'){records=records.filter(x=>x.id!==record.id);risk=Risk.DESTRUCTIVE}else{const patch=action==='event.move'?{date:date(request.date),time:time(request.time)}:request.patch;if(!patch||Object.keys(patch).some(k=>!['title','date','time','duration'].includes(k)))throw Error('Invalid event changes.');Object.assign(record,patch)}}put('events',records);result.item=record;}
  else if(action==='transaction.create'){const amount=number(request.amount,'amount',0.01),type=request.type||'expense';if(!['expense','income'].includes(type))throw Error('Choose expense or income.');const accountId=request.accountId||'';if(accountId&&!get('financeAccounts').some(x=>x.id===accountId))throw Error('Choose an account in this profile.');const record={id:this.uuid(),type,amount,description:text(request.description,'description'),category:request.category||'Other',date:date(request.date||day),accountId,internalTransfer:false};put('transactions',[...get('transactions'),record]);result.item=record;if(amount>=1000)risk=Risk.CONFIRM;}
  else if(action.startsWith('work.')){const operation=action.slice(5);if(!['start','resume','pause','stop','reset','log','correct'].includes(operation))throw Error('Unknown work action.');if(request.title!==undefined)text(request.title,'session name');for(const [field,collection] of [['taskId','tasks'],['goalId','goals'],['objectiveId','objectives']])if(request[field]&&!get(collection).some(x=>x.id===request[field]))throw Error('Choose linked records in this profile.');if(request.objectiveId){const objective=get('objectives').find(x=>x.id===request.objectiveId);if(request.goalId&&request.goalId!==objective.goalId)throw Error('Objective belongs to another goal.');request={...request,goalId:objective.goalId};}const raw=this.read(context,'domos612.workTimer');if(this.storage.getItem('lifeos4.workTimeBaseline')===null)put('workTimeBaseline',this.workBaseline(context));put('workSessions',workSessionChanges({workSessions:get('workSessions'),timer:raw},request,{now,uuid:this.uuid}));if(!['log','correct'].includes(operation)){changes['domos612.workTimer']=JSON.stringify(timerTransition(raw,operation,now,zone));result.timer=JSON.parse(changes['domos612.workTimer'])}else{result.item=operation==='correct'?JSON.parse(changes['lifeos4.workSessions']).find(s=>s.id===request.id):JSON.parse(changes['lifeos4.workSessions']).at(-1);const timer=timerState(raw,now,zone),milliseconds=sessionSlices(result.item,day,zone,now).reduce((n,s)=>n+s.milliseconds,0);if(operation==='log'){timer.elapsedMs+=milliseconds;if(milliseconds)timer.sessionCount++;changes['domos612.workTimer']=JSON.stringify(timer)}}if(operation==='reset'){changes['lifeos4.workCounterReset']=JSON.stringify({timestamp:new Date(now).toISOString()});risk=Risk.DESTRUCTIVE;}}
  else if(action==='routine.complete'){const checks=get('routineChecks',{});const routine=get('routines').find(x=>x.id===request.routineId);if(!routine||!routine.steps?.[request.stepIndex])throw Error('That routine step is no longer available.');const key=`${date(request.date||day)}|${routine.id}|${request.stepIndex}`;checks[key]=true;put('routineChecks',checks);result.name=routine.steps[request.stepIndex].name;}
  else if(action==='task.bulkReschedule'){if(!Array.isArray(request.ids)||request.ids.length<1||request.ids.length>100||new Set(request.ids).size!==request.ids.length)throw Error('Choose 1–100 distinct tasks.');const records=get('tasks');if(request.ids.some(id=>!records.some(x=>x.id===id)))throw Error('Choose tasks in this profile.');for(const record of records)if(request.ids.includes(record.id))Object.assign(record,{date:date(request.date),time:time(request.time),status:request.date===day?'today':'upcoming'});put('tasks',records);result.items=records.filter(x=>request.ids.includes(x.id));risk=Risk.CONFIRM;}
  else if(action==='record.delete'){if(request.collection==='goals')throw Error('Archive a goal to preserve its history.');if(!['notes','goals','routines','calendarTemplates','transactions','financeAccounts','financeBudgets','financeBills','financeSavings'].includes(request.collection))throw Error('Unsupported collection.');const {records,record}=edit(request.collection);if(request.collection==='routines'){put('habitLinks',get('habitLinks').filter(x=>x.routineId!==record.id));}if(request.collection==='routines')put('goalActionLinks',get('goalActionLinks').filter(x=>!(x.kind==='routine'&&x.actionId===record.id)));put(request.collection,records.filter(x=>x.id!==request.id));result.item=record;risk=Risk.DESTRUCTIVE;}
  else if(action==='habit.log'){const habit=get('habits').find(x=>x.id===request.id);if(!habit)throw Error('That habit is no longer available.');const record={id:this.uuid(),habitId:habit.id,timestamp:new Date(now).toISOString(),date:date(request.date||day),value:request.value??true};put('habitLogs',[...get('habitLogs'),record]);result.item=record;}
  else if(action==='tracker.log'){if(!get('trackers').some(x=>x.id===request.id))throw Error('That tracker is no longer available.');const record={id:this.uuid(),trackerId:request.id,date:date(request.date||day),value:number(request.value,'tracker value'),timestamp:new Date(now).toISOString()};put('trackerEntries',[...get('trackerEntries'),record]);result.item=record;}
  else if(['reminder.dismiss','reminder.snooze'].includes(action)){const {records,record}=edit('reminders');if(action==='reminder.dismiss')record.dismissed=true;else{record.date=date(request.date);if(!record.date)throw Error('Choose a reminder date.');record.time=time(request.time||record.time)}put('reminders',records);result.item=record;}
  else if(/^(goal|objective)\.(create|update)$/.test(action)){const collection=action.startsWith('goal.')?'goals':'objectives';let records=get(collection),record;if(action.endsWith('create')){record={id:this.uuid(),name:text(request.name,'name'),progress:number(request.progress??0,'progress'),goalId:request.goalId||null,lifeAreaId:request.lifeAreaId||null};records.push(record)}else{record=records.find(x=>x.id===request.id);if(!record)throw Error('That item is no longer available.');const patch=request.patch;if(!patch||Object.keys(patch).some(k=>!['name','progress','goalId','lifeAreaId'].includes(k)))throw Error('Invalid goal changes.');Object.assign(record,patch)}if(record.progress>100)throw Error('Progress must be between 0 and 100.');if(record.goalId&&!get('goals').some(x=>x.id===record.goalId))throw Error('Choose a goal in this profile.');if(record.lifeAreaId&&!get('lifeAreas').some(x=>x.id===record.lifeAreaId))throw Error('Choose a Life Area in this profile.');put(collection,records);result.item=record;}
  else throw Error('I’m not sure what you meant. Try “Show today” or “Start work”.');
  const before=Object.fromEntries(Object.keys(changes).map(key=>[key,this.storage.getItem(key)]));return {risk,changes,before,result};
 }
 audit(context,request,meta,outcome){const fields=new Set(['operationId','toAccountId','transactionId','anchor','frequency','weekend','horizon','basis','ruleId','externalReference','query','sourceId','minutes','action','id','ids','title','name','description','date','time','duration','status','priority','patch','amount','type','category','currency','accountId','routineId','stepIndex','value','goalId','lifeAreaId','progress','collection','page','source','sourceReference','timestamp','until','schedule','mode','direction','target','minimum','template','aggregation','days','objectiveId','actionId','kind','includeProgress','targetCount','occurrenceDate','areaIds','targetId','start','end','segments','targetDate','offset','reflection','kind','decision','taskId','trackerId','submissionId','attributeToDate','deadline','rating','note','numeric','type']);const parsedAction=Object.fromEntries(Object.entries(request).filter(([key])=>fields.has(key)).map(([key,value])=>[key,auditAction(value)]));return {id:this.uuid(),timestamp:new Date(this.now()).toISOString(),profileId:context.profileId,originalCommand:typeof meta.command==='string'?meta.command.slice(0,512):null,parsedAction,provider:meta.provider||'Local',confirmationRequirement:outcome.risk||Risk.READ,success:outcome.success,result:outcome.result||null,error:outcome.error||null}}
 performUI(context,request){const plan=this.plan(context,request);if(plan.financeCommand)throw Error('Finance writes require asynchronous, coordinated execution.');if([Risk.CONFIRM,Risk.DESTRUCTIVE].includes(plan.risk))throw Error('This action requires a confirmed preview.');this.applyUIChanges(context,plan.changes,plan.financeCommand);this.effects(request,plan.result);return plan.result}
 effects(request,result){if(typeof window!=='undefined'){if(result?.financeDraft){this.navigate('finances');if(result.financeDraft==='bills')window.DOMOSFinance?.openBill?.();else window.DOMOSFinance?.form?.(result.financeDraft);}if(result?.source)openSource(result.source,this);window.DOMOSNotifications?.handleResult?.(request,result);window.DOMOSReviews?.handleResult?.(request,result);window.DOMOSGoals?.handleResult?.(request,result);window.DOMOSHabitTracking?.handleResult?.(request,result);if(request.action.startsWith('finance.')||request.action==='transaction.create')window.DOMOSFinance?.render?.();}if(request.action==='navigate')this.navigate(result.page);else if(request.action==='today.get')this.navigate('dashboard');else if(request.action==='task.draft')this.newTask();else if(request.action==='event.draft')this.newEvent();else if(!['schedule.get','work.totals','finance.summary','goal.progress','timeline.get','history.get','recovery.get'].includes(request.action))this.refresh(request,result);}
 coordinate(operation){const pending=(this.storage.applicationMutationTail||Promise.resolve()).then(operation);this.storage.applicationMutationTail=pending.catch(()=>{});return pending;}
 execute(context,request,meta={}){return this.coordinate(()=>this.executeOrdered(context,request,meta));}
 async executeOrdered(context,request,meta={}){
  this.context(context);await this.storage.flush();if(meta.source==='assistant'&&['habit.log','tracker.log','transaction.create','finance.transaction.create'].includes(request.action))request={...request,source:'assistant'};let plan;
  try{plan=this.plan(context,request)}catch(error){await this.recordFailure(context,request,meta,error);throw error}
  if([Risk.CONFIRM,Risk.DESTRUCTIVE].includes(plan.risk)){const token=this.uuid();this.confirmations.set(token,{profileId:context.profileId,request:copy(request),meta:copy(meta),plan,expires:this.now()+300000});return {status:'confirmation-required',token,preview:{action:request.action,risk:plan.risk,result:plan.result,details:plan.confirmation}}}
  try{return await this.commitPlan(context,request,meta,plan)}catch(error){if(!this.storage.failure)await this.recordFailure(context,request,meta,error);throw error}
 }
 confirm(context,token){return this.coordinate(()=>this.confirmOrdered(context,token));}
 async confirmOrdered(context,token){this.context(context);const pending=this.confirmations.get(token);if(!pending||pending.profileId!==context.profileId||pending.expires<this.now())throw Error('This preview expired. Please try again.');this.confirmations.delete(token);await this.storage.flush();for(const [key,value] of Object.entries(pending.plan.before||{}))if(!sameRaw(this.storage.getItem(key),value))throw Error('This item changed since the preview. Please review it again.');if(pending.plan.financeCommand){const resolved=this.plan(context,pending.request);if(JSON.stringify(resolved.confirmation)!==JSON.stringify(pending.plan.confirmation))throw Error('The financial effect changed. Please review a new preview.');pending.plan=resolved;}return this.commitPlan(context,pending.request,pending.meta,pending.plan)}
 cancel(context,token){this.context(context);const pending=this.confirmations.get(token);if(pending?.profileId===context.profileId)this.confirmations.delete(token)}
 async persistChanges(context,changes,financeCommand=false){
  const before=Object.fromEntries(Object.keys(changes).map(k=>[k,this.storage.getItem(k)]));
  try{this.financePermit=!!financeCommand;try{this.applyUIChanges(context,changes,financeCommand)}finally{this.financePermit=false;}await this.storage.flush();}
  catch(error){if(financeCommand){this.storage.failedRecovery={format:'DOM.OS Unsaved Recovery',version:1,profile:copy(this.storage.profile),data:Object.fromEntries(this.storage.values)};for(const [key,value] of Object.entries(before)){value===null?this.storage.values.delete(key):this.storage.values.set(key,value);this.storage.pending.delete(key);}}throw error;}
  if(financeCommand)this.storage.failedRecovery=null;
  if(financeCommand&&typeof window!=='undefined')window.dispatchEvent(new Event('domos-tracking-changed'));
 }
 async commitPlan(context,request,meta,plan){
  const changes={...plan.changes},undoId=Object.keys(changes).length?this.uuid():null;
  if(meta.source==='assistant'){const audit=this.audit(context,request,meta,{success:true,risk:plan.risk,result:plan.result});changes['lifeos4.assistantAudit']=JSON.stringify([...this.read(context,'lifeos4.assistantAudit',[]),audit]);}
  if(undoId)changes['lifeos4.actionUndo']=JSON.stringify([...this.read(context,'lifeos4.actionUndo',[]).map(r=>plan.financeCommand&&r.after?.[FINANCE_KEY]?{id:r.id,profileId:r.profileId,timestamp:r.timestamp,expired:true,used:true,before:{},after:{}}:r),{id:undoId,profileId:context.profileId,timestamp:new Date(this.now()).toISOString(),before:plan.before,after:plan.changes,used:false}]);
  await this.persistChanges(context,changes,plan.financeCommand);if(plan.financeCommand){try{this.effects(request,plan.result)}catch(error){console.error('Finance was saved, but its view could not refresh:',error)}}else this.effects(request,plan.result);return {status:'success',result:plan.result,undoId,risk:plan.risk};
 }
 async recordFailure(context,request,meta,error){if(meta.source!=='assistant')return;const audit=this.audit(context,request,meta,{success:false,error:String(error)});this.applyUIChanges(context,{'lifeos4.assistantAudit':JSON.stringify([...this.read(context,'lifeos4.assistantAudit',[]),audit])});await this.storage.flush();}
 undo(context,id){return this.coordinate(()=>this.undoOrdered(context,id));}
 async undoOrdered(context,id){this.context(context);await this.storage.flush();const records=this.read(context,'lifeos4.actionUndo',[]),record=records.find(x=>x.id===id);if(record?.expired)throw Error('This data changed after the action. Undo would overwrite newer work.');if(!record||record.used||record.profileId!==context.profileId)throw Error('That action cannot be undone.');for(const [key,value] of Object.entries(record.after))if(!sameRaw(this.storage.getItem(key),value))throw Error('This data changed after the action. Undo would overwrite newer work.');record.used=true;const originalActivity=record.after['lifeos4.goalActivity']?JSON.parse(record.after['lifeos4.goalActivity']):[],changedGoals=[...new Set(originalActivity.filter(x=>!(JSON.parse(record.before['lifeos4.goalActivity']||'[]')).some(old=>old.id===x.id)).map(x=>x.goalId))];const restore={...record.before};if(changedGoals.length)restore['lifeos4.goalActivity']=JSON.stringify([...this.read(context,'lifeos4.goalActivity',[]),...changedGoals.map(goalId=>({id:this.uuid(),goalId,timestamp:new Date(this.now()).toISOString(),label:'Change undone'}))]);const audit=this.audit(context,{action:'undo',id},{provider:'Local'},{success:true,result:{undoId:id}});if(FINANCE_KEY in restore){const prior=JSON.parse(restore[FINANCE_KEY]),current=JSON.parse(this.storage.getItem(FINANCE_KEY));prior.revision=current.revision+1;prior.operations=current.operations.map(o=>prior.operations.some(p=>p.id===o.id)?o:{...o,undone:true});validateFinance(prior,context.profileId);restore[FINANCE_KEY]=JSON.stringify(prior);}await this.persistChanges(context,{...restore,'lifeos4.actionUndo':JSON.stringify(records),'lifeos4.assistantAudit':JSON.stringify([...this.read(context,'lifeos4.assistantAudit',[]),audit])},FINANCE_KEY in restore);this.refresh();return {status:'success'};}
}
